### ISSUE TITLE
Bundle built by `buildbundle-veloxbe.sh` for Spark3.3 is broken

### ISSUE THREAD

**Issue by liralon** [oap-project/gluten#1161]
When running the script `buildbundle-veloxbe.sh`, it builds two bundle JARs: One for spark-3.2 and another for spark-3.3 (`gluten-spark3.2_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar` and `gluten-spark3.3_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar` respectively). However, running queries on spark-3.3 bundle result in query plan not utilizing the Velox backend.

Enabling DEBUG prints (via changing log4j properties), showed the following error:
```
INFO SparkShimLoader: Loading Spark Shims for version: 3.3.1
DEBUG GlutenHashAggregateExecTransformer: Validation failed for class io.glutenproject.execution.GlutenHashAggregateExecTransformer due to null
java.lang.NoClassDefFoundError: Could not initialize class io.glutenproject.expression.ExpressionMappings$
        at io.glutenproject.expression.ExpressionConverter$.replaceWithExpressionTransformer(ExpressionConverter.scala:34)
```

What happens here is that Gluten fails to load the Spark Shims for version 3.3.1 which result in `ExpressionMappings` failing to initialize. (The `SparkShimLoader` print is misleading as it just note the attempt to load the Spark Shims, but only after successfully loading, it will print "Using Shim provider: $shimProviders", which it doesn't in this case).

The issue can easily be reproduced/demonstrated by the following in spark-shell:
```
scala> import java.util.ServiceLoader
import java.util.ServiceLoader

scala> val it = ServiceLoader.load(classOf[io.glutenproject.sql.shims.SparkShimProvider]).iterator()
it: java.util.Iterator[io.glutenproject.sql.shims.SparkShimProvider] = java.util.ServiceLoader$1@4fb5adb8

scala> it.hasNext()
res0: Boolean = true

scala> it.next()
res1: io.glutenproject.sql.shims.SparkShimProvider = io.glutenproject.sql.shims.spark32.SparkShimProvider@4d21ca52

scala> it.next()
java.util.NoSuchElementException
  at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:365)
  at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
  at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
  ... 47 elided
  ```

Examining the produced bundle JAR for spark-3.3 shows that it's `META-INF/services/io.glutenproject.sql.shims.SparkShimProvider` file contain the value of `io.glutenproject.sql.shims.spark32.SparkShimProvider` instead of the value of `io.glutenproject.sql.shims.spark33.SparkShimProvider`. In addition, it shows that both the `spark32` and the `spark33` shims were built into it, instead of only the `spark33` as is the case for the spark-3.2 bundle JAR.

Therefore, the root-cause of the issue is how the spark-3.3 bundle JAR is built. Manually commenting out `mvn package -Pbackends-velox -Pspark-3.2 -DskipTests` out of `dev/buildbundle-veloxbe.sh` fixed the issue. It built spark-3.3 bundle JAR correctly. I have verified that this result in queries properly utilizing the Velox backend (e.g. Query plan shows use of `GlutenHashAggregateExecTransformer` operator rather than simple `HashAggregate` operator).

**Comment by zhouyuan** [comment]
@liralon 
Thanks for reporting, I also ran into this issue before, the fix is to add `clean` goal for mvn in the script:
mvn **clean** package -Pbackends-velox -Pspark-3.2 -DskipTests
mvn **clean** package -Pbackends-velox -Pspark-3.3 -DskipTests

CC: @zhejiangxiaomai 

-yuan

**Comment by zhejiangxiaomai** [comment]
I see. will add ```clean``` in buildbundle-veloxbe.sh.
