### ISSUE TITLE
FileNotFoundException while executing spark jobs -*.so* files

### ISSUE THREAD

**Issue by gshenoy123** [oap-project/gluten#1175]
Hi I have built gluten using $GLUTEN_DIR/dev/buildbundle-veloxbe.sh. My environment is Windows 10 and I am running WSL - Ubuntu 22.04.  I have written a spark SQL job which groups data using a column. I submit spark job to local cluster. Cluster is having one master and worker with 1 CPU core each and 1GB memory allocated.

Spark submit command -

```
./spark-submit.sh --master spark://localhost:7077 \
  --conf spark.plugins=io.glutenproject.GlutenPlugin \
  --conf spark.gluten.sql.columnar.backend.lib=velox \
  --conf spark.driver.extraClassPath="/mnt/d/dev/projects/gluten/backends-velox/target/backends-velox-0.5.0-SNAPSHOT-3.3.jar:/mnt/d/dev/projects/gluten/ep/build-arrow/build/arrow_install/lib/" \
  --conf spark.executor.extraClassPath="/mnt/d/dev/projects/gluten/backends-velox/target/backends-velox-0.5.0-SNAPSHOT-3.3.jar:/mnt/d/dev/projects/gluten/ep/build-arrow/build/arrow_install/lib/" \
  --conf spark.memory.offHeap.enabled=true \
  --conf spark.memory.offHeap.size=512m \
  --conf spark.gluten.sql.columnar.forceshuffledhashjoin=true \
  --conf spark.shuffle.manager=org.apache.spark.shuffle.sort.ColumnarShuffleManager \
  --conf spark.gluten.sql.columnar.iterator=true \
  --conf spark.gluten.sql.columnar.loadarrow=false \
  --conf spark.gluten.sql.columnar.backend.lib=velox \
  --num-executors 1 \
  --executor-cores 1 \
  --driver-memory 1g \
  --executor-memory 2g \
  --conf spark.executor.memoryOverhead=1g \
  --conf spark.driver.maxResultSize=256m \
  --class org.samples.sparksubmit.SparkMain "/mnt/d/dev/spark-submit-example/target/neo-calc.jar"

```

But when I execute above I get exception below. Note that I had **libarrow.so.1100.0.0/libparquet.so.1100.0.0 - FileNotFoundException**, I added these files in classpath and issue got resolved. But after that fix, **the 'VeloxInitializerApi.initialize' is looking for 'libgluten.so', 'libvelox.so'**.  I am not able find these libraries also being generated as a part of the build, can you please help identifying any issue in build or configuration.  Do we have any other libs we need to look at other than above. 

```
23/03/21 19:30:56 ERROR SparkContext: Error initializing SparkContext.
java.lang.RuntimeException: java.io.FileNotFoundException: libgluten.so
        at io.glutenproject.vectorized.JniLibLoader$JniLoadTransaction.lambda$commit$0(JniLibLoader.java:249)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:269)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at io.glutenproject.vectorized.JniLibLoader$JniLoadTransaction.commit(JniLibLoader.java:252)
        at io.glutenproject.vectorized.JniLibLoader.mapAndLoad(JniLibLoader.java:107)
        at io.glutenproject.backendsapi.velox.VeloxInitializerApi.initialize(VeloxInitializerApi.scala:46)
        at io.glutenproject.GlutenDriverPlugin.init(GlutenPlugin.scala:51)
        at org.apache.spark.internal.plugin.DriverPluginContainer.$anonfun$driverPlugins$1(PluginContainer.scala:53)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
        at org.apache.spark.internal.plugin.DriverPluginContainer.<init>(PluginContainer.scala:46)
        at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:210)
        at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:193)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:570)
        at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2714)
        at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:953)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:947)
        at org.amma.samples.sparksubmit.SparkMain.main(SparkMain.java:18)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:958)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.io.FileNotFoundException: libgluten.so
        at io.glutenproject.vectorized.JniLibLoader$JniLoadTransaction.moveToWorkDir(JniLibLoader.java:313)
        at io.glutenproject.vectorized.JniLibLoader$JniLoadTransaction.lambda$commit$0(JniLibLoader.java:245)
        ... 41 more
```

**Comment by Yohahaha** [comment]
Maybe you should use jars under path-to-gluten/package/target/gluten-xxx.jar.

Use `jar -tf xxx.jar | grep lib` to check whether it has needed native lib.
