### ISSUE TITLE
Runtime error - Failed loading library libarrow.so.1100.0.0

### ISSUE THREAD

**Issue by shtein-vs** [oap-project/gluten#1317]
I'm using Gluten with VL as a backend on Ubuntu 20.04 machines.
I compiled Gluten with Velox using the script dev/buildbundle-veloxbe.sh and taking the JAR gluten-velox-bundle-spark3.3_2.12-ubuntu_20.04-0.5.0-SNAPSHOT.jar (from package/targets).
I'm compiling it on 1 machine (using a docker) and copy the JAR to the Ubuntu machines (to avoid compiling it multiple times)
That worked fine!

Then I synced to a latest version of gluten and compiled it the same way as did before. On the machines I am running I just replaced the JAR with the updated one. While running the same job I used to run I got the following runtime error:
```
23/04/09 19:23:51 INFO Utils: Successfully started service 'SparkUI' on port 4040.
23/04/09 19:23:51 INFO SparkContext: Added JAR file:/mnt/spark/jars/spark-sql-perf_spark3_2.12_1673446848.jar at spark://ip-172-31-30-161.us-east-2.compute.internal:43725/jars/spark-sql-perf_spark3_2.12_1673446848.jar with timestamp 1681068231095
23/04/09 19:23:51 INFO SparkDirectoryUtil: Created local directory at /media/ephemeral0/spark/gluten-d7a8cb84-655b-4e46-ac4f-81821479acab
23/04/09 19:23:52 INFO JniWorkspace: Creating JNI workspace in root directory /media/ephemeral0/spark/gluten-d7a8cb84-655b-4e46-ac4f-81821479acab/jni/283671a0-425b-4c64-8f1c-e69d308dd76a
23/04/09 19:23:52 INFO JniWorkspace: JNI workspace /media/ephemeral0/spark/gluten-d7a8cb84-655b-4e46-ac4f-81821479acab/jni/283671a0-425b-4c64-8f1c-e69d308dd76a/gluten-8949048098835699965 created in root directory /media/ephemeral0/spark/gluten-d7a8cb84-655b-4e46-ac4f-81821479acab/jni/283671a0-425b-4c64-8f1c-e69d308dd76a
23/04/09 19:23:52 INFO JniLibLoader: Trying to load library libarrow.so.1100.0.0
Exception in thread "main" java.lang.UnsatisfiedLinkError: /media/ephemeral0/spark/gluten-d7a8cb84-655b-4e46-ac4f-81821479acab/jni/283671a0-425b-4c64-8f1c-e69d308dd76a/gluten-8949048098835699965/libarrow.so.1100.0.0: /media/ephemeral0/spark/gluten-d7a8cb84-655b-4e46-ac4f-81821479acab/jni/283671a0-425b-4c64-8f1c-e69d308dd76a/gluten-8949048098835699965/libarrow.so.1100.0.0: failed to map segment from shared object
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:782)
	at java.lang.System.load(System.java:1100)
	at io.glutenproject.vectorized.JniLibLoader.loadFromPath0(JniLibLoader.java:88)
	at io.glutenproject.vectorized.JniLibLoader.access$300(JniLibLoader.java:56)
	at io.glutenproject.vectorized.JniLibLoader$JniLoadTransaction.loadWithLink(JniLibLoader.java:315)
	at io.glutenproject.vectorized.JniLibLoader$JniLoadTransaction.lambda$commit$1(JniLibLoader.java:265)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at io.glutenproject.vectorized.JniLibLoader$JniLoadTransaction.commit(JniLibLoader.java:262)
	at io.glutenproject.backendsapi.velox.VeloxInitializerApi.initialize(VeloxInitializerApi.scala:49)
	at io.glutenproject.GlutenDriverPlugin.init(GlutenPlugin.scala:49)
```
Per my understanding the libarrow.so should be loaded from the JAR itself so there should not be an issue that the machine has incompatible version of libarrow than expected.

**Comment by zhouyuan** [comment]
@shtein-vs thanks for reporting, looks like it's related with the dependency issue @zhejiangxiaomai is actually trying to improve this. Can you please have a try on our prebuilt packages for Ubuntu20.04 here(https://github.com/oap-project/gluten/releases/tag/0.5.0)? It should contains all libraries needed

-yuan

**Comment by zhejiangxiaomai** [comment]
Yes, here is command.
```
spark-shell --name run_gluten \
 --master yarn --deploy-mode client \
 --conf spark.plugins=io.glutenproject.GlutenPlugin \
 --conf spark.gluten.sql.columnar.backend.lib=velox \
 --conf spark.memory.offHeap.enabled=true \
 --conf spark.memory.offHeap.size=20g \
 --conf spark.gluten.loadLibFromJar=true \
 --jars https://github.com/oap-project/gluten/releases/download/0.5.0/gluten-velox-bundle-spark3.2_2.12-ubuntu_20.04-0.5.0-SNAPSHOT.jar,https://github.com/oap-project/gluten/releases/download/0.5.0/gluten-thirdparty-lib-ubuntu-20.04.jar 
```

**Comment by liralon** [comment]
I have root-caused this issue to when the JNI workspace directory is set to a path within a VFS mount that is mounted with `noexec` (As can be seen by `cat /proc/mounts`). In that case, `libarrow.so` is attempted to be mapped as executable from a non-executable mount point. I have noticed this issue is resolved when remounting the path with `sudo mount -o remount,exec [path]`.
