### ISSUE TITLE
would not run gluten on Anolis OS 7/8

### ISSUE THREAD

**Issue by leesf** [oap-project/gluten#1367]
**Describe the bug**
When running gluten on Anolis OS 7/8
the info is below

```
NAME="Anolis OS"
VERSION="8.4"
ID="anolis"
ID_LIKE="rhel fedora centos"
VERSION_ID="8.4"
PLATFORM_ID="platform:an8"
PRETTY_NAME="Anolis OS 8.4"
ANSI_COLOR="0;31"
HOME_URL="https://openanolis.cn/"

```

following exception is thrown

```
Exception in thread "main" java.lang.ClassCastException: scala.runtime.BoxedUnit cannot be cast to io.glutenproject.utils.VeloxSharedlibraryLoader
	at io.glutenproject.backendsapi.velox.VeloxInitializerApi.loadLibFromJar(VeloxInitializerApi.scala:40)
	at io.glutenproject.backendsapi.velox.VeloxInitializerApi.initialize(VeloxInitializerApi.scala:48)
	at io.glutenproject.GlutenDriverPlugin.init(GlutenPlugin.scala:49)
	at 

```

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by FelixYBW** [comment]
@Yohahaha

**Comment by Yohahaha** [comment]
Hi @leesf 
We have support Gluten in Alinux3, but not verified in Alinux2.

**Comment by PengleiShi** [comment]
@Yohahaha Does gluten support Anolis OS 8? It seems there are some difference between Alinux and Anolis OS.

**Comment by Yohahaha** [comment]
> @Yohahaha Does gluten support Anolis OS 8? It seems there are some difference between Alinux and Anolis OS.

it's should be supported.
