### ISSUE TITLE
Error while reading iceberg:  `batch is not Arrow columnar batch`

### ISSUE THREAD

**Issue by jinhaichen** [oap-project/gluten#1440]
the error info is `batch is not Arrow columnar batch`.

```
23/04/20 13:32:53 INFO BlockManagerMaster: BlockManagerMaster stopped
23/04/20 13:32:53 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
23/04/20 13:32:53 INFO SparkContext: Successfully stopped SparkContext
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (1.2.200.100 executor 3): java.lang.RuntimeException: Error during calling Java code from native code: java.lang.IllegalArgumentException: batch is not Arrow columnar batch
	at io.glutenproject.columnarbatch.ArrowColumnarBatches.offload(ArrowColumnarBatches.java:121)
	at io.glutenproject.columnarbatch.ArrowColumnarBatches.ensureOffloaded(ArrowColumnarBatches.java:172)
	at io.glutenproject.vectorized.ArrowInIterator.next(ArrowInIterator.java:36)
	at io.glutenproject.vectorized.ArrowOutIterator.nativeHasNext(Native Method)
	at io.glutenproject.vectorized.ArrowOutIterator.hasNextInternal(ArrowOutIterator.java:48)
	at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37)
	at io.glutenproject.backendsapi.glutendata.GlutenIteratorApi$$anon$3.hasNext(GlutenIteratorApi.scala:300)
	at io.glutenproject.vectorized.CloseableColumnBatchIterator.hasNext(CloseableColumnBatchIterator.scala:41)
```

Please have a check.

**Comment by zhouyuan** [comment]
hi @jinhaichen 

I assume the test is using Velox backend(?). iceberg/hudi/deltalake is not supported yet. Velox backend do have some rough plans to support those lakehouse based solutions in 2H23. The main gap is Velox does not have "connectors" for those lakehouse. 

Thanks, -yuan

**Comment by jinhaichen** [comment]
> hi @jinhaichen
> 
> I assume the test is using Velox backend(?). iceberg/hudi/deltalake is not supported yet. Velox backend do have some rough plans to support those lakehouse based solutions in 2H23. The main gap is Velox does not have "connectors" for those lakehouse.
> 
> Thanks, -yuan

> 
Hi @zhouyuan  
Sorry for my unclear description. The test is run using **Velox** backend.

I would like to know the specific reason why the iceberg table cannot be read. Or whether it can be achieved theoretically in the future？

By the way, I have no idea with what 2H23 is. Could you please give me some reference?

**Comment by zhouyuan** [comment]
@jinhaichen sure. here's some more details:

- hudi/iceberg/delta provides Java based connectors in vanilla Spark. Gluten could support these lakehouse solutions via "resuing" vanilla Spark's codes(fallback to run with JVM code). I actually have tried delta lake and find the basic read should be OK, but there are many bugs during upsert. Also the performance is not good as it has to do many memory copies between C++ and JVM. 
- The ideal impl should be adding a C++ based connector for those lakehouse in Velox, just like the HDFS/S3 support. There's already some discussion on Velox community.  https://github.com/facebookincubator/velox/discussions/4088  once these connectors are ready, Gluten should be able to pick up these and talk with lakehouse easily. "2H23" means the 2nd half of 2023. it's mostly due to limited resource issue as we have many features in the 1st half already. 

would you like to join gluten wechat group? it might be easier to talk with Chinese for many PRC developers

Thanks, -yuan

**Comment by PHILO-HE** [comment]
Hi @jinhaichen, recently vanilla spark's vectorized reader is supported by https://github.com/oap-project/gluten/pull/1931, which may fix your mentioned exception. As pointed by yuan, there may have other gaps for supporting iceberg. Anyway, if you are interested, you can have a try again. Thanks!

**Comment by jinhaichen** [comment]
Thanks for your great work! Now it runs well.
