### ISSUE TITLE
[CH] fix aggregate bug for clickhouse backend

### ISSUE THREAD

**Issue by taiyang-li** [oap-project/gluten#1455]
```
SELECT hdid,abflag,abflag_source
FROM
(
  SELECT
  trim(hdid) as hdid,
  trim(event.log_extra['abflags_v2']) as abflags_v2,
  'test_field' as abflag_source
  FROM vlog.like_user_event_hour_orc
  WHERE day = '2023-04-17' and hour = '11' and event_id in ('0101004','010106001') and event.log_extra['abflags_v2'] is not null and hdid is not null and hdid != ''
  limit 100
) t1
lateral view explode(split(regexp_replace(regexp_extract(abflags_v2,'group_name\\"\\:\\[(.*)\\]'),'\\"',''),',')) abflags as abflag
GROUP BY hdid,abflag,abflag_source
```

```
Header: hdid#0 Nullable(String) Nullable(size = 0, String(size = 0), UInt8(size = 0)), abflag#43 Nullable(String) Nullable(size = 0, String(size = 0), UInt8(size = 0)), test_field#123 String String(size = 0)
Chunk:  Nullable(size = 6680, String(size = 6680), UInt8(size = 6680)) Nullable(size = 6680, String(size = 6680), UInt8(size = 6680))

0. ./build_gcc/./contrib/llvm-project/libcxx/include/exception:134: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) @ 0x191671da in /data14/hadoop/yarn/local/usercache/liyang/filecache/18/libch.so
1. ./build_gcc/./src/Common/Exception.cpp:91: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x12c7b8d5 in /data14/hadoop/yarn/local/usercache/liyang/filecache/18/libch.so
2. ./build_gcc/./contrib/llvm-project/libcxx/include/string:1499: DB::Exception::Exception<unsigned long, unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>(int, FormatStringHelperImpl<std::__1::type_identity<unsigned long>::type, std::__1::type_identity<unsigned long>::type, std::__1::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type, std::__1::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type>, unsigned long&&, unsigned long&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&) @ 0xc00a47f in /data14/hadoop/yarn/local/usercache/liyang/filecache/18/libch.so
3. ./build_gcc/./src/Processors/Port.h:0: DB::ISource::prepare() @ 0x15d79612 in /data14/hadoop/yarn/local/usercache/liyang/filecache/18/libch.so
4. ./build_gcc/./src/Processors/Executors/ExecutingGraph.cpp:0: DB::ExecutingGraph::updateNode(unsigned long, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*>>>&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*>>>&) @ 0x15d8bd15 in /data14/hadoop/yarn/local/usercache/liyang/filecache/18/libch.so
5. ./build_gcc/./src/Processors/Executors/PipelineExecutor.cpp:248: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x15d87409 in /data14/hadoop/yarn/local/usercache/liyang/filecache/18/libch.so
6. ./build_gcc/./contrib/llvm-project/libcxx/include/atomic:958: DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0x15d86ec9 in /data14/hadoop/yarn/local/usercache/liyang/filecache/18/libch.so
7. ./build_gcc/./src/Processors/Executors/PullingPipelineExecutor.cpp:54: DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x15d945ea in /data14/hadoop/yarn/local/usercache/liyang/filecache/18/libch.so
8. ./build_gcc/./src/Processors/Executors/PullingPipelineExecutor.cpp:0: DB::PullingPipelineExecutor::pull(DB::Block&) @ 0x15d947d0 in /data14/hadoop/yarn/local/usercache/liyang/filecache/18/libch.so
9. ./build_gcc/./utils/extern-local-engine/Parser/SerializedPlanParser.cpp:0: local_engine::LocalExecutor::hasNext() @ 0xbc79e50 in /data14/hadoop/yarn/local/usercache/liyang/filecache/18/libch.so
10. ./build_gcc/./utils/extern-local-engine/local_engine_jni.cpp:260: Java_io_glutenproject_vectorized_BatchIterator_nativeHasNext @ 0xc047677 in /data14/hadoop/yarn/local/usercache/liyang/filecache/18/libch.so

        at io.glutenproject.vectorized.BatchIterator.nativeHasNext(Native Method)
        at io.glutenproject.vectorized.BatchIterator.hasNextInternal(BatchIterator.java:49)
        at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37)
        at io.glutenproject.backendsapi.clickhouse.CHIteratorApi$$anon$3.hasNext(CHIteratorApi.scala:252)
        at io.glutenproject.vectorized.CloseableCHColumnBatchIterator.hasNext(CloseableCHColumnBatchIterator.scala:41)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:350)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1491)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by taiyang-li** [comment]
问题在于这里：

substrait plan对应聚合算子，其中输入schema是[hdid, abflag, test_field],  跟spark plan中partial aggregate算子的input不一致(多了一个test_field)
```
(8) CHHashAggregateExecTransformer
Input [2]: [hdid#661, abflag#671]
Keys [3]: [hdid#661, abflag#671, test_field AS test_field#710]
Functions: []
Aggregate Attributes: []
Results [3]: [hdid#661, abflag#671, test_field#710]
```

```
substrait plan:{"extensions":[{"extensionFunction":{"name":"alias:req_str"}}],"relations":[{"root":{"input":{"project":{"common":{"emit":{"outputMapping":[3,4,5]}},"input":{"aggregate":{"common":{"direct":{}},"input":{"aggregate":{"common":{"direct":{}},"input":{"project":{"common":{"emit":{"outputMapping":[2,3,4]}},"input":{"read":{"common":{"direct":{}},"baseSchema":{"names":["hdid#0","abflag#43","test_field#123"],"struct":{"types":[{"string":{"nullability":"NULLABILITY_NULLABLE"}},{"string":{"nullability":"NULLABILITY_NULLABLE"}},{"string":{"nullability":"NULLABILITY_REQUIRED"}}]}},"localFiles":{"items":[{"uriFile":"iterator:0"}]}}},"expressions":[{"selection":{"directReference":{"structField":{}}}},{"selection":{"directReference":{"structField":{"field":1}}}},{"scalarFunction":{"outputType":{"string":{"nullability":"NULLABILITY_REQUIRED"}},"arguments":[{"value":{"literal":{"string":"test_field"}}}]}}]}},"groupings":[{"groupingExpressions":[{"selection":{"directReference":{"structField":{}}}},{"selection":{"directReference":{"structField":{"field":1}}}},{"selection":{"directReference":{"structField":{"field":2}}}}]}]}},"groupings":[{"groupingExpressions":[{"selection":{"directReference":{"structField":{}}}},{"selection":{"directReference":{"structField":{"field":1}}}},{"selection":{"directReference":{"structField":{"field":2}}}}]}]}},"expressions":[{"selection":{"directReference":{"structField":{}}}},{"selection":{"directReference":{"structField":{"field":1}}}},{"scalarFunction":{"outputType":{"string":{"nullability":"NULLABILITY_REQUIRED"}},"arguments":[{"value":{"literal":{"string":"test_field"}}}]}}]}},"names":["hdid#0","abflag#43","abflag_source#2"]}}]}
```
