### ISSUE TITLE
libch.so coredump when release rocksdb static resources 

### ISSUE THREAD

**Issue by taiyang-li** [oap-project/gluten#1649]
```
(gdb) 
(gdb) bt 
#0  0x00007f631c5bc438 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f631c5be03a in __GI_abort () at abort.c:89
#2  0x00000000004419cc in programming_error ()
#3  0x00000000004b91f0 in ?? ()
#4  0x00007f6330df3661 in rocksdb::LRUCache::~LRUCache (this=0x15b7420) at ./contrib/rocksdb/cache/lru_cache.cc:665
#5  0x00007f632dbeeff1 in std::__1::__shared_count::__release_shared[abi:v15000]() (this=<optimized out>) at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:174
#6  std::__1::__shared_weak_count::__release_shared[abi:v15000]() (this=<optimized out>) at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:215
#7  std::__1::shared_ptr<rocksdb::Cache>::~shared_ptr[abi:v15000]() (this=0x15b7068) at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:702
#8  rocksdb::BlockBasedTableOptions::~BlockBasedTableOptions (this=0x15b7030) at ./contrib/rocksdb/include/rocksdb/table.h:104
#9  0x00007f63310347ae in rocksdb::BlockBasedTableFactory::~BlockBasedTableFactory (this=0x15b7008) at ./contrib/rocksdb/table/block_based/block_based_table_factory.h:47
#10 rocksdb::BlockBasedTableFactory::~BlockBasedTableFactory (this=0x15b7008) at ./contrib/rocksdb/table/block_based/block_based_table_factory.h:47
#11 0x00007f6330e18bb9 in std::__1::__shared_count::__release_shared[abi:v15000]() (this=0x15b65c8) at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:174
#12 std::__1::__shared_weak_count::__release_shared[abi:v15000]() (this=0x15b65c8) at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:215
#13 std::__1::shared_ptr<rocksdb::TableFactory>::~shared_ptr[abi:v15000]() (this=0x7f6332ab5e00 <rocksdb::dummy_cf_options+232>) at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:702
#14 rocksdb::ImmutableCFOptions::~ImmutableCFOptions (this=0x7f6332ab5d18 <rocksdb::dummy_cf_options>) at ./contrib/rocksdb/options/cf_options.h:22
s#15 0x00007f631c5c137a in __cxa_finalize (d=0x7f633270a0c0) at cxa_finalize.c:56
#16 0x00007f63237519d7 in __do_global_dtors_aux () from ./libch.so
#17 0x00007ffe3ccd2c50 in ?? ()
#18 0x00007f6332ae1e27 in _dl_fini () at dl-fini.c:235
Backtrace stopped: frame did not save the PC

```

**Comment by taiyang-li** [comment]
It was fixed by excluding rocksdb during building libch.so
