### ISSUE TITLE
Run mvn test failed with profile backends-velox-without-rss and spark-ut

### ISSUE THREAD

**Issue by jackylee-ch** [oap-project/gluten#1747]
**Describe the bug**
Currently, we found mvn test run failed with `mvn clean test -Pbackends-velox-without-rss -Pspark-ut -Pspark-3.3 -DskipTests`. The reason is that `gluten-ut` module does not support `backends-velox-without-rss`, and would not add backends dependencies into it.
```
2023-05-24 13:26:48 GlutenStringFunctionsSuite:
2023-05-24 13:26:49 org.apache.spark.sql.GlutenStringFunctionsSuite *** ABORTED ***
2023-05-24 13:26:49   java.lang.RuntimeException: Unable to load a Suite class that was discovered in the runpath: org.apache.spark.sql.GlutenStringFunctionsSuite
2023-05-24 13:26:49   at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:81)
2023-05-24 13:26:49   at org.scalatest.tools.DiscoverySuite.$anonfun$nestedSuites$1(DiscoverySuite.scala:38)
2023-05-24 13:26:49   at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
2023-05-24 13:26:49   at scala.collection.Iterator.foreach(Iterator.scala:943)
2023-05-24 13:26:49   at scala.collection.Iterator.foreach$(Iterator.scala:943)
2023-05-24 13:26:49   at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
2023-05-24 13:26:49   at scala.collection.IterableLike.foreach(IterableLike.scala:74)
2023-05-24 13:26:49   at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
2023-05-24 13:26:49   at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
2023-05-24 13:26:49   at scala.collection.TraversableLike.map(TraversableLike.scala:286)
2023-05-24 13:26:49   ...
2023-05-24 13:26:49   Cause: java.lang.ExceptionInInitializerError:
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenTestsBaseTrait.shouldRun(GlutenTestsBaseTrait.scala:42)
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenTestsBaseTrait.shouldRun$(GlutenTestsBaseTrait.scala:35)
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenStringFunctionsSuite.shouldRun(GlutenStringFunctionsSuite.scala:22)
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenSQLTestsBaseTrait.test(GlutenSQLTestsBaseTrait.scala:36)
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenSQLTestsBaseTrait.test$(GlutenSQLTestsBaseTrait.scala:34)
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenStringFunctionsSuite.test(GlutenStringFunctionsSuite.scala:22)
2023-05-24 13:26:49   at org.apache.spark.sql.StringFunctionsSuite.<init>(StringFunctionsSuite.scala:28)
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenStringFunctionsSuite.<init>(GlutenStringFunctionsSuite.scala:22)
2023-05-24 13:26:49   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2023-05-24 13:26:49   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2023-05-24 13:26:49   ...
2023-05-24 13:26:49   Cause: java.lang.IllegalStateException: Backend implementation not discovered from JVM classpath
2023-05-24 13:26:49   at io.glutenproject.backendsapi.BackendsApiManager$.initializeInternal(BackendsApiManager.scala:44)
2023-05-24 13:26:49   at io.glutenproject.backendsapi.BackendsApiManager$.manager$lzycompute(BackendsApiManager.scala:37)
2023-05-24 13:26:49   at io.glutenproject.backendsapi.BackendsApiManager$.manager(BackendsApiManager.scala:37)
2023-05-24 13:26:49   at io.glutenproject.backendsapi.BackendsApiManager$.getBackendName(BackendsApiManager.scala:73)
2023-05-24 13:26:49   at io.glutenproject.utils.BackendTestSettings$.<init>(BackendTestSettings.scala:136)
2023-05-24 13:26:49   at io.glutenproject.utils.BackendTestSettings$.<clinit>(BackendTestSettings.scala)
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenTestsBaseTrait.shouldRun(GlutenTestsBaseTrait.scala:42)
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenTestsBaseTrait.shouldRun$(GlutenTestsBaseTrait.scala:35)
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenStringFunctionsSuite.shouldRun(GlutenStringFunctionsSuite.scala:22)
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenSQLTestsBaseTrait.test(GlutenSQLTestsBaseTrait.scala:36)
2023-05-24 13:26:49   ...
2023-05-24 13:26:49 *** RUN ABORTED ***
2023-05-24 13:26:49   java.lang.ExceptionInInitializerError:
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenTestsBaseTrait.shouldRun(GlutenTestsBaseTrait.scala:42)
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenTestsBaseTrait.shouldRun$(GlutenTestsBaseTrait.scala:35)
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenStringFunctionsSuite.shouldRun(GlutenStringFunctionsSuite.scala:22)
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenSQLTestsBaseTrait.test(GlutenSQLTestsBaseTrait.scala:36)
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenSQLTestsBaseTrait.test$(GlutenSQLTestsBaseTrait.scala:34)
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenStringFunctionsSuite.test(GlutenStringFunctionsSuite.scala:22)
2023-05-24 13:26:49   at org.apache.spark.sql.StringFunctionsSuite.<init>(StringFunctionsSuite.scala:28)
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenStringFunctionsSuite.<init>(GlutenStringFunctionsSuite.scala:22)
2023-05-24 13:26:49   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2023-05-24 13:26:49   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2023-05-24 13:26:49   ...
2023-05-24 13:26:49   Cause: java.lang.IllegalStateException: Backend implementation not discovered from JVM classpath
2023-05-24 13:26:49   at io.glutenproject.backendsapi.BackendsApiManager$.initializeInternal(BackendsApiManager.scala:44)
2023-05-24 13:26:49   at io.glutenproject.backendsapi.BackendsApiManager$.manager$lzycompute(BackendsApiManager.scala:37)
2023-05-24 13:26:49   at io.glutenproject.backendsapi.BackendsApiManager$.manager(BackendsApiManager.scala:37)
2023-05-24 13:26:49   at io.glutenproject.backendsapi.BackendsApiManager$.getBackendName(BackendsApiManager.scala:73)
2023-05-24 13:26:49   at io.glutenproject.utils.BackendTestSettings$.<init>(BackendTestSettings.scala:136)
2023-05-24 13:26:49   at io.glutenproject.utils.BackendTestSettings$.<clinit>(BackendTestSettings.scala)
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenTestsBaseTrait.shouldRun(GlutenTestsBaseTrait.scala:42)
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenTestsBaseTrait.shouldRun$(GlutenTestsBaseTrait.scala:35)
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenStringFunctionsSuite.shouldRun(GlutenStringFunctionsSuite.scala:22)
2023-05-24 13:26:49   at org.apache.spark.sql.GlutenSQLTestsBaseTrait.test(GlutenSQLTestsBaseTrait.scala:36)
2023-05-24 13:26:49   ...
```

**To Reproduce**
`mvn clean test -Pbackends-velox-without-rss -Pspark-ut -Pspark-3.3 -DskipTests`

**Additional context**
Although it works while adding `backends-velox-without-rss` in spark-ut, I found it look awful as we have too many similar config in pom.xml. The `backends-velox` in pom.xml has nothring to do with rss in almost every module except for `backends-velox` module and parent pom.xml. Thus I recomanded we use `-Pbackends` to define the config for velox and use `-Prss` to define the config for rss module, such as `gluten-celeborn`.

**Comment by PHILO-HE** [comment]
Suppose fixed. Closing this issue.
