### ISSUE TITLE
libre2.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lifulong** [oap-project/gluten#2094]
use Prebuilt jar submit spark test job spark version is 3.2.4  submit error

spark submit command(use local downloaded gluten jar instead of download from github each submit):
--conf spark.plugins=io.glutenproject.GlutenPlugin --conf spark.gluten.sql.columnar.backend.lib=velox --conf spark.gluten.loadLibFromJar=true --conf spark.shuffle.manager=org.apache.spark.shuffle.sort.ColumnarShuffleManager --jars /home/lifulong/tpc_h_parquet/gluten_jars/gluten-thirdparty-lib-ubuntu-20.04.jar,/home/lifulong/tpc_h_parquet/gluten_jars/gluten-velox-bundle-spark3.2_2.12-ubuntu_20.04-0.5.0-SNAPSHOT.jar

error msg:
Exception in thread "main" java.lang.UnsatisfiedLinkError: /data1/sparktmp/gluten-d1634de2-f6d6-4724-a92b-4c7e7604104f/jni/d7604432-ce53-4c88-9d38-263dc7b143bf/gluten-5705549510796417282/libarrow.so.1100.0.0: libre2.so.5: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at io.glutenproject.vectorized.JniLibLoader.loadFromPath0(JniLibLoader.java:88)
	at io.glutenproject.vectorized.JniLibLoader.access$300(JniLibLoader.java:56)
	at io.glutenproject.vectorized.JniLibLoader$JniLoadTransaction.loadWithLink(JniLibLoader.java:315)
	at io.glutenproject.vectorized.JniLibLoader$JniLoadTransaction.lambda$commit$1(JniLibLoader.java:265)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at io.glutenproject.vectorized.JniLibLoader$JniLoadTransaction.commit(JniLibLoader.java:262)
	at io.glutenproject.backendsapi.velox.VeloxInitializerApi.initialize(VeloxInitializerApi.scala:49)
	at io.glutenproject.GlutenDriverPlugin.init(GlutenPlugin.scala:49)
	at org.apache.spark.internal.plugin.DriverPluginContainer.$anonfun$driverPlugins$1(PluginContainer.scala:57)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at org.apache.spark.internal.plugin.DriverPluginContainer.<init>(PluginContainer.scala:46)
	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:214)
	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:197)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:566)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2700)
	at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:949)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:943)
	at pkg.Main.spark2ParquetTest(Main.java:46)
	at pkg.Main.main(Main.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:988)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:213)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:236)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:92)
	at org.apache.spark.deploy.SparkSubmit$$anon$3.doSubmit(SparkSubmit.scala:1076)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1085)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by zhejiangxiaomai** [comment]
Would you try this? @lifulong  you need include gluten-thirdparty-lib-ubuntu-20.04.jar. and use  --conf spark.gluten.loadLibFromJar=true.
```
spark-shell --name run_gluten \
 --master yarn --deploy-mode client \
 --conf spark.plugins=io.glutenproject.GlutenPlugin \
 --conf spark.gluten.sql.columnar.backend.lib=velox \
 --conf spark.memory.offHeap.enabled=true \
 --conf spark.memory.offHeap.size=20g \
 --conf spark.gluten.loadLibFromJar=true \
 --conf spark.shuffle.manager=org.apache.spark.shuffle.sort.ColumnarShuffleManager \
 --jars https://github.com/oap-project/gluten/releases/download/0.5.0/gluten-velox-bundle-spark3.2_2.12-ubuntu_20.04-0.5.0-SNAPSHOT.jar,https://github.com/oap-project/gluten/releases/download/0.5.0/gluten-thirdparty-lib-ubuntu-20.04.jar 
```

**Comment by lifulong** [comment]
> 

i have set spark.gluten.loadLibFromJar=true and downloaded gluten-thirdparty-lib-ubuntu-20.04.jar to local and use downloaded jar
because download from github while submit spark job will socket timeout
