### ISSUE TITLE
Crash when convert nullable complex type columns to arrow table during native insert into parquet table 

### ISSUE THREAD

**Issue by taiyang-li** [oap-project/gluten#2344]
Reproduce 
``` cpp
  Block header;

    // map field
    {
        ColumnWithTypeAndName col;
        col.name = "map_field";
        String str_type = "Nullable(Map(Int32, Nullable(Int64)))";
        col.type = DataTypeFactory::instance().get(str_type);
        header.insert(std::move(col));
    }

   Block block = header.cloneEmpty();
   auto columns = block.mutateColumns();

  size_t rows = 10;
    for (size_t i = 0; i < rows; i++)
    {
        /// map_field
        {
            Map map;

            Tuple tuple1{Int32(i), Int64(i + 1)};
            map.emplace_back(std::move(tuple1));

            Tuple tuple2{Int32(i + 2), Int64(i + 3)};
            map.emplace_back(std::move(tuple2));

            columns[0]->insert(std::move(map));
        }
  }


    // Convert CH Block to Arrow Table
    std::shared_ptr<arrow::Table> arrow_table;
    CHColumnToArrowColumn ch2arrow(header, "Parquet", false, true, true);
    Chunk chunk{std::move(columns), rows};
    std::vector<Chunk> chunks;
    chunks.push_back(std::move(chunk));
    ch2arrow.chChunkToArrowTable(arrow_table, chunks, block.columns());
    std::cout << "arrow_table->num_rows() = " << arrow_table->num_rows() << std::endl;
    std::cout << "arrow_table->ToString() = " << arrow_table->ToString() << std::endl;

```

**Comment by taiyang-li** [comment]
When above source codes are built with debug mode, crash will happen:

```
(gdb) bt 
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f4b6806e859 in __GI_abort () at abort.c:79
#2  0x00007f4b6806e729 in __assert_fail_base (fmt=0x7f4b68204588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x877910 "(n >= (static_cast<ssize_t>(pad_left_) ? -1 : 0)) && (n <= static_cast<ssize_t>(this->size()))", 
    file=0x8e3590 "/data1/liyang/cppproject/kyli/ClickHouse/src/Common/PODArray.h", line=391, function=<optimized out>) at assert.c:92
#3  0x00007f4b6807ff36 in __GI___assert_fail (assertion=0x877910 "(n >= (static_cast<ssize_t>(pad_left_) ? -1 : 0)) && (n <= static_cast<ssize_t>(this->size()))", 
    file=0x8e3590 "/data1/liyang/cppproject/kyli/ClickHouse/src/Common/PODArray.h", line=391, 
    function=0xc67fb3 "const T &DB::PODArray<char8_t, 4096, Allocator<false, false>, 63, 64>::operator[](ssize_t) const [T = char8_t, initial_bytes = 4096, TAllocator = Allocator<false, false>, pad_right_ = 63, pad_left_ = 64]")
    at assert.c:101
#4  0x000000001ff6f11d in DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>::operator[] (this=0x7f4b67123780, n=11) at /data1/liyang/cppproject/kyli/ClickHouse/src/Common/PODArray.h:391
#5  0x000000001b9ead42 in DB::revertNullByteMap (null_bytemap=0x7f4b67123780, start=10, end=12) at /data1/liyang/cppproject/kyli/ClickHouse/src/Processors/Formats/Impl/CHColumnToArrowColumn.cpp:110
#6  0x000000001b9ea22a in DB::fillArrowArrayWithNumericColumnData<int, arrow::NumericBuilder<arrow::Int32Type> > (write_column=..., null_bytemap=0x7f4b67123780, format_name=..., array_builder=0x7f4b671c5200, start=10, end=12)
    at /data1/liyang/cppproject/kyli/ClickHouse/src/Processors/Formats/Impl/CHColumnToArrowColumn.cpp:127
#7  0x000000001b9e405d in DB::fillArrowArray (column_name=..., column=..., column_type=..., null_bytemap=0x7f4b67123780, array_builder=0x7f4b671c5200, format_name=..., start=10, end=12, output_string_as_string=true, 
    output_fixed_string_as_fixed_byte_array=true, dictionary_values=...) at /data1/liyang/cppproject/kyli/ClickHouse/src/Processors/Formats/Impl/CHColumnToArrowColumn.cpp:795
#8  0x000000001b9e6a55 in DB::fillArrowArrayWithTupleColumnData (column_name=..., column=..., column_type=..., null_bytemap=0x7f4b67123780, array_builder=0x7f4b67207a18, format_name=..., start=10, end=12, 
    output_string_as_string=true, output_fixed_string_as_fixed_byte_array=true, dictionary_values=...) at /data1/liyang/cppproject/kyli/ClickHouse/src/Processors/Formats/Impl/CHColumnToArrowColumn.cpp:264
#9  0x000000001b9e35a7 in DB::fillArrowArray (column_name=..., column=..., column_type=..., null_bytemap=0x7f4b67123780, array_builder=0x7f4b67207a18, format_name=..., start=10, end=12, output_string_as_string=true, 
    output_fixed_string_as_fixed_byte_array=true, dictionary_values=...) at /data1/liyang/cppproject/kyli/ClickHouse/src/Processors/Formats/Impl/CHColumnToArrowColumn.cpp:738
#10 0x000000001b9e7f45 in DB::fillArrowArrayWithArrayColumnData<arrow::MapBuilder> (column_name=..., column=..., column_type=..., null_bytemap=0x7f4b67123780, array_builder=0x7f4b6721ae40, format_name=..., start=0, end=10, 
    output_string_as_string=true, output_fixed_string_as_fixed_byte_array=true, dictionary_values=...) at /data1/liyang/cppproject/kyli/ClickHouse/src/Processors/Formats/Impl/CHColumnToArrowColumn.cpp:237
#11 0x000000001b9e3808 in DB::fillArrowArray (column_name=..., column=..., column_type=..., null_bytemap=0x7f4b67123780, array_builder=0x7f4b6721ae40, format_name=..., start=0, end=10, output_string_as_string=true, 
    output_fixed_string_as_fixed_byte_array=true, dictionary_values=...) at /data1/liyang/cppproject/kyli/ClickHouse/src/Processors/Formats/Impl/CHColumnToArrowColumn.cpp:747
#12 0x000000001b9e2f18 in DB::fillArrowArray (column_name=..., column=..., column_type=..., null_bytemap=0x0, array_builder=0x7f4b6721ae40, format_name=..., start=0, end=10, output_string_as_string=true, 
    output_fixed_string_as_fixed_byte_array=true, dictionary_values=...) at /data1/liyang/cppproject/kyli/ClickHouse/src/Processors/Formats/Impl/CHColumnToArrowColumn.cpp:698
#13 0x000000001b9e0d5b in DB::CHColumnToArrowColumn::chChunkToArrowTable (this=0x7ffe4eb23b58, res=..., chunks=..., columns_num=8)
    at /data1/liyang/cppproject/kyli/ClickHouse/src/Processors/Formats/Impl/CHColumnToArrowColumn.cpp:1055
#14 0x00000000098492f5 in ParquetWrite_ComplexTypes_Test::TestBody (this=0x7f4b672015d0) at /data1/liyang/cppproject/kyli/ClickHouse/utils/extern-local-engine/tests/gtest_parquet_write.cpp:173
#15 0x00000000187ac39b in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0x7f4b672015d0, method=&virtual testing::Test::TestBody(), location=0xe46dbb "the test body")
    at /data1/liyang/cppproject/kyli/ClickHouse/contrib/googletest/googletest/src/gtest.cc:2679
#16 0x000000001878f492 in testing::Test::Run (this=0x7f4b672015d0) at /data1/liyang/cppproject/kyli/ClickHouse/contrib/googletest/googletest/src/gtest.cc:2696
#17 0x000000001878ff22 in testing::TestInfo::Run (this=0x7f4b6720c200) at /data1/liyang/cppproject/kyli/ClickHouse/contrib/googletest/googletest/src/gtest.cc:2845
#18 0x000000001879069f in testing::TestSuite::Run (this=0x7f4b6721d000) at /data1/liyang/cppproject/kyli/ClickHouse/contrib/googletest/googletest/src/gtest.cc:3004
#19 0x000000001879f04b in testing::internal::UnitTestImpl::RunAllTests (this=0x7f4b6723f000) at /data1/liyang/cppproject/kyli/ClickHouse/contrib/googletest/googletest/src/gtest.cc:5889
#20 0x00000000187aea9b in testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x7f4b6723f000, 
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x1879ec40 <testing::internal::UnitTestImpl::RunAllTests()>, 
    location=0x9cf9b9 "auxiliary test code (environments or event listeners)") at /data1/liyang/cppproject/kyli/ClickHouse/contrib/googletest/googletest/src/gtest.cc:2679
#21 0x000000001879ebf0 in testing::UnitTest::Run (this=0x239b4198 <testing::UnitTest::GetInstance()::instance>) at /data1/liyang/cppproject/kyli/ClickHouse/contrib/googletest/googletest/src/gtest.cc:5454
#22 0x000000000982ad71 in RUN_ALL_TESTS () at /data1/liyang/cppproject/kyli/ClickHouse/contrib/googletest/googletest/include/gtest/gtest.h:2310
#23 0x0000000009825e63 in main (argc=1, argv=0x7ffe4eb24a38) at /data1/liyang/cppproject/kyli/ClickHouse/utils/extern-local-engine/tests/gtest_local_engine.cpp:368

```

**Comment by taiyang-li** [comment]
Let's fix it!

**Comment by taiyang-li** [comment]
fixed by https://github.com/ClickHouse/ClickHouse/pull/52112
