### ISSUE TITLE
Error while running DEBUG build of Gluten

### ISSUE THREAD

**Issue by zhztheplayer** [oap-project/gluten#240]
Following error appeared when I was running DEBUG build using newest master branch:

```
# 0  std::shared_ptr<facebook::velox::VeloxException::State const> facebook::velox::VeloxException::State::make<facebook::velox::VeloxException::make(char const*, unsigned long, char const*, std::basic_s
tring_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char
> >, bool, std::basic_string_view<char, std::char_traits<char> >)::{lambda(auto:1&)#1}>(facebook::velox::VeloxException::make(char const*, unsigned long, char const*, std::basic_string_view<char, std::ch
ar_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, bool, std::basic_st
ring_view<char, std::char_traits<char> >)::{lambda(auto:1&)#1})
# 1  facebook::velox::VeloxException::VeloxException(char const*, unsigned long, char const*, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, bool, std::basic_string_view<char, std::char_traits<char> >)
# 2  facebook::velox::VeloxRuntimeError::VeloxRuntimeError(char const*, unsigned long, char const*, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<ch
ar> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, bool, std::basic_string_view<char, std::char_traits<char> >)
# 3  void facebook::velox::detail::veloxCheckFail<facebook::velox::VeloxRuntimeError, facebook::velox::detail::CompileTimeEmptyString>(facebook::velox::detail::VeloxCheckFailArgs const&, facebook::velox:
:detail::CompileTimeEmptyString)
# 4  facebook::velox::core::AggregationNode::stepName(facebook::velox::core::AggregationNode::Step)
# 5  facebook::velox::core::AggregationNode::addDetails(std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >&) const
# 6  facebook::velox::core::PlanNode::toString(std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >&, bool, bool, unsigned long, std::function<void (std::__cxx11::basic_s
tring<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_stringstream<char, std::char
_traits<char>, std::allocator<char> >&)>) const
# 7  facebook::velox::core::PlanNode::toString(bool, bool, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std
::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >&)>) const
# 8  velox::compute::VeloxPlanConverter::getVeloxPlanNode(substrait::Plan const&)
# 9  velox::compute::VeloxPlanConverter::GetResultIterator(std::vector<std::shared_ptr<gluten::RecordBatchResultIterator>, std::allocator<std::shared_ptr<gluten::RecordBatchResultIterator> > >)
# 10 Java_io_glutenproject_vectorized_ExpressionEvaluatorJniWrapper_nativeCreateKernelWithIterator
# 11 0x00007f3361018427

        at io.glutenproject.vectorized.ExpressionEvaluatorJniWrapper.nativeCreateKernelWithIterator(Native Method)
        at io.glutenproject.backendsapi.velox.VeloxIteratorApi.genBatchIterator(VeloxIteratorApi.scala:355)
        at io.glutenproject.vectorized.ExpressionEvaluator.createKernelWithBatchIterator(ExpressionEvaluator.java:100)
        at io.glutenproject.backendsapi.velox.VeloxIteratorApi.genFirstStageIterator(VeloxIteratorApi.scala:221)
        at io.glutenproject.execution.NativeWholeStageColumnarRDD.compute(NativeWholeStageColumnarRDD.scala:133)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

@rui-mo @zhejiangxiaomai Would you please help me identify if the above is a bug, or we can simply remove the DEBUG code

https://github.com/oap-project/gluten/blob/c1ccbd8946042b510255ec1f29e5698ca71352a7/cpp/velox/compute/VeloxPlanConverter.cc#L225-L227

from which the error is spawned?

**Comment by rui-mo** [comment]
Hi Hongze, it seems to be a known issue. The fix is in previous main branch, and should be added to the newest one. @zhejiangxiaomai will work on this.

**Comment by zhztheplayer** [comment]
Got it. Thanks for working on it.

**Comment by zhztheplayer** [comment]
Fixed in newest main
