### ISSUE TITLE
Protocol message had too many levels of nesting

### ISSUE THREAD

**Issue by loukey-lj** [oap-project/gluten#2414]
**Describe the bug**
org.apache.spark.SparkException: Job aborted due to stage failure: Task 5 in stage 2.0 failed 4 times, most recent failure: Lost task 5.3 in stage 2.0 (TID 17) (cnsz26plk8y0 executor 2): ja
va.lang.RuntimeException: Unable to understand proto buffer
      at io.glutenproject.shaded.com.google.protobuf.GeneratedMessageLite$SerializedForm.readResolve(GeneratedMessageLite.java:1463)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1148)
      at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1817)
      at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
      at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
      at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
      at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
      at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
      at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
      at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
      at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
      at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
      at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
      at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
      at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
      at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
      at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:76)
      at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:115)
      at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:466)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
Caused by: io.glutenproject.shaded.com.google.protobuf.InvalidProtocolBufferException: Protocol message had too many levels of nesting.  May be malicious.  Use CodedInputStream.setRecursion
Limit() to increase the depth limit.
      at io.glutenproject.shaded.com.google.protobuf.InvalidProtocolBufferException.recursionLimitExceeded(InvalidProtocolBufferException.java:148)
      at io.glutenproject.shaded.com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:869)
      at io.substrait.proto.Expression$ScalarFunction$Builder.mergeFrom(Expression.java:19668)
      at io.substrait.proto.Expression$ScalarFunction$Builder.mergeFrom(Expression.java:19372)
      at io.glutenproject.shaded.com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:873)
      at io.substrait.proto.Expression$Builder.mergeFrom(Expression.java:61888)
      at io.substrait.proto.Expression$Builder.mergeFrom(Expression.java:61567)
      at io.glutenproject.shaded.com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:873)
      at io.substrait.proto.FunctionArgument$Builder.mergeFrom(FunctionArgument.java:600)
      at io.substrait.proto.FunctionArgument$1.parsePartialFrom(FunctionArgument.java:1050)
      at io.substrait.proto.FunctionArgument$1.parsePartialFrom(FunctionArgument.java:1042)
      at io.glutenproject.shaded.com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:889)
      at io.substrait.proto.Expression$ScalarFunction$Builder.mergeFrom(Expression.java:19676)
      at io.substrait.proto.Expression$ScalarFunction$Builder.mergeFrom(Expression.java:19372)
      at io.glutenproject.shaded.com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:873)

**Comment by loukey-lj** [comment]
@PHILO-HE  thank u, www.sf-tech.com.cn
