### ISSUE TITLE
readInt128 error

### ISSUE THREAD

**Issue by loukey-lj** [oap-project/gluten#2416]
**Describe the bug**
2023-07-16 13:51:09,341 [task-result-getter-0] WARN  - TaskSetManager: Lost task 0.2 in stage 6.0 (TID 27) (cnsz26plghnj executor 1): java.lang.RuntimeException: Exception: VeloxRuntimeErro
r
Error Source: RUNTIME
Error Code: NOT_IMPLEMENTED
Retriable: False
Context: Split [file hdfs://xxxx/dm_tdym_iassist_task_record_dtl_di_001/part-00003-95801391-91b8-470c-8dde-442a62313d60-c000.snappy.parquet 0 - 10171548] Task
Gluten stage-6 task-27
Top-Level Context: Same as context.
Function: readInt128
File: ../.././velox/dwio/common/IntDecoder.h
Line: 553
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorENS1_22CompileTimeEmptyStringEEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZN8facebook5velox4dwio6common10IntDecoderILb1EE10readInt128Ev
# 4  _ZN8facebook5velox7parquet10PageReader15readWithVisitorINS0_4dwio6common13ColumnVisitorInNS0_6common10AlwaysTrueENS5_15ExtractToReaderINS5_28SelectiveIntegerColumnReaderEEELb1EEEEEvRT_
# 5  _ZN8facebook5velox4dwio6common28SelectiveIntegerColumnReader10readHelperINS0_7parquet19IntegerColumnReaderENS0_6common10AlwaysTrueELb1ENS2_15ExtractToReaderIS3_EEEEvPNS7_6FilterEN5foll
y5RangeIPKiEET2_
# 6  _ZN8facebook5velox4dwio6common28SelectiveIntegerColumnReader10readCommonINS0_7parquet19IntegerColumnReaderEEEvN5folly5RangeIPKiEE
# 7  _ZN8facebook5velox4dwio6common31SelectiveStructColumnReaderBase4readEiN5folly5RangeIPKiEEPKm
# 8  _ZN8facebook5velox4dwio6common31SelectiveStructColumnReaderBase4nextEmRSt10shared_ptrINS0_10BaseVectorEEPKm
# 9  _ZN8facebook5velox7parquet16ParquetRowReader4nextEmRSt10shared_ptrINS0_10BaseVectorEE
# 10 _ZN8facebook5velox9connector4hive14HiveDataSource4nextEmRN5folly10SemiFutureINS4_4UnitEEE
# 11 _ZN8facebook5velox4exec9TableScan9getOutputEv
# 12 _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE
# 13 _ZN8facebook5velox4exec6Driver4nextERSt10shared_ptrINS1_13BlockingStateEE
# 14 _ZN8facebook5velox4exec4Task4nextEPN5folly10SemiFutureINS3_4UnitEEE
# 15 _ZN6gluten24WholeStageResultIterator4nextEv
# 16 Java_io_glutenproject_vectorized_ColumnarBatchOutIterator_nativeHasNext
# 17 0x00007fd72d017a14
      at io.glutenproject.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
      at io.glutenproject.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:47)
      at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37)
      at io.glutenproject.backendsapi.velox.IteratorHandler$$anon$2.hasNext(IteratorHandler.scala:240)
      at io.glutenproject.vectorized.CloseableColumnBatchIterator.hasNext(CloseableColumnBatchIterator.scala:41)
      at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
      at org.apache.spark.sql.execution.ColumnarToRowRDD$$anon$1.hasNext(VeloxColumnarToRowExec.scala:149)
      at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
      at scala.collection.TraversableOnce$FlattenOps$$anon$2.hasNext(TraversableOnce.scala:521)
      at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
      at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
      at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)
      at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
      at org.apache.spark.sql.execution.UnsafeExternalRowSorter.sort(UnsafeExternalRowSorter.java:225)

**Comment by loukey-lj** [comment]
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Operator::getOutput failed for [operator: ValueStream, plan node ID: 0]: Error during calling Java code from native code: io.glutenproject.exception.GlutenException: java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: NOT_IMPLEMENTED
Retriable: False
Context: Split [Hive: hdfs://xxx/hive/warehouse/tech/DM/dm_pass_tos/dm_tos_tail_good_car_pooling_mid_di/20240217/dm_tos_tail_good_car_pooling_mid_di__4b19e06d_b246_4a3e_b6f4_2c80cd28adf4 0 - 46132197] Task Gluten_Stage_4_TID_52
Top-Level Context: Same as context.
Function: readInt
File: /app/dps-ssc-core-gluten/ep/build-velox/build/velox_ep/./velox/dwio/common/IntDecoder.h
Line: 443
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorENS1_22CompileTimeEmptyStringEEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZN8facebook5velox4dwio6common10IntDecoderILb1EE7readIntInEET_v
# 4  _ZN8facebook5velox7parquet10PageReader15readWithVisitorINS0_4dwio6common13ColumnVisitorInNS0_6common10AlwaysTrueENS5_15ExtractToReaderINS5_28SelectiveIntegerColumnReaderEEELb0EEEEEvRT_
# 5  _ZN8facebook5velox4dwio6common28SelectiveIntegerColumnReader13processFilterINS0_7parquet19IntegerColumnReaderELb0ENS2_15ExtractToReaderIS3_EEEEvPNS0_6common6FilterET1_N5folly5RangeIPKiEE
# 6  _ZN8facebook5velox7parquet21TimestampColumnReader4readEiN5folly5RangeIPKiEEPKm
# 7  _ZN8facebook5velox4dwio6common31SelectiveStructColumnReaderBase4readEiN5folly5RangeIPKiEEPKm
# 8  _ZN8facebook5velox4dwio6common31SelectiveStructColumnReaderBase4nextEmRSt10shared_ptrINS0_10BaseVectorEEPKNS2_8MutationE
# 9  _ZN8facebook5velox7parquet16ParquetRowReader4nextEmRSt10shared_ptrINS0_10BaseVectorEEPKNS0_4dwio6common8MutationE
# 10 _ZN8facebook5velox9connector4hive14HiveDataSource4nextEmRN5folly10SemiFutureINS4_4UnitEEE
# 11 _ZN8facebook5velox4exec9TableScan9getOutputEv
# 12 _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE
# 13 _ZN8facebook5velox4exec6Driver4nextERSt10shared_ptrINS1_13BlockingStateEE
# 14 _ZN8facebook5velox4exec4Task4nextEPN5folly10SemiFutureINS3_4UnitEEE
# 15 _ZN6gluten24WholeStageResultIterator4nextEv
# 16 Java_io_glutenproject_vectorized_ColumnarBatchOutIterator_nativeHasNext
# 17 0x00007f8199017a14

	at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:39)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:45)
	at io.glutenproject.utils.InvocationFlowProtection.hasNext(Iterators.scala:135)
	at io.glutenproject.utils.IteratorCompleter.hasNext(Iterators.scala:69)
	at io.glutenproject.utils.PayloadCloser.hasNext(Iterators.scala:35)
	at io.glutenproject.utils.PipelineTimeAccumulator.hasNext(Iterators.scala:98)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at io.glutenproject.execution.VeloxColumnarToRowExec$$anon$1.hasNext(VeloxColumnarToRowExec.scala:107)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.TraversableOnce$FlattenOps$$anon$2.hasNext(TraversableOnce.scala:521)
	at io.glutenproject.utils.InvocationFlowProtection.hasNext(Iterators.scala:135)
	at io.glutenproject.utils.IteratorCompleter.hasNext(Iterators.scala:69)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(generated.java:28)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)
	at io.glutenproject.execution.RowToVeloxColumnarExec$$anon$1.nativeConvert(RowToVeloxColumnarExec.scala:150)
	at io.glutenproject.execution.RowToVeloxColumnarExec$$anon$1.next(RowToVeloxColumnarExec.scala:199)
	at io.glutenproject.execution.RowToVeloxColumnarExec$$anon$1.next(RowToVeloxColumnarExec.scala:108)
	at io.glutenproject.utils.IteratorCompleter.next(Iterators.scala:77)
	at io.glutenproject.utils.PayloadCloser.next(Iterators.scala:39)
	at scala.collection.convert.Wrappers$IteratorWrapper.next(Wrappers.scala:33)
	at io.glutenproject.vectorized.GeneralInIterator.nextColumnarBatch(GeneralInIterator.java:38)
	at io.glutenproject.vectorized.ColumnarBatchInIterator.next(ColumnarBatchInIterator.java:33)
	at io.glutenproject.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
	at io.glutenproject.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:65)
	at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:45)
	at io.glutenproject.utils.IteratorCompleter.hasNext(Iterators.scala:69)
	at io.glutenproject.utils.PayloadCloser.hasNext(Iterators.scala:35)
	at io.glutenproject.utils.PipelineTimeAccumulator.hasNext(Iterators.scala:98)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.writer.gluten.uniffle.writer.NativeShuffleWriter.writeImpl(NativeShuffleWriter.scala:91)
	at org.apache.spark.writer.gluten.uniffle.writer.NativeShuffleWriter.write(NativeShuffleWriter.scala:73)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
