### ISSUE TITLE
[VL] values_->capacity() >= byteSize

### ISSUE THREAD

**Issue by loukey-lj** [oap-project/gluten#2421]
**Describe the bug**
org.apache.spark.SparkException: Job aborted due to stage failure: Task 3 in stage 66.0 failed 4 times, most recent failure: Lost task 3.3 in stage 66.0 (TID 730) (executor 2):
 java.lang.RuntimeException: Error during calling Java code from native code: java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: (160 vs. 503)
Retriable: False
Expression: values_->capacity() >= byteSize
Context: isnotnull(try(cast((trim(
        at io.glutenproject.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
        at io.glutenproject.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:47)
        at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37)
        at io.glutenproject.backendsapi.velox.IteratorHandler$$anon$2.hasNext(IteratorHandler.scala:240)
        at io.glutenproject.vectorized.CloseableColumnBatchIterator.hasNext(CloseableColumnBatchIterator.scala:41)
        at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
        at org.apache.spark.sql.execution.ColumnarToRowRDD$$anon$1.hasNext(VeloxColumnarToRowExec.scala:149)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
        at scala.collection.TraversableOnce$FlattenOps$$anon$2.hasNext(TraversableOnce.scala:521)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)
        at io.glutenproject.execution.RowToArrowColumnarExec$$anon$1.nativeConvert(RowToArrowColumnarExec.scala:368)
        at io.glutenproject.execution.RowToArrowColumnarExec$$anon$1.next(RowToArrowColumnarExec.scala:421)
        at io.glutenproject.execution.RowToArrowColumnarExec$$anon$1.next(RowToArrowColumnarExec.scala:331)
        at io.glutenproject.vectorized.CloseableColumnBatchIterator.next(CloseableColumnBatchIterator.scala:56)
        at io.glutenproject.vectorized.CloseableColumnBatchIterator.next(CloseableColumnBatchIterator.scala:32)
        at scala.collection.convert.Wrappers$IteratorWrapper.next(Wrappers.scala:33)
        at io.glutenproject.vectorized.GeneralInIterator.hasNext(GeneralInIterator.java:34)
        at io.glutenproject.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
        at io.glutenproject.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:47)
        at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37)
        at io.glutenproject.backendsapi.velox.IteratorHandler$$anon$3.hasNext(IteratorHandler.scala:298)
        at io.glutenproject.vectorized.CloseableColumnBatchIterator.hasNext(CloseableColumnBatchIterator.scala:41)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
        at org.apache.spark.shuffle.utils.NativeShuffleWriter.writeImpl(NativeShuffleWriter.scala:89)
        at org.apache.spark.shuffle.utils.NativeShuffleWriter.write(NativeShuffleWriter.scala:71)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
sql: 用到 cast 的地方
    where inc_day = regexp_replace(cast(date_add('2023-07-15', -1) as string), '-', '')
      and regexp_replace(substr(get_bill_date, 1, 7), '-', '') >= substr(regexp_replace(cast(date_add('2023-07-15', -240) as string), '-', ''), 1, 6)

**Comment by kecookier** [comment]
I also encountered this problem.

**Comment by kecookier** [comment]
In my case, the task involves reading data from an ORC file with a remaining filter expression `and(isnotnull(try_cast trim("  ","X") as BIGINT),greaterthan(try_cast trim("  ","X") as BIGINT,0))`. In this expression, `try_cast trim("  ","X")` is a common subexpression (CSE), and the column X has 2484 different `varchar` values. The common batch size is 4096, but the last batch size of the input ORC file is 1.

Now, when evaluating the last batch, the input rows will be peeled to a new `SelectivityVector (size: 2484, begin: 1004, end: 1005)`. When checking the CSE cache, all requested rows are cached, and the `sharedSubexprValues (size: 1005)` are returned as the result. These values are then passed to the parent expression: `IsNullFunction`. In `IsNull::apply(),` when constructing a FlatVector with `rows.size(2484)` and `arg.size(1005)`, an exception is thrown.

```cpp
template <typename TEval>
void Expr::evaluateSharedSubexpr(
    const SelectivityVector& rows,
    EvalCtx& context,
    VectorPtr& result,
    TEval eval) {

// ...
  if (rows.isSubset(*sharedSubexprRows)) {
    // We have results for all requested rows. No need to compute anything.
    context.moveOrCopyResult(sharedSubexprValues, rows, result);
    return;
  }
// ...
}

  // Returns true if 'this' is equal to or a subset of 'other'.
  bool isSubset(const SelectivityVector& other) const {
    if (begin_ >= other.begin_ && end_ <= other.end_) {
      return bits::isSubset(bits_.data(), other.bits_.data(), begin_, end_);
    }
    return false;
  }
```

This [PR](https://github.com/facebookincubator/velox/pull/4456) will fix this bug.

**Comment by zhouyuan** [comment]
closing as it's fixed in recent rebase work
