### ISSUE TITLE
[CH] Add pre-projection for hash shuffle with expressions failed

### ISSUE THREAD

**Issue by lgbo-ustc** [oap-project/gluten#2430]
**Describe the bug**

Following query failed
```SQL
Comments
@[lgbo-ustc](https://github.com/lgbo-ustc)
lgbo-ustc commented [5 minutes ago](https://github.com/Kyligence/ClickHouse/issues/451#issue-1815240685)
(you don't have to strictly follow this form)

Describe the unexpected behaviour

Following query failed

select count(1) from ( select '2023-03-07' as sday
,abflag
,coalesce(country,'all') as country
,coalesce(usertype,'all') as usertype
,count(a.uid) as dau
,cast(null as bigint) as retention_1d_uv
,cast(null as bigint) as retention_2d_uv
,cast(null as bigint) as retention_3d_uv
,cast(null as bigint) as retention_4d_uv
,cast(null as bigint) as retention_5d_uv
,cast(null as bigint) as retention_6d_uv
,cast(null as bigint) as retention_7d_uv

,count(b.uid)/count(a.uid) as retention_1d_rate
,cast (null as float) as retention_2d_rate
,count(c.uid)/count(a.uid) as retention_3d_rate
,cast (null as float) as retention_4d_rate
,cast (null as float) as retention_5d_rate
,cast (null as float) as retention_6d_rate
,count(d.uid)/count(a.uid) as retention_7d_rate

from
    (select a.day
    ,a.abflag
    ,b.country
    ,if(c.uid is not null,'new','old') as usertype
    ,a.uid
    from
        (select day,abflag,app_uid as uid
        from swh_client_abflag
        where day = '2023-03-07'
        group by day,abflag,app_uid
        ) a
    join
        (select day,app_uid as uid,country
        from  com_dim_snapshot_user
        where day = '2023-03-07'
        and app_use_time_order_desc_rank=1
        ) b
    on a.day=b.day and a.uid=b.uid
    left join
        (select day,uid
        from account_registrations
        where day = '2023-03-07'
        and num_deleted=0
        group by day,uid
        ) c
    on a.day=c.day and a.uid=c.uid
    ) a
left join
    (
    select day,app_uid as uid
    from com_dim_snapshot_user
    where day = date_add('2023-03-07',1)
    and app_use_time_order_desc_rank=1
    ) b
on a.uid=b.uid
left join
    (
    select day,app_uid as uid
    from com_dim_snapshot_user
    where day = date_add('2023-03-07',3)
    and app_use_time_order_desc_rank=1
    ) c
on a.uid=c.uid
left join
    (-- 七留
    select day,app_uid as uid
    from com_dim_snapshot_user
    where day = date_add('2023-03-07',7)
    and app_use_time_order_desc_rank=1
    ) d
on a.uid=d.uid
group by abflag,country,usertype
grouping sets(
    (abflag),
    (abflag,country),
    (abflag,usertype),
    (abflag,country,usertype)
) )
```

got exception
```

java.lang.IllegalStateException: Couldn't find uid#0 in [day#121,abflag#113,imo_uid#115]
	at org.apache.spark.sql.catalyst.expressions.BindReferences$$anonfun$bindReference$1.applyOrElse(BoundAttribute.scala:80)
	at org.apache.spark.sql.catalyst.expressions.BindReferences$$anonfun$bindReference$1.applyOrElse(BoundAttribute.scala:73)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:481)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:481)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:457)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transform(TreeNode.scala:425)
	at org.apache.spark.sql.catalyst.expressions.BindReferences$.bindReference(BoundAttribute.scala:73)
	at io.glutenproject.extension.TransformPreOverrides.$anonfun$addProjectionForShuffleExchange$1(ColumnarOverrides.scala:182)
	at io.glutenproject.extension.TransformPreOverrides.$anonfun$addProjectionForShuffleExchange$1$adapted(ColumnarOverrides.scala:174)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at io.glutenproject.extension.TransformPreOverrides.selectExpressions$1(ColumnarOverrides.scala:174)
	at io.glutenproject.extension.TransformPreOverrides.addProjectionForShuffleExchange(ColumnarOverrides.scala:194)
	at io.glutenproject.extension.TransformPreOverrides.replaceWithTransformerPlan(ColumnarOverrides.scala:359)
	at io.glutenproject.extension.TransformPreOverrides.replaceWithTransformerPlan(ColumnarOverrides.scala:382)
	at io.glutenproject.extension.TransformPreOverrides.replaceWithTransformerPlan(ColumnarOverrides.scala:275)
	at io.glutenproject.extension.TransformPreOverrides.replaceWithTransformerPlan(ColumnarOverrides.scala:382)
	at io.glutenproject.extension.TransformPreOverrides.replaceWithTransformerPlan(ColumnarOverrides.scala:275)
	at io.glutenproject.extension.TransformPreOverrides.replaceWithTransformerPlan(ColumnarOverrides.scala:340)
	at io.glutenproject.extension.TransformPreOverrides.replaceWithTransformerPlan(ColumnarOverrides.scala:382)
	at io.glutenproject.extension.TransformPreOverrides.replaceWithTransformerPlan(ColumnarOverrides.scala:275)
	at io.glutenproject.extension.TransformPreOverrides.replaceWithTransformerPlan(ColumnarOverrides.scala:382)
	at io.glutenproject.extension.TransformPreOverrides.replaceWithTransformerPlan(ColumnarOverrides.scala:275)
	at io.glutenproject.extension.TransformPreOverrides.replaceWithTransformerPlan(ColumnarOverrides.scala:382)
	at io.glutenproject.extension.TransformPreOverrides.replaceWithTransformerPlan(ColumnarOverrides.scala:275)
	at io.glutenproject.extension.TransformPreOverrides.replaceWithTransformerPlan(ColumnarOverrides.scala:327)
	at io.glutenproject.extension.TransformPreOverrides.genHashAggregateExec(ColumnarOverrides.scala:87)
	at io.glutenproject.extension.TransformPreOverrides.replaceWithTransformerPlan(ColumnarOverrides.scala:281)
	at io.glutenproject.extension.TransformPreOverrides.replaceWithTransformerPlan(ColumnarOverrides.scala:340)
	at io.glutenproject.extension.TransformPreOverrides.genHashAggregateExec(ColumnarOverrides.scala:87)
	at io.glutenproject.extension.TransformPreOverrides.replaceWithTransformerPlan(ColumnarOverrides.scala:281)
	at io.glutenproject.extension.TransformPreOverrides.genHashAggregateExec(ColumnarOverrides.scala:87)
	at io.glutenproject.extension.TransformPreOverrides.replaceWithTransformerPlan(ColumnarOverrides.scala:281)
	at io.glutenproject.extension.TransformPreOverrides.replaceWithTransformerPlan(ColumnarOverrides.scala:340)
	at io.glutenproject.extension.TransformPreOverrides.genHashAggregateExec(ColumnarOverrides.scala:87)
	at io.glutenproject.extension.TransformPreOverrides.replaceWithTransformerPlan(ColumnarOverrides.scala:281)
	at io.glutenproject.extension.TransformPreOverrides.apply(ColumnarOverrides.scala:548)
	at io.glutenproject.extension.TransformPreOverrides.apply(ColumnarOverrides.scala:48)
	at io.glutenproject.extension.ColumnarOverrideRules.$anonfun$preColumnarTransitions$5(ColumnarOverrides.scala:720)
	at io.glutenproject.extension.ColumnarOverrideRules.$anonfun$preColumnarTransitions$5$adapted(ColumnarOverrides.scala:719)
	at scala.collection.immutable.List.foreach(List.scala:431)
```

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by lgbo-ustc** [comment]
@liuneng1994

**Comment by shuai-xu** [comment]
select count(1) from ( select all1.*
    ,today_pay_uv,today_pay_diamond
    ,next_pay_uv,next_pay_diamond,seven_pay_uv,seven_pay_diamond
from
    (select  op_area ,country ,ticket_type ,get_pv ,get_uv ,use_pv ,
        use_uv ,bet_diamond ,win_diamond
    from xxxxxx where day = '2023-03-07'
    ) all1
join
    (select
        nvl(op_area,'all') as op_area
        ,nvl(country,'all') as country
        ,nvl(ticket_type,'all') as ticket_type
        ,count(distinct case when game_diamond1>0 then uid end) today_pay_uv
        ,sum(case when game_diamond1>0 then game_diamond1 else 0 end) as today_pay_diamond
        ,count(distinct case when game_diamond2>0 then uid end) next_pay_uv
        ,sum(case when game_diamond2>0 then game_diamond2 else 0 end) as next_pay_diamond
        ,count(distinct case when game_diamond3>0 then uid end) seven_pay_uv
        ,sum(case when game_diamond3>0 then game_diamond3 else 0 end) as seven_pay_diamond
    from
        (select base.*
            ,nvl(b.countrycode,'other') as country
            ,nvl(c.op_area,'other') as op_area
            ,nvl(game_diamond1,0) as game_diamond1
            ,nvl(game_diamond2,0) as game_diamond2
            ,nvl(game_diamond3,0) as game_diamond3
        from 
            (select uid,case when  ticket_id !=  1011  then 'rengong' else 'zidong' end as ticket_type
              from xxxxxxx
             where is_gray = 0 and from_unixtime(create_time,'yyyy-mm-dd') = '2023-03-07' 
             group by uid, case when  ticket_id !=  1011  then 'rengong' else 'zidong' end
            ) base  
        left join xxxxxxx b
            on base.uid = b.uid
        left join xxxxxxx c
            on b.countrycode = c.country
        left join 
            (select  uid
                    ,sum(case when bus_type in (33) and sub_bus_type != 40646  then -change_count else 0 end) as game_diamond1
            from xxxxxx
            where day between '2023-03-07' and '2023-03-07' and type = 2  and appid = 48  and change_count < 0
            group by uid
            ) t1 
        on base.uid = t1.uid
        left join 
            (select  uid
                    ,sum(case when bus_type in (33) and sub_bus_type != 40646  then -change_count else 0 end) as game_diamond2
            from xxxxxx
            where day between date_add('2023-03-07',1) and date_add('2023-03-07',1) and type = 2  and appid = 48  and change_count < 0
            group by uid
            ) t2 
        on base.uid = t2.uid
        left join 
            (select  uid
                    ,sum(case when bus_type in (33) and sub_bus_type != 40646  then -change_count else 0 end) as game_diamond3
            from xxxxxx
            where day between '2023-03-07' and date_add('2023-03-07',6) and type = 2  and appid = 48  and change_count < 0
            group by uid
            ) t3 
        on base.uid = t3.uid
        ) tb_base
    group by op_area,country,ticket_type with cube
    ) all2
on all1.op_area = all2.op_area and all1.country = all2.country and all1.ticket_type = all2.ticket_type )
