### ISSUE TITLE
[CH] gluten submit additional jobs to get input paths

### ISSUE THREAD

**Issue by shuai-xu** [oap-project/gluten#2498]
**Describe the bug**
Such as shown in bellow:
<img width="1439" alt="image" src="https://github.com/oap-project/gluten/assets/20960838/5b7fdb19-fd6f-4989-8e6f-6d1dabf23c6f">
<img width="1434" alt="image" src="https://github.com/oap-project/gluten/assets/20960838/a750fa7c-ae4f-46dd-8cc7-02f44b6f349f">

gluten submit some jobs to list directory and get the input files. But spark with same config didn't. This cause a preformance degradation。
The jobs are submitted by：
<img width="1189" alt="image" src="https://github.com/oap-project/gluten/assets/20960838/2fbaa264-96d7-4b53-9c61-8d64d36764d4">

**Comment by shuai-xu** [comment]
These job are submitted by gluten When doing ColumnarOverride. 
<img width="916" alt="image" src="https://github.com/oap-project/gluten/assets/20960838/00f9d74d-a07c-48a2-83b9-08dc9e4cffea">

**Comment by taiyang-li** [comment]
```
23/0//26 60:34:05NFOpaatjava.Lang.Exception: Traceat org.apache.spark.SparkContext.runJob(SparkContext.scala:2234)at org.apache.spark.SparkContext.runJob(SparkContext.scala:2259)at org.apache.spark.SparkContext.runJob(SparkContext.scala:2278)at org.apache.spark.SparkContext.runJob(SparkContext.scala:2303)org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1021)org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)org.apache.sparkRDDOperationScopes withScope(RDDOperationScope.scala:112org.apache.spark.rdd.RDD.withScope(RDD.scala:406)rdd.RDD.collect(RDD..scala:1020)org.apache.spark.org.apache.spark utilHadoopFSUtils$.parallellistlegfFilesInternal(HadoopFSUtis.scala:139)parallelListLeafFiles(HadoopFSUtils.scala:69)org.apache.spark.util.HadoopFSUtils$.bulkListLeafFiles(InMemoryFileIndex.scala:158)orq.apache.spark.sqlexecutionootosorces.apache.spark.salnorvFileIndex.scala:131)oradotosonMenFileTndexscala:94)raonacbeShOYKsaorvFileIndex.scala:66)org.apache.spark.sglexecution .datasources .InMemorvs(CatalogFileIndex.scala:90).datasol.apacheCHiveTableScanExecTransformerscala:128)HsvoaeSCAOrGanacheHiveTableScanExecTransformer.scala:53).apachexecTransformer.scala:53)raabache.apacheTransformer.scala:100)er.scala:263)arkPlanExecApi.scala:76)$(SparkPlanExecApi.scala:75)TableScanExecTransformer(CHSparkPlanExecApi.scala:58)SstonnNrPlan(ColumnarOverrides.scala:473)rOverridesscala:155rPlan(ColumnarOverrides.scala:276)lanCColumnarOverridesscala:338IteNNYOOverridesscala:552io.glutenproject.extensiorio.alutenpro/errides.scala:49)io.alutenprojectTransitionst5CColumnarOverrides scala:731)ayteNS10rtions$5$adapted(ColumnarOverrides.scala:730)lo.alutenprojectscalocolectiorio.glutenprojectun$preColumnarTransitions$2(ColumnarOverrides,scala:730oalutennrojecttio.glutenproject.extension.sitions$8.apply(ColumnarOverrides.scala:707)io.glutenproject.extension.Colio.alutenproiect.extension .Columransitions$8.applv(ColumnarOverrides.scala:707at org.apache.spark.sal.execution.ApplvColumnarRulesAndInsertTransitions$anonfun$apply$1(Columnar.scala:553)at org.apache.spark.sgl.execution.ApplyColumnarRullesAndInsertTransitions.$anonfun
```

**Comment by taiyang-li** [comment]
I'll fix it .

**Comment by taiyang-li** [comment]
@baibaichen will fix it later.
