### ISSUE TITLE
[VL] DictionaryVector error

### ISSUE THREAD

**Issue by loukey-lj** [oap-project/gluten#2525]
```
E20230729 13:00:28.318135  9355 Exceptions.h:68] Line: ../.././velox/vector/DictionaryVector-inl.h:108, Function:DictionaryVector, Expression: dictionaryIndices->size() >= length * sizeof(vector_size_t) (16384 vs. 16388) Malformed dictionary, index array is shorter than DictionaryVector, Source: RUNTIME, ErrorCode: INVALID_STATE
23/07/29 13:00:28 ERROR NativeShuffleWriter: ============== writeImpl write error: java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: (16384 vs. 16388) Malformed dictionary, index array is shorter than DictionaryVector
Retriable: False
Expression: dictionaryIndices->size() >= length * sizeof(vector_size_t)
Function: DictionaryVector
File: ../.././velox/vector/DictionaryVector-inl.h
Line: 108
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKSsEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZN8facebook5velox16DictionaryVectorINS0_10StringViewEEC1EPNS0_6memory10MemoryPoolEN5boost13intrusive_ptrINS0_6BufferEEEmSt10shared_ptrINS0_10BaseVectorEESA_RKNS0_17SimpleVectorStatsIS2_EESt8optionalIiESJ_SI_IbESJ_SJ_
# 4  _ZN8facebook5veloxL13addDictionaryILNS0_8TypeKindE7EEESt10shared_ptrINS0_10BaseVectorEEN5boost13intrusive_ptrINS0_6BufferEEES9_mS5_
# 5  _ZN8facebook5velox10BaseVector16wrapInDictionaryEN5boost13intrusive_ptrINS0_6BufferEEES5_iSt10shared_ptrIS1_E
# 6  _ZN8facebook5velox4exec9wrapChildEiN5boost13intrusive_ptrINS0_6BufferEEERKSt10shared_ptrINS0_10BaseVectorEES5_
# 7  _ZN8facebook5velox4exec9HashProbe10fillOutputEi
# 8  _ZN8facebook5velox4exec9HashProbe9getOutputEv
# 9  _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE
# 10 _ZN8facebook5velox4exec6Driver4nextERSt10shared_ptrINS1_13BlockingStateEE
# 11 _ZN8facebook5velox4exec4Task4nextEPN5folly10SemiFutureINS3_4UnitEEE
# 12 _ZN6gluten24WholeStageResultIterator4nextEv
# 13 Java_io_glutenproject_vectorized_ColumnarBatchOutIterator_nativeHasNext
# 14 0x00007f94557c38a8
,org.apache.spark.writer.gluten.uniffle.writer.NativeShuffleWriter@1d994f10
java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: (16384 vs. 16388) Malformed dictionary, index array is shorter than DictionaryVector
Retriable: False
Expression: dictionaryIndices->size() >= length * sizeof(vector_size_t)
Function: DictionaryVector
File: ../.././velox/vector/DictionaryVector-inl.h
Line: 108
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKSsEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZN8facebook5velox16DictionaryVectorINS0_10StringViewEEC1EPNS0_6memory10MemoryPoolEN5boost13intrusive_ptrINS0_6BufferEEEmSt10shared_ptrINS0_10BaseVectorEESA_RKNS0_17SimpleVectorStatsIS2_EESt8optionalIiESJ_SI_IbESJ_SJ_
# 4  _ZN8facebook5veloxL13addDictionaryILNS0_8TypeKindE7EEESt10shared_ptrINS0_10BaseVectorEEN5boost13intrusive_ptrINS0_6BufferEEES9_mS5_
# 5  _ZN8facebook5velox10BaseVector16wrapInDictionaryEN5boost13intrusive_ptrINS0_6BufferEEES5_iSt10shared_ptrIS1_E
# 6  _ZN8facebook5velox4exec9wrapChildEiN5boost13intrusive_ptrINS0_6BufferEEERKSt10shared_ptrINS0_10BaseVectorEES5_
# 7  _ZN8facebook5velox4exec9HashProbe10fillOutputEi
# 8  _ZN8facebook5velox4exec9HashProbe9getOutputEv
# 9  _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE
# 10 _ZN8facebook5velox4exec6Driver4nextERSt10shared_ptrINS1_13BlockingStateEE
# 11 _ZN8facebook5velox4exec4Task4nextEPN5folly10SemiFutureINS3_4UnitEEE
# 12 _ZN6gluten24WholeStageResultIterator4nextEv
# 13 Java_io_glutenproject_vectorized_ColumnarBatchOutIterator_nativeHasNext
# 14 0x00007f94557c38a8

	at io.glutenproject.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
	at io.glutenproject.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:47)
	at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37)
	at io.glutenproject.backendsapi.velox.IteratorHandler$$anon$3.hasNext(IteratorHandler.scala:298)
	at io.glutenproject.vectorized.CloseableColumnBatchIterator.hasNext(CloseableColumnBatchIterator.scala:41)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.writer.gluten.uniffle.writer.NativeShuffleWriter.writeImpl(NativeShuffleWriter.scala:98)
	at org.apache.spark.writer.gluten.uniffle.writer.NativeShuffleWriter.write(NativeShuffleWriter.scala:80)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
23/07/29 13:00:28 ERROR TaskResources: Task 9731 failed by error: 
java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: (16384 vs. 16388) Malformed dictionary, index array is shorter than DictionaryVector
Retriable: False
Expression: dictionaryIndices->size() >= length * sizeof(vector_size_t)
Function: DictionaryVector
File: ../.././velox/vector/DictionaryVector-inl.h
Line: 108
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKSsEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZN8facebook5velox16DictionaryVectorINS0_10StringViewEEC1EPNS0_6memory10MemoryPoolEN5boost13intrusive_ptrINS0_6BufferEEEmSt10shared_ptrINS0_10BaseVectorEESA_RKNS0_17SimpleVectorStatsIS2_EESt8optionalIiESJ_SI_IbESJ_SJ_
# 4  _ZN8facebook5veloxL13addDictionaryILNS0_8TypeKindE7EEESt10shared_ptrINS0_10BaseVectorEEN5boost13intrusive_ptrINS0_6BufferEEES9_mS5_
# 5  _ZN8facebook5velox10BaseVector16wrapInDictionaryEN5boost13intrusive_ptrINS0_6BufferEEES5_iSt10shared_ptrIS1_E
# 6  _ZN8facebook5velox4exec9wrapChildEiN5boost13intrusive_ptrINS0_6BufferEEERKSt10shared_ptrINS0_10BaseVectorEES5_
# 7  _ZN8facebook5velox4exec9HashProbe10fillOutputEi
# 8  _ZN8facebook5velox4exec9HashProbe9getOutputEv
# 9  _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE
# 10 _ZN8facebook5velox4exec6Driver4nextERSt10shared_ptrINS1_13BlockingStateEE
# 11 _ZN8facebook5velox4exec4Task4nextEPN5folly10SemiFutureINS3_4UnitEEE
# 12 _ZN6gluten24WholeStageResultIterator4nextEv
# 13 Java_io_glutenproject_vectorized_ColumnarBatchOutIterator_nativeHasNext
# 14 0x00007f94557c38a8

	at io.glutenproject.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
	at io.glutenproject.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:47)
	at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37)
	at io.glutenproject.backendsapi.velox.IteratorHandler$$anon$3.hasNext(IteratorHandler.scala:298)
	at io.glutenproject.vectorized.CloseableColumnBatchIterator.hasNext(CloseableColumnBatchIterator.scala:41)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.writer.gluten.uniffle.writer.NativeShuffleWriter.writeImpl(NativeShuffleWriter.scala:98)
	at org.apache.spark.writer.gluten.uniffle.writer.NativeShuffleWriter.write(NativeShuffleWriter.scala:80)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
23/07/29 13:00:28 WARN MemoryAllocatorManager: Detected leaked native allocator, size: 157366272, process accumulated leaked size: 157366272...
23/07/29 13:00:28 ERROR Executor: Exception in task 1.0 in stage 18.0 (TID 9731)
java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: (16384 vs. 16388) Malformed dictionary, index array is shorter than DictionaryVector
Retriable: False
Expression: dictionaryIndices->size() >= length * sizeof(vector_size_t)
Function: DictionaryVector
File: ../.././velox/vector/DictionaryVector-inl.h
Line: 108
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKSsEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZN8facebook5velox16DictionaryVectorINS0_10StringViewEEC1EPNS0_6memory10MemoryPoolEN5boost13intrusive_ptrINS0_6BufferEEEmSt10shared_ptrINS0_10BaseVectorEESA_RKNS0_17SimpleVectorStatsIS2_EESt8optionalIiESJ_SI_IbESJ_SJ_
# 4  _ZN8facebook5veloxL13addDictionaryILNS0_8TypeKindE7EEESt10shared_ptrINS0_10BaseVectorEEN5boost13intrusive_ptrINS0_6BufferEEES9_mS5_
# 5  _ZN8facebook5velox10BaseVector16wrapInDictionaryEN5boost13intrusive_ptrINS0_6BufferEEES5_iSt10shared_ptrIS1_E
# 6  _ZN8facebook5velox4exec9wrapChildEiN5boost13intrusive_ptrINS0_6BufferEEERKSt10shared_ptrINS0_10BaseVectorEES5_
# 7  _ZN8facebook5velox4exec9HashProbe10fillOutputEi
# 8  _ZN8facebook5velox4exec9HashProbe9getOutputEv
# 9  _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE
# 10 _ZN8facebook5velox4exec6Driver4nextERSt10shared_ptrINS1_13BlockingStateEE
# 11 _ZN8facebook5velox4exec4Task4nextEPN5folly10SemiFutureINS3_4UnitEEE
# 12 _ZN6gluten24WholeStageResultIterator4nextEv
# 13 Java_io_glutenproject_vectorized_ColumnarBatchOutIterator_nativeHasNext
# 14 0x00007f94557c38a8

	at io.glutenproject.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
	at io.glutenproject.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:47)
	at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37)
	at io.glutenproject.backendsapi.velox.IteratorHandler$$anon$3.hasNext(IteratorHandler.scala:298)
	at io.glutenproject.vectorized.CloseableColumnBatchIterator.hasNext(CloseableColumnBatchIterator.scala:41)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.writer.gluten.uniffle.writer.NativeShuffleWriter.writeImpl(NativeShuffleWriter.scala:98)
	at org.apache.spark.writer.gluten.uniffle.writer.NativeShuffleWriter.write(NativeShuffleWriter.scala:80)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
23/07/29 13:03:05 ERROR YarnCoarseGrainedExecutorBackend: Executor self-exiting due to : Driver cnsz26pl10uz:34242 disassociated! Shutting down.
23/07/29 13:03:05 INFO YarnCoarseGrainedExecutorBackend: Driver from cnsz26pl10uz:34242 disconnected during shutdown
23/07/29 13:03:05 INFO MemoryStore: MemoryStore cleared
23/07/29 13:03:05 INFO BlockManager: BlockManager stopped
```

**Comment by PHILO-HE** [comment]
Just appended `[VL]` to indicate velox backend issue.
