### ISSUE TITLE
[VL][UT] GlutenBroadcastJoinSuite failed with LiveListenerBus is stopped

### ISSUE THREAD

**Issue by liujiayi771** [oap-project/gluten#2564]
**Describe the bug**
Run Gluten Velox UT
```
mvn clean install -Pspark-3.2 -Pspark-ut -Pbackends-velox -DargLine="-Dspark.test.home=/opt/spark322" -DwildcardSuites=org.apache.spark.sql.execution.joins.GlutenBroadcastJoinSuite
```

```
java.lang.IllegalStateException: LiveListenerBus is stopped.
  at org.apache.spark.scheduler.LiveListenerBus.addToQueue(LiveListenerBus.scala:97)
  at org.apache.spark.scheduler.LiveListenerBus.addToStatusQueue(LiveListenerBus.scala:80)
  at org.apache.spark.sql.internal.SharedState.<init>(SharedState.scala:115)
  at org.apache.spark.sql.SparkSession.$anonfun$sharedState$1(SparkSession.scala:139)
  at scala.Option.getOrElse(Option.scala:189)
  at org.apache.spark.sql.SparkSession.sharedState$lzycompute(SparkSession.scala:139)
  at org.apache.spark.sql.SparkSession.sharedState(SparkSession.scala:138)
  at org.apache.spark.sql.SparkSession.$anonfun$sessionState$2(SparkSession.scala:158)
  at scala.Option.getOrElse(Option.scala:189)
  at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:156)
```
The cause of the error may be that the spark context has stopped when ut is executed. The same UT can be executed successfully in spark.

**Comment by rui-mo** [comment]
cc @PHILO-HE

**Comment by Yohahaha** [comment]
Found same issue in PR #2843 

```
2023-08-23T04:22:14.4512057Z [32mGlutenBroadcastJoinSuite:[0m
2023-08-23T04:22:15.2727040Z 12:22:15.272 WARN org.apache.spark.sql.SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.
2023-08-23T04:22:15.3644432Z 12:22:15.363 ERROR org.apache.spark.deploy.worker.ExecutorRunner: Error running executor
2023-08-23T04:22:15.3645858Z java.lang.IllegalStateException: Cannot find any build directories.
2023-08-23T04:22:15.3646748Z 	at org.apache.spark.launcher.CommandBuilderUtils.checkState(CommandBuilderUtils.java:228)
2023-08-23T04:22:15.3647802Z 	at org.apache.spark.launcher.AbstractCommandBuilder.getScalaVersion(AbstractCommandBuilder.java:240)
2023-08-23T04:22:15.3648978Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildClassPath(AbstractCommandBuilder.java:194)
2023-08-23T04:22:15.3650132Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildJavaCommand(AbstractCommandBuilder.java:117)
2023-08-23T04:22:15.3651394Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:39)
2023-08-23T04:22:15.3652475Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:45)
2023-08-23T04:22:15.3653426Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildCommandSeq(CommandUtils.scala:63)
2023-08-23T04:22:15.3654409Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildProcessBuilder(CommandUtils.scala:51)
2023-08-23T04:22:15.3655410Z 	at org.apache.spark.deploy.worker.ExecutorRunner.org$apache$spark$deploy$worker$ExecutorRunner$$fetchAndRunExecutor(ExecutorRunner.scala:158)
2023-08-23T04:22:15.3656533Z 	at org.apache.spark.deploy.worker.ExecutorRunner$$anon$1.run(ExecutorRunner.scala:79)
2023-08-23T04:22:15.3657341Z 12:22:15.363 ERROR org.apache.spark.deploy.worker.ExecutorRunner: Error running executor
2023-08-23T04:22:15.3658181Z java.lang.IllegalStateException: Cannot find any build directories.
2023-08-23T04:22:15.3658996Z 	at org.apache.spark.launcher.CommandBuilderUtils.checkState(CommandBuilderUtils.java:228)
2023-08-23T04:22:15.3660054Z 	at org.apache.spark.launcher.AbstractCommandBuilder.getScalaVersion(AbstractCommandBuilder.java:240)
2023-08-23T04:22:15.3661145Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildClassPath(AbstractCommandBuilder.java:194)
2023-08-23T04:22:15.3662262Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildJavaCommand(AbstractCommandBuilder.java:117)
2023-08-23T04:22:15.3663348Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:39)
2023-08-23T04:22:15.3664375Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:45)
2023-08-23T04:22:15.3665316Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildCommandSeq(CommandUtils.scala:63)
2023-08-23T04:22:15.3666158Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildProcessBuilder(CommandUtils.scala:51)
2023-08-23T04:22:15.3667197Z 	at org.apache.spark.deploy.worker.ExecutorRunner.org$apache$spark$deploy$worker$ExecutorRunner$$fetchAndRunExecutor(ExecutorRunner.scala:158)
2023-08-23T04:22:15.3668207Z 	at org.apache.spark.deploy.worker.ExecutorRunner$$anon$1.run(ExecutorRunner.scala:79)
2023-08-23T04:22:15.4654668Z 12:22:15.464 ERROR org.apache.spark.deploy.worker.ExecutorRunner: Error running executor
2023-08-23T04:22:15.4656143Z java.lang.IllegalStateException: Cannot find any build directories.
2023-08-23T04:22:15.4657575Z 	at org.apache.spark.launcher.CommandBuilderUtils.checkState(CommandBuilderUtils.java:228)
2023-08-23T04:22:15.4659696Z 	at org.apache.spark.launcher.AbstractCommandBuilder.getScalaVersion(AbstractCommandBuilder.java:240)
2023-08-23T04:22:15.4661613Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildClassPath(AbstractCommandBuilder.java:194)
2023-08-23T04:22:15.4663490Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildJavaCommand(AbstractCommandBuilder.java:117)
2023-08-23T04:22:15.4665339Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:39)
2023-08-23T04:22:15.4667071Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:45)
2023-08-23T04:22:15.4668624Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildCommandSeq(CommandUtils.scala:63)
2023-08-23T04:22:15.4670109Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildProcessBuilder(CommandUtils.scala:51)
2023-08-23T04:22:15.4672796Z 	at org.apache.spark.deploy.worker.ExecutorRunner.org$apache$spark$deploy$worker$ExecutorRunner$$fetchAndRunExecutor(ExecutorRunner.scala:158)
2023-08-23T04:22:15.4674539Z 	at org.apache.spark.deploy.worker.ExecutorRunner$$anon$1.run(ExecutorRunner.scala:79)
2023-08-23T04:22:15.4675905Z 12:22:15.464 ERROR org.apache.spark.deploy.worker.ExecutorRunner: Error running executor
2023-08-23T04:22:15.4677139Z java.lang.IllegalStateException: Cannot find any build directories.
2023-08-23T04:22:15.4678543Z 	at org.apache.spark.launcher.CommandBuilderUtils.checkState(CommandBuilderUtils.java:228)
2023-08-23T04:22:15.4680549Z 	at org.apache.spark.launcher.AbstractCommandBuilder.getScalaVersion(AbstractCommandBuilder.java:240)
2023-08-23T04:22:15.4682388Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildClassPath(AbstractCommandBuilder.java:194)
2023-08-23T04:22:15.4684284Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildJavaCommand(AbstractCommandBuilder.java:117)
2023-08-23T04:22:15.4686284Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:39)
2023-08-23T04:22:15.4687979Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:45)
2023-08-23T04:22:15.4689558Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildCommandSeq(CommandUtils.scala:63)
2023-08-23T04:22:15.4691015Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildProcessBuilder(CommandUtils.scala:51)
2023-08-23T04:22:15.4692759Z 	at org.apache.spark.deploy.worker.ExecutorRunner.org$apache$spark$deploy$worker$ExecutorRunner$$fetchAndRunExecutor(ExecutorRunner.scala:158)
2023-08-23T04:22:15.4694818Z 	at org.apache.spark.deploy.worker.ExecutorRunner$$anon$1.run(ExecutorRunner.scala:79)
2023-08-23T04:22:15.5073959Z 12:22:15.506 ERROR org.apache.spark.deploy.worker.ExecutorRunner: Error running executor
2023-08-23T04:22:15.5075442Z java.lang.IllegalStateException: Cannot find any build directories.
2023-08-23T04:22:15.5076941Z 	at org.apache.spark.launcher.CommandBuilderUtils.checkState(CommandBuilderUtils.java:228)
2023-08-23T04:22:15.5078748Z 	at org.apache.spark.launcher.AbstractCommandBuilder.getScalaVersion(AbstractCommandBuilder.java:240)
2023-08-23T04:22:15.5080663Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildClassPath(AbstractCommandBuilder.java:194)
2023-08-23T04:22:15.5082569Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildJavaCommand(AbstractCommandBuilder.java:117)
2023-08-23T04:22:15.5084511Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:39)
2023-08-23T04:22:15.5087377Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:45)
2023-08-23T04:22:15.5089956Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildCommandSeq(CommandUtils.scala:63)
2023-08-23T04:22:15.5092439Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildProcessBuilder(CommandUtils.scala:51)
2023-08-23T04:22:15.5094231Z 	at org.apache.spark.deploy.worker.ExecutorRunner.org$apache$spark$deploy$worker$ExecutorRunner$$fetchAndRunExecutor(ExecutorRunner.scala:158)
2023-08-23T04:22:15.5095916Z 	at org.apache.spark.deploy.worker.ExecutorRunner$$anon$1.run(ExecutorRunner.scala:79)
2023-08-23T04:22:15.5216316Z 12:22:15.520 ERROR org.apache.spark.deploy.worker.ExecutorRunner: Error running executor
2023-08-23T04:22:15.5217704Z java.lang.IllegalStateException: Cannot find any build directories.
2023-08-23T04:22:15.5219373Z 	at org.apache.spark.launcher.CommandBuilderUtils.checkState(CommandBuilderUtils.java:228)
2023-08-23T04:22:15.5221258Z 	at org.apache.spark.launcher.AbstractCommandBuilder.getScalaVersion(AbstractCommandBuilder.java:240)
2023-08-23T04:22:15.5223161Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildClassPath(AbstractCommandBuilder.java:194)
2023-08-23T04:22:15.5225053Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildJavaCommand(AbstractCommandBuilder.java:117)
2023-08-23T04:22:15.5227277Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:39)
2023-08-23T04:22:15.5229025Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:45)
2023-08-23T04:22:15.5230623Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildCommandSeq(CommandUtils.scala:63)
2023-08-23T04:22:15.5232063Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildProcessBuilder(CommandUtils.scala:51)
2023-08-23T04:22:15.5233811Z 	at org.apache.spark.deploy.worker.ExecutorRunner.org$apache$spark$deploy$worker$ExecutorRunner$$fetchAndRunExecutor(ExecutorRunner.scala:158)
2023-08-23T04:22:15.5235660Z 	at org.apache.spark.deploy.worker.ExecutorRunner$$anon$1.run(ExecutorRunner.scala:79)
2023-08-23T04:22:15.5553558Z 12:22:15.554 ERROR org.apache.spark.deploy.worker.ExecutorRunner: Error running executor
2023-08-23T04:22:15.5555001Z java.lang.IllegalStateException: Cannot find any build directories.
2023-08-23T04:22:15.5556475Z 	at org.apache.spark.launcher.CommandBuilderUtils.checkState(CommandBuilderUtils.java:228)
2023-08-23T04:22:15.5558726Z 	at org.apache.spark.launcher.AbstractCommandBuilder.getScalaVersion(AbstractCommandBuilder.java:240)
2023-08-23T04:22:15.5560596Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildClassPath(AbstractCommandBuilder.java:194)
2023-08-23T04:22:15.5562491Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildJavaCommand(AbstractCommandBuilder.java:117)
2023-08-23T04:22:15.5564315Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:39)
2023-08-23T04:22:15.5566096Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:45)
2023-08-23T04:22:15.5567656Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildCommandSeq(CommandUtils.scala:63)
2023-08-23T04:22:15.5569138Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildProcessBuilder(CommandUtils.scala:51)
2023-08-23T04:22:15.5570886Z 	at org.apache.spark.deploy.worker.ExecutorRunner.org$apache$spark$deploy$worker$ExecutorRunner$$fetchAndRunExecutor(ExecutorRunner.scala:158)
2023-08-23T04:22:15.5572584Z 	at org.apache.spark.deploy.worker.ExecutorRunner$$anon$1.run(ExecutorRunner.scala:79)
2023-08-23T04:22:15.5648888Z 12:22:15.563 ERROR org.apache.spark.deploy.worker.ExecutorRunner: Error running executor
2023-08-23T04:22:15.5650342Z java.lang.IllegalStateException: Cannot find any build directories.
2023-08-23T04:22:15.5651770Z 	at org.apache.spark.launcher.CommandBuilderUtils.checkState(CommandBuilderUtils.java:228)
2023-08-23T04:22:15.5653577Z 	at org.apache.spark.launcher.AbstractCommandBuilder.getScalaVersion(AbstractCommandBuilder.java:240)
2023-08-23T04:22:15.5655478Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildClassPath(AbstractCommandBuilder.java:194)
2023-08-23T04:22:15.5657383Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildJavaCommand(AbstractCommandBuilder.java:117)
2023-08-23T04:22:15.5659898Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:39)
2023-08-23T04:22:15.5661646Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:45)
2023-08-23T04:22:15.5663235Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildCommandSeq(CommandUtils.scala:63)
2023-08-23T04:22:15.5664721Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildProcessBuilder(CommandUtils.scala:51)
2023-08-23T04:22:15.5666462Z 	at org.apache.spark.deploy.worker.ExecutorRunner.org$apache$spark$deploy$worker$ExecutorRunner$$fetchAndRunExecutor(ExecutorRunner.scala:158)
2023-08-23T04:22:15.5668131Z 	at org.apache.spark.deploy.worker.ExecutorRunner$$anon$1.run(ExecutorRunner.scala:79)
2023-08-23T04:22:15.6060454Z 12:22:15.604 ERROR org.apache.spark.deploy.worker.ExecutorRunner: Error running executor
2023-08-23T04:22:15.6061926Z java.lang.IllegalStateException: Cannot find any build directories.
2023-08-23T04:22:15.6063363Z 	at org.apache.spark.launcher.CommandBuilderUtils.checkState(CommandBuilderUtils.java:228)
2023-08-23T04:22:15.6065635Z 	at org.apache.spark.launcher.AbstractCommandBuilder.getScalaVersion(AbstractCommandBuilder.java:240)
2023-08-23T04:22:15.6067540Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildClassPath(AbstractCommandBuilder.java:194)
2023-08-23T04:22:15.6069449Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildJavaCommand(AbstractCommandBuilder.java:117)
2023-08-23T04:22:15.6071265Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:39)
2023-08-23T04:22:15.6072999Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:45)
2023-08-23T04:22:15.6074787Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildCommandSeq(CommandUtils.scala:63)
2023-08-23T04:22:15.6076229Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildProcessBuilder(CommandUtils.scala:51)
2023-08-23T04:22:15.6078007Z 	at org.apache.spark.deploy.worker.ExecutorRunner.org$apache$spark$deploy$worker$ExecutorRunner$$fetchAndRunExecutor(ExecutorRunner.scala:158)
2023-08-23T04:22:15.6079862Z 	at org.apache.spark.deploy.worker.ExecutorRunner$$anon$1.run(ExecutorRunner.scala:79)
2023-08-23T04:22:15.6156869Z 12:22:15.614 ERROR org.apache.spark.deploy.worker.ExecutorRunner: Error running executor
2023-08-23T04:22:15.6158254Z java.lang.IllegalStateException: Cannot find any build directories.
2023-08-23T04:22:15.6159693Z 	at org.apache.spark.launcher.CommandBuilderUtils.checkState(CommandBuilderUtils.java:228)
2023-08-23T04:22:15.6161537Z 	at org.apache.spark.launcher.AbstractCommandBuilder.getScalaVersion(AbstractCommandBuilder.java:240)
2023-08-23T04:22:15.6163468Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildClassPath(AbstractCommandBuilder.java:194)
2023-08-23T04:22:15.6165351Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildJavaCommand(AbstractCommandBuilder.java:117)
2023-08-23T04:22:15.6167205Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:39)
2023-08-23T04:22:15.6168947Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:45)
2023-08-23T04:22:15.6170538Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildCommandSeq(CommandUtils.scala:63)
2023-08-23T04:22:15.6171971Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildProcessBuilder(CommandUtils.scala:51)
2023-08-23T04:22:15.6173716Z 	at org.apache.spark.deploy.worker.ExecutorRunner.org$apache$spark$deploy$worker$ExecutorRunner$$fetchAndRunExecutor(ExecutorRunner.scala:158)
2023-08-23T04:22:15.6175411Z 	at org.apache.spark.deploy.worker.ExecutorRunner$$anon$1.run(ExecutorRunner.scala:79)
2023-08-23T04:22:15.6331323Z 12:22:15.625 ERROR org.apache.spark.deploy.master.Master: Application testing with ID app-20230822212215-0000 failed 10 times; removing it
2023-08-23T04:22:15.6406577Z 12:22:15.639 ERROR org.apache.spark.scheduler.cluster.StandaloneSchedulerBackend: Application has been killed. Reason: Master removed our application: FAILED
2023-08-23T04:22:15.6731524Z 12:22:15.672 ERROR org.apache.spark.deploy.worker.ExecutorRunner: Error running executor
2023-08-23T04:22:15.6733024Z java.lang.IllegalStateException: Cannot find any build directories.
2023-08-23T04:22:15.6734505Z 	at org.apache.spark.launcher.CommandBuilderUtils.checkState(CommandBuilderUtils.java:228)
2023-08-23T04:22:15.6736296Z 	at org.apache.spark.launcher.AbstractCommandBuilder.getScalaVersion(AbstractCommandBuilder.java:240)
2023-08-23T04:22:15.6738491Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildClassPath(AbstractCommandBuilder.java:194)
2023-08-23T04:22:15.6740439Z 	at org.apache.spark.launcher.AbstractCommandBuilder.buildJavaCommand(AbstractCommandBuilder.java:117)
2023-08-23T04:22:15.6742254Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:39)
2023-08-23T04:22:15.6744007Z 	at org.apache.spark.launcher.WorkerCommandBuilder.buildCommand(WorkerCommandBuilder.scala:45)
2023-08-23T04:22:15.6745602Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildCommandSeq(CommandUtils.scala:63)
2023-08-23T04:22:15.6747520Z 	at org.apache.spark.deploy.worker.CommandUtils$.buildProcessBuilder(CommandUtils.scala:51)
2023-08-23T04:22:15.6749247Z 	at org.apache.spark.deploy.worker.ExecutorRunner.org$apache$spark$deploy$worker$ExecutorRunner$$fetchAndRunExecutor(ExecutorRunner.scala:158)
2023-08-23T04:22:15.6750949Z 	at org.apache.spark.deploy.worker.ExecutorRunner$$anon$1.run(ExecutorRunner.scala:79)
2023-08-23T04:22:15.6797054Z 12:22:15.678 WARN org.apache.spark.deploy.master.Master: Got status update for unknown executor app-20230822212215-0000/10
2023-08-23T04:22:15.7091482Z 12:22:15.700 ERROR org.apache.spark.util.Utils: Uncaught exception in thread stop-spark-context
2023-08-23T04:22:15.7092954Z org.apache.spark.SparkException: Exception thrown in awaitResult: 
2023-08-23T04:22:15.7094143Z 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
2023-08-23T04:22:15.7095457Z 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
2023-08-23T04:22:15.7097437Z 	at org.apache.spark.deploy.client.StandaloneAppClient.stop(StandaloneAppClient.scala:287)
2023-08-23T04:22:15.7099791Z 	at org.apache.spark.scheduler.cluster.StandaloneSchedulerBackend.org$apache$spark$scheduler$cluster$StandaloneSchedulerBackend$$stop(StandaloneSchedulerBackend.scala:259)
2023-08-23T04:22:15.7102099Z 	at org.apache.spark.scheduler.cluster.StandaloneSchedulerBackend.stop(StandaloneSchedulerBackend.scala:131)
2023-08-23T04:22:15.7103880Z 	at org.apache.spark.scheduler.TaskSchedulerImpl.stop(TaskSchedulerImpl.scala:931)
2023-08-23T04:22:15.7105314Z 	at org.apache.spark.scheduler.DAGScheduler.stop(DAGScheduler.scala:2785)
2023-08-23T04:22:15.7106570Z 	at org.apache.spark.SparkContext.$anonfun$stop$11(SparkContext.scala:2095)
2023-08-23T04:22:15.7107765Z 	at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1484)
2023-08-23T04:22:15.7108951Z 	at org.apache.spark.SparkContext.stop(SparkContext.scala:2095)
2023-08-23T04:22:15.7110085Z 	at org.apache.spark.SparkContext$$anon$3.run(SparkContext.scala:2049)
2023-08-23T04:22:15.7111261Z Caused by: org.apache.spark.SparkException: Could not find AppClient.
2023-08-23T04:22:15.7112555Z 	at org.apache.spark.rpc.netty.Dispatcher.postMessage(Dispatcher.scala:178)
2023-08-23T04:22:15.7114010Z 	at org.apache.spark.rpc.netty.Dispatcher.postLocalMessage(Dispatcher.scala:144)
2023-08-23T04:22:15.7115462Z 	at org.apache.spark.rpc.netty.NettyRpcEnv.askAbortable(NettyRpcEnv.scala:242)
2023-08-23T04:22:15.7116998Z 	at org.apache.spark.rpc.netty.NettyRpcEndpointRef.askAbortable(NettyRpcEnv.scala:554)
2023-08-23T04:22:15.7118538Z 	at org.apache.spark.rpc.netty.NettyRpcEndpointRef.ask(NettyRpcEnv.scala:558)
2023-08-23T04:22:15.7119861Z 	at org.apache.spark.rpc.RpcEndpointRef.ask(RpcEndpointRef.scala:74)
2023-08-23T04:22:15.7120761Z 	... 9 more
2023-08-23T04:22:15.7121969Z 'unsafe broadcast hash join updates peak execution memory' offload to gluten
2023-08-23T04:22:15.7175673Z 'unsafe broadcast hash outer join updates peak execution memory' offload to gluten
2023-08-23T04:22:15.7213415Z 'unsafe broadcast left semi join updates peak execution memory' offload to gluten
2023-08-23T04:22:15.7259391Z [31m- unsafe broadcast hash join updates peak execution memory *** FAILED ***[0m
2023-08-23T04:22:15.7261603Z [31m  java.util.concurrent.ExecutionException: org.apache.spark.SparkException: Job aborted due to stage failure: Master removed our application: FAILED[0m
2023-08-23T04:22:15.7263456Z [31m  at java.util.concurrent.FutureTask.report(FutureTask.java:122)[0m
2023-08-23T04:22:15.7264877Z [31m  at java.util.concurrent.FutureTask.get(FutureTask.java:206)[0m
2023-08-23T04:22:15.7267060Z [31m  at org.apache.spark.sql.execution.exchange.BroadcastExchangeExec.doExecuteBroadcast(BroadcastExchangeExec.scala:208)[0m
2023-08-23T04:22:15.7269331Z [31m  at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeBroadcast$1(SparkPlan.scala:207)[0m
2023-08-23T04:22:15.7271139Z [31m  at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232)[0m
2023-08-23T04:22:15.7273252Z [31m  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)[0m
2023-08-23T04:22:15.7275021Z [31m  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229)[0m
2023-08-23T04:22:15.7276868Z [31m  at org.apache.spark.sql.execution.SparkPlan.executeBroadcast(SparkPlan.scala:203)[0m
2023-08-23T04:22:15.7279009Z [31m  at org.apache.spark.sql.execution.joins.BroadcastHashJoinExec.doExecute(BroadcastHashJoinExec.scala:142)[0m
2023-08-23T04:22:15.7281011Z [31m  at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:194)[0m
2023-08-23T04:22:15.7282399Z [31m  ...[0m
2023-08-23T04:22:15.7283836Z [31m  Cause: org.apache.spark.SparkException: Job aborted due to stage failure: Master removed our application: FAILED[0m
2023-08-23T04:22:15.7285855Z [31m  at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2672)[0m
2023-08-23T04:22:15.7287864Z [31m  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2608)[0m
2023-08-23T04:22:15.7289883Z [31m  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2607)[0m
2023-08-23T04:22:15.7291621Z [31m  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)[0m
2023-08-23T04:22:15.7293368Z [31m  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)[0m
2023-08-23T04:22:15.7295037Z [31m  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)[0m
2023-08-23T04:22:15.7296747Z [31m  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2607)[0m
2023-08-23T04:22:15.7298731Z [31m  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1182)[0m
2023-08-23T04:22:15.7300687Z [31m  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1182)[0m
2023-08-23T04:22:15.7302143Z [31m  at scala.Option.foreach(Option.scala:407)[0m
2023-08-23T04:22:15.7303000Z [31m  ...[0m
2023-08-23T04:22:15.7304162Z [31m- unsafe broadcast hash outer join updates peak execution memory *** FAILED ***[0m
2023-08-23T04:22:15.7305578Z [31m  java.lang.IllegalStateException: LiveListenerBus is stopped.[0m
2023-08-23T04:22:15.7307268Z [31m  at org.apache.spark.scheduler.LiveListenerBus.addToQueue(LiveListenerBus.scala:98)[0m
2023-08-23T04:22:15.7309206Z [31m  at org.apache.spark.scheduler.LiveListenerBus.addToSharedQueue(LiveListenerBus.scala:71)[0m
2023-08-23T04:22:15.7311055Z [31m  at org.apache.spark.SparkContext.addSparkListener(SparkContext.scala:1681)[0m
2023-08-23T04:22:15.7312882Z [31m  at org.apache.spark.AccumulatorSuite$.verifyPeakExecutionMemorySet(AccumulatorSuite.scala:126)[0m
2023-08-23T04:22:15.7315183Z [31m  at org.apache.spark.sql.execution.joins.BroadcastJoinSuiteBase.testBroadcastJoinPeak(BroadcastJoinSuite.scala:79)[0m
2023-08-23T04:22:15.7317763Z [31m  at org.apache.spark.sql.execution.joins.BroadcastJoinSuiteBase.$anonfun$new$2(BroadcastJoinSuite.scala:108)[0m
2023-08-23T04:22:15.7319594Z [31m  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)[0m
2023-08-23T04:22:15.7321654Z [31m  at org.apache.spark.sql.execution.adaptive.DisableAdaptiveExecutionSuite.$anonfun$test$5(AdaptiveTestUtils.scala:65)[0m
2023-08-23T04:22:15.7323787Z [31m  at org.apache.spark.sql.catalyst.plans.SQLHelper.withSQLConf(SQLHelper.scala:54)[0m
2023-08-23T04:22:15.7325635Z [31m  at org.apache.spark.sql.catalyst.plans.SQLHelper.withSQLConf$(SQLHelper.scala:38)[0m
2023-08-23T04:22:15.7326809Z [31m  ...[0m
```

**Comment by PHILO-HE** [comment]
It is not always producible. I will fix it. Thanks!

**Comment by Yohahaha** [comment]
Again in https://github.com/oap-project/gluten/pull/2875

**Comment by Yohahaha** [comment]
Hi @PHILO-HE 

Could you share the current status? does this issue be fixed? thanks!

**Comment by PHILO-HE** [comment]
Hi @Yohahaha, this issue is just related to the CI build environment (building spark source is not completed when do the test). We are preparing a new docker image with built spark source, which can avoid this issue and save CI time.

Before that new docker image ready, please re-trigger the CI (force push an empty change if no permission) if this test failure happens for your PR. Thanks!

**Comment by PHILO-HE** [comment]
FYI. As [this pr](https://github.com/oap-project/gluten/commit/e8a52318dba83f75486eadd7080eaea07bfa3fde) merged, this CI issue should not happen again. Thanks!

**Comment by PHILO-HE** [comment]
Suppose fixed.

**Comment by liujiayi771** [comment]
@PHILO-HE Does the Spark path `/opt/spark331` specified in the 'mvn' command need to be fully compiled, or is only the source code sufficient?

**Comment by PHILO-HE** [comment]
For some imported spark UTs, specifying spark source code home is enough, e.g. for using its *.sql files. But for some others like this `BroadcastJoinSuite`, it needs spark source code compiled.
I recommend you to build spark source code if many gluten UTs are executed on your local.
