### ISSUE TITLE
[Core] not support insert values

### ISSUE THREAD

**Issue by WolverineJiang** [oap-project/gluten#2661]
### Backend

VL (Velox)

### Bug description

If set spark.gluten.sql.native.parquet.writer.enabled true and use datasoruce v1, It will report java.lang.UnsupportedOperationException when insert values into parquet format table.

### Spark version

3.3.1.4

### Spark configurations

`spark.gluten.sql.native.parquet.writer.enabled=true`
`spark.sql.sources.useV1SourceList=parquet`

### Relevant logs

`Caused by: java.lang.UnsupportedOperationException
	at org.apache.spark.sql.execution.datasources.FakeRow.numFields(FakeRow.scala:28)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetWriteSupport.writeFields(ParquetWriteSupport.scala:160)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetWriteSupport.$anonfun$write$1(ParquetWriteSupport.scala:153)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetWriteSupport.consumeMessage(ParquetWriteSupport.scala:474)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetWriteSupport.write(ParquetWriteSupport.scala:153)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetWriteSupport.write(ParquetWriteSupport.scala:55)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:138)
	at org.apache.parquet.hadoop.ParquetRecordWriter.write(ParquetRecordWriter.java:181)
	at org.apache.parquet.hadoop.ParquetRecordWriter.write(ParquetRecordWriter.java:43)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetOutputWriter.write(ParquetOutputWriter.scala:39)
	at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.write(FileFormatDataWriter.scala:175)
	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.writeWithMetrics(FileFormatDataWriter.scala:85)
	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.writeWithIterator(FileFormatDataWriter.scala:92)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:331)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1567)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:338)
	... 9 more`

**Comment by WolverineJiang** [comment]
I'm work on it.

**Comment by PHILO-HE** [comment]
Assume fixed. Closing this issue. Thanks so much!
