### ISSUE TITLE
VeloxWholeStageTransformerSuite testcase failed.

### ISSUE THREAD

**Issue by LaiZhou** [oap-project/gluten#276]
@rui-mo 
**Describe the bug**
testcase failed, when running VeloxWholeStageTransformerSuite, it reports :
```
INFO VeloxWholeStageTransformerSuite: 

===== FINISHED io.glutenproject.execution.VeloxWholeStageTransformerSuite: 'generate hash join plan' =====



joins.forall(((x$1: io.glutenproject.execution.ShuffledHashJoinExecTransformer) => x$1.children.forall(((x$2: org.apache.spark.sql.execution.SparkPlan) => x$2.isInstanceOf[org.apache.spark.sql.execution.ColumnarInputAdapter])))) was false
ScalaTestFailureLocation: io.glutenproject.execution.VeloxWholeStageTransformerSuite at (VeloxWholeStageTransformerSuite.scala:58)
org.scalatest.exceptions.TestFailedException: joins.forall(((x$1: io.glutenproject.execution.ShuffledHashJoinExecTransformer) => x$1.children.forall(((x$2: org.apache.spark.sql.execution.SparkPlan) => x$2.isInstanceOf[org.apache.spark.sql.execution.ColumnarInputAdapter])))) was false
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:472)
	at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:471)
	at org.scalatest.Assertions$.newAssertionFailedException(Assertions.scala:1231)
	at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:1295)
	at io.glutenproject.execution.VeloxWholeStageTransformerSuite.$anonfun$new$2(VeloxWholeStageTransformerSuite.scala:58)
	at org.apache.spark.sql.catalyst.plans.SQLHelper.withSQLConf(SQLHelper.scala:54)
	at org.apache.spark.sql.catalyst.plans.SQLHelper.withSQLConf$(SQLHelper.scala:38)
	at io.glutenproject.execution.WholeStageTransformerSuite.org$apache$spark$sql$test$SQLTestUtilsBase$$super$withSQLConf(WholeStageTransformerSuite.scala:26)

```

the plan :
```
VeloxNativeColumnarToRowExec
+- *(1) ProjectExecTransformer [l_partkey#17]
   +- *(1) ShuffledHashJoinExecTransformer [knownfloatingpointnormalized(normalizenanandzero(l_suppkey#18))], [knownfloatingpointnormalized(normalizenanandzero(ps_suppkey#93))], Inner, BuildRight
      :- *(1) ProjectExecTransformer [l_partkey#17, l_suppkey#18]
      :  +- *(1) ShuffledHashJoinExecTransformer [knownfloatingpointnormalized(normalizenanandzero(l_partkey#17))], [knownfloatingpointnormalized(normalizenanandzero(p_partkey#74))], Inner, BuildRight
      :     :- *(1) VeloxFilterExecTransformer (isnotnull(l_partkey#17) AND isnotnull(l_suppkey#18))
      :     :  +- *(1) BatchScanExecTransformer[l_partkey#17, l_suppkey#18] OrcScan DataFilters: [isnotnull(l_partkey#17), isnotnull(l_suppkey#18)], Format: orc, Location: InMemoryFileIndex[file:/mnt/data/jvm/bigdata/gluten/backends-velox/target/scala-2.12/test-classes..., PartitionFilters: [], PushedFilers: [IsNotNull(l_partkey), IsNotNull(l_suppkey)], ReadSchema: struct<l_partkey:double,l_suppkey:double>, PushedFilters: [IsNotNull(l_partkey), IsNotNull(l_suppkey)]
      :     +- *(1) VeloxFilterExecTransformer isnotnull(p_partkey#74)
      :        +- *(1) BatchScanExecTransformer[p_partkey#74] OrcScan DataFilters: [isnotnull(p_partkey#74)], Format: orc, Location: InMemoryFileIndex[file:/mnt/data/jvm/bigdata/gluten/backends-velox/target/scala-2.12/test-classes..., PartitionFilters: [], PushedFilers: [IsNotNull(p_partkey)], ReadSchema: struct<p_partkey:double>, PushedFilters: [IsNotNull(p_partkey)]
      +- *(1) VeloxFilterExecTransformer isnotnull(ps_suppkey#93)
         +- *(1) BatchScanExecTransformer[ps_suppkey#93] OrcScan DataFilters: [isnotnull(ps_suppkey#93)], Format: orc, Location: InMemoryFileIndex[file:/mnt/data/jvm/bigdata/gluten/backends-velox/target/scala-2.12/test-classes..., PartitionFilters: [], PushedFilers: [IsNotNull(ps_suppkey)], ReadSchema: struct<ps_suppkey:double>, PushedFilters: [IsNotNull(ps_suppkey)]


```

ShuffledHashJoinExecTransformer is not  an instance of ColumnarInputAdapter, and no WholeStage here.

it's the rule to decide if to insert ColumnarInputAdapter,:
```
  private def insertInputAdapter(plan: SparkPlan): SparkPlan = {
    plan match {
      case p if !supportTransform(p) =>
        new ColumnarInputAdapter(insertWholeStageTransformer(p))
      case p =>
        p.withNewChildren(p.children.map(insertInputAdapter))
    }
  }

```

So I guess the generated plan is not correct, please fix me if I'm wrong.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by rui-mo** [comment]
Thanks for reporting this issue. We will take a look.

**Comment by rui-mo** [comment]
There is some differences between v1 and v2 plan. Test both of them in the fixing PR.
