### ISSUE TITLE
[CH] io.glutenproject.exception.GlutenException: Indices in strings are 1-based

### ISSUE THREAD

**Issue by zhanglistar** [oap-project/gluten#2876]
### Backend

CH (ClickHouse)

### Bug description

SQL:
2023-03-15_9717.json
related function:` substring_index `  or `substri`
Log:
```
23/08/23 18:37:19 INFO YarnCoarseGrainedExecutorBackend: Got assigned task 55659
23/08/23 18:37:19 INFO Executor: Running task 246.0 in stage 134.0 (TID 55659)
23/08/23 18:37:19 INFO TorrentBroadcast: Started reading broadcast variable 96 with 1 pieces (estimated total size 4.0 MiB)
23/08/23 18:37:19 INFO TransportClientFactory: Successfully created connection to sg-ha-rt-dn81.bigdata.bigo.inner/10.146.35.87:44267 after 1 ms (0 ms spent in bootstraps)
23/08/23 18:37:19 INFO MemoryStore: Block broadcast_96_piece0 stored as bytes in memory (estimated size 6.0 KiB, free 3.4 GiB)
23/08/23 18:37:19 INFO TorrentBroadcast: Reading broadcast variable 96 took 53 ms
23/08/23 18:37:19 INFO MemoryStore: Block broadcast_96 stored as values in memory (estimated size 12.9 KiB, free 3.4 GiB)
23/08/23 18:37:19 ERROR TaskResources: Task 55659 failed by error: 
io.glutenproject.exception.GlutenException: Indices in strings are 1-based
0. Poco::Exception::Exception(String const&, int) @ 0x000000001346b2b9 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
1. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000bb0b077 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
2. DB::Exception::Exception<char const (&) [31]>(int, char const (&) [31]) @ 0x0000000007c0c918 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
3. DB::(anonymous namespace)::FunctionSubstring<false>::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000000aa71a67 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
4. DB::IFunction::executeImplDryRun(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x0000000006a7df0a in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
5. DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x0000000006a7da2e in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
6. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f54964f in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
7. DB::IExecutableFunction::defaultImplementationForNulls(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f549970 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
8. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f54961d in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
9. DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f549fd8 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
10. DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f54b059 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
11. DB::ActionsDAG::updateHeader(DB::Block) const @ 0x000000000fa5a5e9 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
12. DB::ExpressionTransform::transformHeader(DB::Block, DB::ActionsDAG const&) @ 0x00000000112223e3 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
13. DB::ExpressionStep::ExpressionStep(DB::DataStream const&, std::shared_ptr<DB::ActionsDAG> const&) @ 0x000000001135f2f4 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
14. local_engine::ProjectRelParser::parseProject(std::unique_ptr<DB::QueryPlan, std::default_delete<DB::QueryPlan>>, substrait::Rel const&, std::list<substrait::Rel const*, std::allocator<substrait::Rel const*>>&) @ 0x000000000bc607df in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
15. local_engine::ProjectRelParser::parse(std::unique_ptr<DB::QueryPlan, std::default_delete<DB::QueryPlan>>, substrait::Rel const&, std::list<substrait::Rel const*, std::allocator<substrait::Rel const*>>&) @ 0x000000000bc605f9 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
16. local_engine::SerializedPlanParser::parseOp(substrait::Rel const&, std::list<substrait::Rel const*, std::allocator<substrait::Rel const*>>&) @ 0x000000000bc0c527 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
17. local_engine::SerializedPlanParser::parse(std::unique_ptr<substrait::Plan, std::default_delete<substrait::Plan>>) @ 0x000000000bc0a15c in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
18. local_engine::SerializedPlanParser::parse(String const&) @ 0x000000000bc1ce90 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
19. Java_io_glutenproject_vectorized_ExpressionEvaluatorJniWrapper_nativeCreateKernelWithIterator @ 0x00000000069d917f in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so

	at io.glutenproject.vectorized.ExpressionEvaluatorJniWrapper.nativeCreateKernelWithIterator(Native Method)
	at io.glutenproject.vectorized.CHNativeExpressionEvaluator.createKernelWithBatchIterator(CHNativeExpressionEvaluator.java:86)
	at io.glutenproject.backendsapi.clickhouse.CHIteratorApi.genFirstStageIterator(CHIteratorApi.scala:131)
	at io.glutenproject.execution.GlutenWholeStageColumnarRDD.compute(GlutenWholeStageColumnarRDD.scala:119)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
23/08/23 18:37:19 ERROR Executor: Exception in task 246.0 in stage 134.0 (TID 55659)
io.glutenproject.exception.GlutenException: Indices in strings are 1-based
0. Poco::Exception::Exception(String const&, int) @ 0x000000001346b2b9 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
1. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000bb0b077 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
2. DB::Exception::Exception<char const (&) [31]>(int, char const (&) [31]) @ 0x0000000007c0c918 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
3. DB::(anonymous namespace)::FunctionSubstring<false>::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000000aa71a67 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
4. DB::IFunction::executeImplDryRun(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x0000000006a7df0a in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
5. DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x0000000006a7da2e in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
6. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f54964f in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
7. DB::IExecutableFunction::defaultImplementationForNulls(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f549970 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
8. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f54961d in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
9. DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f549fd8 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
10. DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f54b059 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
11. DB::ActionsDAG::updateHeader(DB::Block) const @ 0x000000000fa5a5e9 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
12. DB::ExpressionTransform::transformHeader(DB::Block, DB::ActionsDAG const&) @ 0x00000000112223e3 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
13. DB::ExpressionStep::ExpressionStep(DB::DataStream const&, std::shared_ptr<DB::ActionsDAG> const&) @ 0x000000001135f2f4 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
14. local_engine::ProjectRelParser::parseProject(std::unique_ptr<DB::QueryPlan, std::default_delete<DB::QueryPlan>>, substrait::Rel const&, std::list<substrait::Rel const*, std::allocator<substrait::Rel const*>>&) @ 0x000000000bc607df in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
15. local_engine::ProjectRelParser::parse(std::unique_ptr<DB::QueryPlan, std::default_delete<DB::QueryPlan>>, substrait::Rel const&, std::list<substrait::Rel const*, std::allocator<substrait::Rel const*>>&) @ 0x000000000bc605f9 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
16. local_engine::SerializedPlanParser::parseOp(substrait::Rel const&, std::list<substrait::Rel const*, std::allocator<substrait::Rel const*>>&) @ 0x000000000bc0c527 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
17. local_engine::SerializedPlanParser::parse(std::unique_ptr<substrait::Plan, std::default_delete<substrait::Plan>>) @ 0x000000000bc0a15c in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
18. local_engine::SerializedPlanParser::parse(String const&) @ 0x000000000bc1ce90 in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so
19. Java_io_glutenproject_vectorized_ExpressionEvaluatorJniWrapper_nativeCreateKernelWithIterator @ 0x00000000069d917f in /data3/hadoop/yarn/local/usercache/zouyunhe/filecache/52/libch.so

	at io.glutenproject.vectorized.ExpressionEvaluatorJniWrapper.nativeCreateKernelWithIterator(Native Method)
	at io.glutenproject.vectorized.CHNativeExpressionEvaluator.createKernelWithBatchIterator(CHNativeExpressionEvaluator.java:86)
	at io.glutenproject.backendsapi.clickhouse.CHIteratorApi.genFirstStageIterator(CHIteratorApi.scala:131)
	at io.glutenproject.execution.GlutenWholeStageColumnarRDD.compute(GlutenWholeStageColumnarRDD.scala:119)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
23/08/23 18:37:19 INFO YarnCoarseGrainedExecutorBackend: Got assigned task 56317
23/08/23 18:37:19 INFO Executor: Running task 67.1 in stage 134.0 (TID 56317)
```

### Spark version

Spark-3.3.x

**Comment by zhanglistar** [comment]
As code of, we should check sometimes maybe gluten pass non-const column to clickhouse, triger this execption.
<img width="1006" alt="image" src="https://github.com/oap-project/gluten/assets/985418/7304c550-5362-4e8c-bad9-0c34e362d6ff">

**Comment by taiyang-li** [comment]
I'll fix it .

**Comment by taiyang-li** [comment]
It is strange.. I can't reproduce it with the same sql.
