### ISSUE TITLE
[VL] Error: (shuffle) nativeEvict: evict failed - Cannot evict partition -1 because writer is stopped

### ISSUE THREAD

**Issue by zhztheplayer** [oap-project/gluten#2941]
### Backend

VL (Velox)

### Bug description

```
23/08/29 13:39:41 ERROR ManagedReservationListener: Error reserving memory from target
java.lang.RuntimeException: (shuffle) nativeEvict: evict failed - Cannot evict partition -1 because writer is stopped.
	at io.glutenproject.vectorized.ShuffleWriterJniWrapper.nativeEvict(Native Method)
	at org.apache.spark.shuffle.ColumnarShuffleWriter$$anon$1.spill(ColumnarShuffleWriter.scala:151)
	at io.glutenproject.memory.memtarget.spark.GlutenMemoryConsumer.spill(GlutenMemoryConsumer.java:50)
	at org.apache.spark.memory.TaskMemoryManager.acquireExecutionMemory(TaskMemoryManager.java:177)
	at org.apache.spark.memory.MemoryConsumer.acquireMemory(MemoryConsumer.java:136)
	at io.glutenproject.memory.memtarget.OverAcquire$DummyTarget.borrow(OverAcquire.java:136)
	at io.glutenproject.memory.memtarget.OverAcquire.borrow(OverAcquire.java:70)
	at io.glutenproject.memory.memtarget.ThrowOnOomMemoryTarget.borrow(ThrowOnOomMemoryTarget.java:35)
	at io.glutenproject.memory.nmm.ManagedReservationListener.reserve(ManagedReservationListener.java:42)
	at io.glutenproject.vectorized.ShuffleWriterJniWrapper.stop(Native Method)
	at org.apache.spark.shuffle.ColumnarShuffleWriter.internalWrite(ColumnarShuffleWriter.scala:177)
	at org.apache.spark.shuffle.ColumnarShuffleWriter.write(ColumnarShuffleWriter.scala:218)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1491)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
pure virtual method called
terminate called without an active exception

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

```

To reproduce:

```
tools/gluten-it/sbin/gluten-it.sh queries --local --preset=velox --benchmark-type=ds --error-on-memleak --disable-aqe --off-heap-size=5g -s=100.0 --shuffle-partitions=72 --threads=8 --iterations=1 --queries=q67 --enable-history --enable-ui
```

### Spark version

3.2.2

**Comment by zhztheplayer** [comment]
Fixed by https://github.com/oap-project/gluten/pull/3029
