### ISSUE TITLE
[VL] nonSpilledRows is not empty after spill finish

### ISSUE THREAD

**Issue by jackylee-ch** [oap-project/gluten#3008]
### Backend

VL (Velox)

### Bug description

```
Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Retriable: False
Expression: nonSpilledRows.empty()
Function: noMoreInput
File: /code/gluten/ep/build-velox/build/velox_ep/velox/exec/OrderBy.cpp
Line: 290
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorENS1_22CompileTimeEmptyStringEEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZN8facebook5velox4exec7OrderBy11noMoreInputEv
# 4  _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE
# 5  _ZN8facebook5velox4exec6Driver4nextERSt10shared_ptrINS1_13BlockingStateEE
# 6  _ZN8facebook5velox4exec4Task4nextEPN5folly10SemiFutureINS3_4UnitEEE
# 7  _ZN6gluten24WholeStageResultIterator4nextEv
# 8  Java_io_glutenproject_vectorized_ColumnarBatchOutIterator_nativeHasNext
# 9  0x00007f3e188027e8
# 10 0x00007f3e19e6f8c4

	at io.glutenproject.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
	at io.glutenproject.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:52)
	at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:32)
	at io.glutenproject.backendsapi.velox.IteratorHandler$$anon$2.hasNext(IteratorHandler.scala:216)
	at io.glutenproject.vectorized.CloseableColumnBatchIterator.hasNext(CloseableColumnBatchIterator.scala:40)
	at scala.collection.Iterator.isEmpty(Iterator.scala:387)
	at scala.collection.Iterator.isEmpty$(Iterator.scala:387)
	at io.glutenproject.vectorized.CloseableColumnBatchIterator.isEmpty(CloseableColumnBatchIterator.scala:30)
	at org.apache.spark.sql.execution.ColumnarToRowRDD.$anonfun$f$1(VeloxColumnarToRowExec.scala:114)
	at org.apache.spark.sql.execution.ColumnarToRowRDD.compute(VeloxColumnarToRowExec.scala:109)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at io.glutenproject.execution.WholeStageZippedPartitionsRDD.$anonfun$compute$1(WholeStageZippedPartitionsRDD.scala:70)
	at scala.collection.immutable.List.map(List.scala:293)
	at io.glutenproject.execution.WholeStageZippedPartitionsRDD.compute(WholeStageZippedPartitionsRDD.scala:70)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:552)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1533)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:555)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

### Spark version

None

### Spark configurations

spark.memory.offHeap.size 32G
spark.executor.cores 8
spark.executor.memory 20g
spark.gluten.sql.columnar.backend.velox.spillStrategy auto
spark.gluten.sql.columnar.backend.velox.overAcquiredMemoryRatio 0.4
spark.sql.join.preferSortMergeJoin
spark.gluten.sql.columnar.forceShuffledHashJoin true

### System information

The latest Commit: a06e4f0a4662d69623c3b62cd87d013237e33b45

**Comment by PHILO-HE** [comment]
@zhztheplayer, thanks!
