### ISSUE TITLE
[CH] `stop` is called before `write` finished in `CelebornHashBasedCHColumnarShuffleWriter`

### ISSUE THREAD

**Issue by lgbo-ustc** [oap-project/gluten#3041]
### Backend

CH (ClickHouse)

### Bug description

[Expected behavior] and [actual behavior].

`stop` is called before `write` finished in `CelebornHashBasedCHColumnarShuffleWriter`, and cause exceptions.

### Spark version

Spark-3.3.x

### Relevant logs

```bash
2023-09-06 12:13:30.326 &lt;Error&gt; CelebornPartitionWriter: xxx CelebornPartitionWriter::~CelebornPartitionWriter. 140644406007648
23/09/06 12:13:30.326 INFO [Executor task launch worker for task 305.0 in stage 1.0 (TID 15305)] TaskMemoryManager: Memory used in task 15305
23/09/06 12:13:30.327 INFO [Executor task launch worker for task 305.0 in stage 1.0 (TID 15305)] TaskMemoryManager: Acquired by GlutenMemoryConsumer/CelebornShuffleWriter: 1.0 B
23/09/06 12:13:30.327 INFO [Executor task launch worker for task 305.0 in stage 1.0 (TID 15305)] TaskMemoryManager: Acquired by GlutenMemoryConsumer/ContextInstance: 42.9 MiB
23/09/06 12:13:30.327 INFO [Executor task launch worker for task 305.0 in stage 1.0 (TID 15305)] TaskMemoryManager: 0 bytes of memory were used by task 15305 but are not associated with specific consumers
23/09/06 12:13:30.327 INFO [Executor task launch worker for task 305.0 in stage 1.0 (TID 15305)] TaskMemoryManager: 44978440 bytes of memory are used for execution and 70688 bytes of memory are used for storage
23/09/06 12:13:30.327 WARN [Executor task launch worker for task 305.0 in stage 1.0 (TID 15305)] InFlightRequestTracker: Clear InFlightRequestTracker
23/09/06 12:13:30.328 ERROR [Executor task launch worker for task 305.0 in stage 1.0 (TID 15305)] TaskResources: Task 15305 failed by error:
io.glutenproject.exception.GlutenException: Block is empty
0. ./build1/../contrib/llvm-project/libcxx/include/exception:134: Poco::Exception::Exception(String const&amp;, int) @ 0x0000000013510db9 in /data5/hadoop/yarn/local/usercache/liangjiabiao/filecache/83271/libch.so
1. ./build1/../src/Common/Exception.cpp:98: DB::Exception::Exception(DB::Exception::MessageMasked&amp;&amp;, int, bool) @ 0x0000000006cfb677 in /data5/hadoop/yarn/local/usercache/liangjiabiao/filecache/83271/libch.so
2. DB::Exception::Exception&lt;char const (&amp;) [15]&gt;(int, char const (&amp;) [15]) @ 0x000000000e332c98 in /data5/hadoop/yarn/local/usercache/liangjiabiao/filecache/83271/libch.so
3. ./build1/../src/Core/Block.cpp:280: DB::Block::safeGetByPosition(unsigned long) const @ 0x000000000f6811d6 in /data5/hadoop/yarn/local/usercache/liangjiabiao/filecache/83271/libch.so
4. ./build1/../contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:93: DB::NativeWriter::write(DB::Block const&amp;) @ 0x000000001124084f in /data5/hadoop/yarn/local/usercache/liangjiabiao/filecache/83271/libch.so
5. ./build1/../utils/extern-local-engine/Shuffle/PartitionWriter.cpp:0: local_engine::CelebornPartitionWriter::evictPartitions(bool)::$_0::operator()() const @ 0x000000000732c6a0 in /data5/hadoop/yarn/local/usercache/liangjiabiao/filecache/83271/libch.so
6. ./build1/../utils/extern-local-engine/Shuffle/PartitionWriter.cpp:0: local_engine::CelebornPartitionWriter::evictPartitions(bool) @ 0x000000000732b635 in /data5/hadoop/yarn/local/usercache/liangjiabiao/filecache/83271/libch.so
7. ./build1/../utils/extern-local-engine/Shuffle/PartitionWriter.cpp:339: local_engine::CelebornPartitionWriter::stop() @ 0x000000000732d610 in /data5/hadoop/yarn/local/usercache/liangjiabiao/filecache/83271/libch.so
8. ./build1/../utils/extern-local-engine/Shuffle/CachedShuffleWriter.cpp:144: local_engine::CachedShuffleWriter::stop() @ 0x000000000731c8f7 in /data5/hadoop/yarn/local/usercache/liangjiabiao/filecache/83271/libch.so
9. ./build1/../contrib/llvm-project/libcxx/include/vector:537: Java_io_glutenproject_vectorized_CHShuffleSplitterJniWrapper_stop @ 0x0000000006bd0c80 in /data5/hadoop/yarn/local/usercache/liangjiabiao/filecache/83271/libch.so

        at io.glutenproject.vectorized.CHShuffleSplitterJniWrapper.stop(Native Method)
        at org.apache.spark.shuffle.gluten.celeborn.CelebornHashBasedCHColumnarShuffleWriter.internalWrite(CelebornHashBasedCHColumnarShuffleWriter.scala:145)
        at org.apache.spark.shuffle.gluten.celeborn.CelebornHashBasedCHColumnarShuffleWriter.write(CelebornHashBasedCHColumnarShuffleWriter.scala:88)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:60)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
        at org.apache.spark.scheduler.Task.run(Task.scala:136)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by lgbo-ustc** [comment]
find an OOM exception, maybe that is why this happen
```
23/09/06 15:14:13.926 ERROR [Thread-6] SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Thread-6,5,main]
java.lang.OutOfMemoryError: Java heap space
	at org.apache.celeborn.client.ShuffleClientImpl.pushOrMergeData(ShuffleClientImpl.java:855)
	at org.apache.celeborn.client.ShuffleClientImpl.pushData(ShuffleClientImpl.java:1157)
	at org.apache.spark.shuffle.gluten.celeborn.CelebornCHPartitionPusher.pushPartitionData(CelebornCHPartitionPusher.scala:50)
23/09/06 15:14:13.926 ERROR [SIGTERM handler] CoarseGrainedExecutorBackend: RECEIVED SIGNAL TERM
```

**Comment by lgbo-ustc** [comment]
Maybe the same reason in #3016

**Comment by lgbo-ustc** [comment]
trace the memory consumption in partition writer.
```
2023-09-06 16:53:41.276 &lt;Error&gt; PartitionWriter: xxx PartitionWriter::write. cache bytes. total_partition_buffer_size=1.51 GiB/1.52 GiB, total_partition_buffer_allocated_size=2.16 GiB/2.18 GiB, current mem usage:4.70 GiB
```
