### ISSUE TITLE
[VL] Crash in libunwind during shuffle reader is actively running, after task is killed

### ISSUE THREAD

**Issue by zhztheplayer** [oap-project/gluten#3062]
### Backend

VL (Velox)

### Bug description

Umbrella https://github.com/oap-project/gluten/issues/3048

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fc9ac010618, pid=862760, tid=0x00007fc4975f5700
#
# JRE version: OpenJDK Runtime Environment (8.0_382-b05) (build 1.8.0_382-8u382-ga-1~20.04.1-b05)
# Java VM: OpenJDK 64-Bit Server VM (25.382-b05 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libunwind.so.8+0x4618]
#
# Core dump written. Default location: /opt/gluten/tools/gluten-it/core or core.862760
#
# An error report file with more information is saved as:
# /opt/gluten/tools/gluten-it/hs_err_pid862760.log
23/09/07 16:00:03 WARN TaskSchedulerImpl: Could not kill task 226 because no task with that ID was found.
Killing task attempt after 4219 ms: 260
[thread 140486384633600 also had an error]
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
23/09/07 16:00:04 ERROR TaskResources: Task 260 failed by error: 
org.apache.spark.TaskKilledException
	at org.apache.spark.TaskContextImpl.killTaskIfInterrupted(TaskContextImpl.scala:216)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:36)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.shuffle.ColumnarShuffleWriter.internalWrite(ColumnarShuffleWriter.scala:118)
	at org.apache.spark.shuffle.ColumnarShuffleWriter.write(ColumnarShuffleWriter.scala:218)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1491)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
E0907 16:00:04.043340 863266 Exceptions.h:68] Line: ../../velox/exec/Task.cpp:1602, Function:terminate, Expression:  Cancelled, Source: RUNTIME, ErrorCode: INVALID_STATE
23/09/07 16:00:04 WARN TaskSetManager: Lost task 78.0 in stage 29.0 (TID 260) (55f8ad28c275 executor driver): TaskKilled (killed via SparkContext.killTaskAttempt)
```

Exception stack trace:
```
Killing task attempt after 2680 ms: 1653
terminate called after throwing an instance of 'gluten::GlutenException'
  what():  Error during calling Java code from native code: io.glutenproject.exception.GlutenException: java.nio.channels.ClosedByInterruptException
	at io.glutenproject.vectorized.LowCopyFileSegmentJniByteInputStream.read(LowCopyFileSegmentJniByteInputStream.java:110)
	at io.glutenproject.vectorized.ColumnarBatchOutIterator.nativeNext(Native Method)
	at io.glutenproject.vectorized.ColumnarBatchOutIterator.nextInternal(ColumnarBatchOutIterator.java:57)
	at io.glutenproject.vectorized.GeneralOutIterator.next(GeneralOutIterator.java:36)
	at io.glutenproject.vectorized.ColumnarBatchSerializerInstance$$anon$1.liftedTree1$1(ColumnarBatchSerializer.scala:154)
	at io.glutenproject.vectorized.ColumnarBatchSerializerInstance$$anon$1.readValue(ColumnarBatchSerializer.scala:153)
	at org.apache.spark.serializer.DeserializationStream$$anon$2.getNext(Serializer.scala:188)
	at org.apache.spark.serializer.DeserializationStream$$anon$2.getNext(Serializer.scala:185)
	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:73)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:31)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:32)
	at io.glutenproject.vectorized.GeneralInIterator.hasNext(GeneralInIterator.java:32)
	at io.glutenproject.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
	at io.glutenproject.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:52)
	at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:32)
	at io.glutenproject.backendsapi.velox.IteratorHandler$$anon$2.hasNext(IteratorHandler.scala:216)
	at io.glutenproject.vectorized.CloseableColumnBatchIterator.hasNext(CloseableColumnBatchIterator.scala:40)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.shuffle.ColumnarShuffleWriter.internalWrite(ColumnarShuffleWriter.scala:118)
	at org.apache.spark.shuffle.ColumnarShuffleWriter.write(ColumnarShuffleWriter.scala:218)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1491)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:164)
	at io.glutenproject.vectorized.LowCopyFileSegmentJniByteInputStream.read(LowCopyFileSegmentJniByteInputStream.java:102)
	... 33 more
```

Crash stack trace from gdb:

```
__GI_raise 0x00007f3ecd99600b
__GI_abort 0x00007f3ecd975859
<unknown> 0x00007f3ecc9c3911
<unknown> 0x00007f3ecc9cf38c
<unknown> 0x00007f3ecc9ce369
__gxx_personality_v0 0x00007f3ecc9ced21
<unknown> 0x00007f3ecc7cbbef
_Unwind_Resume 0x00007f3ecc7cc5aa
checkException JniCommon.h:142
SparkAllocationListener::updateReservation JniCommon.h:224
SparkAllocationListener::allocationChanged JniCommon.h:193
gluten::ListenableMemoryAllocator::free MemoryAllocator.cc:92
gluten::ArrowMemoryPool::Free ArrowMemoryPool.cc:43
arrow::PoolBuffer::~PoolBuffer memory_pool.cc:853
arrow::PoolBuffer::~PoolBuffer memory_pool.cc:855
std::default_delete::operator() unique_ptr.h:81
std::_Sp_counted_deleter::_M_dispose shared_ptr_base.h:471
std::_Sp_counted_base::_M_release shared_ptr_base.h:155
std::__shared_count::~__shared_count shared_ptr_base.h:730
std::__shared_ptr::~__shared_ptr shared_ptr_base.h:1169
std::shared_ptr::~shared_ptr shared_ptr.h:103
arrow::ipc::DecodeMessage message.cc:521
arrow::ipc::ReadMessage message.cc:550
ShuffleReaderOutStream::next reader.cc:47
gluten::ResultIterator::getNext ResultIterator.h:83
gluten::ResultIterator::hasNext ResultIterator.h:45
gluten::VeloxShuffleReaderOutStream::next VeloxShuffleReader.cc:372
gluten::ResultIterator::getNext ResultIterator.h:83
gluten::ResultIterator::hasNext ResultIterator.h:45
Java_io_glutenproject_vectorized_ColumnarBatchOutIterator_nativeNext JniWrapper.cc:396
<unknown> 0x00007f3ebb9d53f0
<unknown> 0x000000076b2f1468
std::_Sp_counted_ptr::~_Sp_counted_ptr shared_ptr_base.h:368
<unknown> 0x00007f3ebc35b36c
<unknown> 0x000000076b2f13d8
<unknown> 0x00000007c13d9a78
<unknown> 0x00000007c1216380
<unknown> 0x00000007c0024e60
<unknown> 0x00000007c05b7f88
<unknown> 0x00000007c05b8778
<unknown> 0x00000007c0000f28
<unknown> 0x00000007c05b8c08
<unknown> 0x00000007c1199ad8
<unknown> 0x00000007c01b9948
<unknown> 0x00007f379d8d7b60
<unknown> 0x62a8cd026e9fa900
<unknown> 0x00007f379d8d7b90
<unknown> 0x00007f37000ab950
<unknown> 0x00007f379d8d7bb0
<unknown> 0x00007f39da29b204
<unknown> 0x0000000000001000
<unknown> 0x0000000000000006
<unknown> 0x00007f3a74076000
__gnu_cxx::new_allocator::deallocate new_allocator.h:128
```

**Comment by zhztheplayer** [comment]
Probably duplicates https://github.com/oap-project/gluten/issues/3058
