### ISSUE TITLE
[VL] ShuffleWriter spill throws Error reallocating 0 bytes

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#3189]
### Backend

VL (Velox)

### Bug description

Expect shuffleWriter spill success, even if spilled 0 bytes, but it throws.

### Spark version

Spark-3.3.x

### Relevant logs

```bash
I0918 17:29:00.247943 1949205 WholeStageResultIterator.cc:166] Spill[WholeStageIterator_root/WholeStageIterator_root]: Trying to request spilling for 8388608 bytes...
I0918 17:29:00.248003 1949205 WholeStageResultIterator.cc:177] Spill[WholeStageIterator_root/WholeStageIterator_root]: Successfully spilled out 0 bytes.
I0918 17:29:00.248070 1949205 WholeStageResultIterator.cc:166] Spill[WholeStageIterator_root/WholeStageIterator_root]: Trying to request spilling for 8388608 bytes...
I0918 17:29:00.248075 1949205 WholeStageResultIterator.cc:177] Spill[WholeStageIterator_root/WholeStageIterator_root]: Successfully spilled out 0 bytes.
23/09/18 17:29:00 INFO [Executor task launch worker for task 1.0 in stage 37.0 (TID 6941)] ColumnarShuffleWriter: Gluten shuffle writer: Trying to spill 8388608 bytes of data
23/09/18 17:29:00 ERROR [Executor task launch worker for task 1.0 in stage 37.0 (TID 6941)] ManagedReservationListener: Error reserving memory from target
java.lang.RuntimeException: (shuffle) nativeEvict: evict failed - WrappedMemoryPool: Error reallocating 0 bytes
	at io.glutenproject.vectorized.ShuffleWriterJniWrapper.nativeEvict(Native Method) ~[gluten-velox-bundle-spark3.3_2.12-alinux_3-1.1.0-SNAPSHOT.jar:?]
	at org.apache.spark.shuffle.ColumnarShuffleWriter$$anon$1.spill(ColumnarShuffleWriter.scala:153) ~[gluten-velox-bundle-spark3.3_2.12-alinux_3-1.1.0-SNAPSHOT.jar:3.3.1]
	at io.glutenproject.memory.memtarget.spark.Spillers$WithMinSpillSize.spill(Spillers.java:54) ~[gluten-velox-bundle-spark3.3_2.12-alinux_3-1.1.0-SNAPSHOT.jar:?]
	at io.glutenproject.memory.memtarget.spark.Spillers.lambda$withOrder$0(Spillers.java:30) ~[gluten-velox-bundle-spark3.3_2.12-alinux_3-1.1.0-SNAPSHOT.jar:?]
	at io.glutenproject.memory.memtarget.spark.RegularMemoryConsumer.spill(RegularMemoryConsumer.java:57) ~[gluten-velox-bundle-spark3.3_2.12-alinux_3-1.1.0-SNAPSHOT.jar:?]
	at org.apache.spark.memory.TaskMemoryManager.trySpillAndAcquire(TaskMemoryManager.java:221) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.memory.TaskMemoryManager.acquireExecutionMemory(TaskMemoryManager.java:188) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.memory.MemoryConsumer.acquireMemory(MemoryConsumer.java:136) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at io.glutenproject.memory.memtarget.spark.RegularMemoryConsumer.borrow(RegularMemoryConsumer.java:103) ~[gluten-velox-bundle-spark3.3_2.12-alinux_3-1.1.0-SNAPSHOT.jar:?]
	at io.glutenproject.memory.memtarget.ThrowOnOomMemoryTarget.borrow(ThrowOnOomMemoryTarget.java:35) ~[gluten-velox-bundle-spark3.3_2.12-alinux_3-1.1.0-SNAPSHOT.jar:?]
	at io.glutenproject.memory.nmm.ManagedReservationListener.reserve(ManagedReservationListener.java:43) ~[gluten-velox-bundle-spark3.3_2.12-alinux_3-1.1.0-SNAPSHOT.jar:?]
	at io.glutenproject.vectorized.ShuffleWriterJniWrapper.split(Native Method) ~[gluten-velox-bundle-spark3.3_2.12-alinux_3-1.1.0-SNAPSHOT.jar:?]
	at org.apache.spark.shuffle.ColumnarShuffleWriter.internalWrite(ColumnarShuffleWriter.scala:166) ~[gluten-velox-bundle-spark3.3_2.12-alinux_3-1.1.0-SNAPSHOT.jar:3.3.1]
	at org.apache.spark.shuffle.ColumnarShuffleWriter.write(ColumnarShuffleWriter.scala:220) ~[gluten-velox-bundle-spark3.3_2.12-alinux_3-1.1.0-SNAPSHOT.jar:3.3.1]
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.scheduler.Task.run(Task.scala:136) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1516) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_372]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_372]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_372]
23/09/18 17:29:00 ERROR [Executor task launch worker for task 1.0 in stage 37.0 (TID 6941)] TaskResources: Task 6941 failed by error: 
java.lang.RuntimeException: Error during calling Java code from native code: java.lang.RuntimeException: (shuffle) nativeEvict: evict failed - WrappedMemoryPool: Error reallocating 0 bytes
	at io.glutenproject.vectorized.ShuffleWriterJniWrapper.nativeEvict(Native Method)
	at org.apache.spark.shuffle.ColumnarShuffleWriter$$anon$1.spill(ColumnarShuffleWriter.scala:153)
	at io.glutenproject.memory.memtarget.spark.Spillers$WithMinSpillSize.spill(Spillers.java:54)
	at io.glutenproject.memory.memtarget.spark.Spillers.lambda$withOrder$0(Spillers.java:30)
	at io.glutenproject.memory.memtarget.spark.RegularMemoryConsumer.spill(RegularMemoryConsumer.java:57)
	at org.apache.spark.memory.TaskMemoryManager.trySpillAndAcquire(TaskMemoryManager.java:221)
	at org.apache.spark.memory.TaskMemoryManager.acquireExecutionMemory(TaskMemoryManager.java:188)
	at org.apache.spark.memory.MemoryConsumer.acquireMemory(MemoryConsumer.java:136)
	at io.glutenproject.memory.memtarget.spark.RegularMemoryConsumer.borrow(RegularMemoryConsumer.java:103)
	at io.glutenproject.memory.memtarget.ThrowOnOomMemoryTarget.borrow(ThrowOnOomMemoryTarget.java:35)
	at io.glutenproject.memory.nmm.ManagedReservationListener.reserve(ManagedReservationListener.java:43)
	at io.glutenproject.vectorized.ShuffleWriterJniWrapper.split(Native Method)
	at org.apache.spark.shuffle.ColumnarShuffleWriter.internalWrite(ColumnarShuffleWriter.scala:166)
	at org.apache.spark.shuffle.ColumnarShuffleWriter.write(ColumnarShuffleWriter.scala:220)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1516)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

	at io.glutenproject.vectorized.ShuffleWriterJniWrapper.split(Native Method) ~[gluten-velox-bundle-spark3.3_2.12-alinux_3-1.1.0-SNAPSHOT.jar:?]
	at org.apache.spark.shuffle.ColumnarShuffleWriter.internalWrite(ColumnarShuffleWriter.scala:166) ~[gluten-velox-bundle-spark3.3_2.12-alinux_3-1.1.0-SNAPSHOT.jar:3.3.1]
	at org.apache.spark.shuffle.ColumnarShuffleWriter.write(ColumnarShuffleWriter.scala:220) ~[gluten-velox-bundle-spark3.3_2.12-alinux_3-1.1.0-SNAPSHOT.jar:3.3.1]
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.scheduler.Task.run(Task.scala:136) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1516) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_372]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_372]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_372]
E0918 17:29:00.271008 1949205 Exceptions.h:68] Line: ../../velox/exec/Task.cpp:1602, Function:terminate, Expression:  Cancelled, Source: RUNTIME, ErrorCode: INVALID_STATE
```

**Comment by zhztheplayer** [comment]
@marin-ma

**Comment by zuochunwei** [comment]
We also encountered this problem.

**Comment by marin-ma** [comment]
Thanks. We didn't handle the case properly if the split buffer size after shrink is 0. I will open a PR to fix it.
