### ISSUE TITLE
[VL] centos7 spark 3.2.4 + velox  protobuf conflict  lead to jvm crash.

### ISSUE THREAD

**Issue by chestnutqiang** [oap-project/gluten#3215]
### Backend

VL (Velox)

### Bug description

# Expected behavior 

```shell
/data/soft/spark-3.2.4-bin-hadoop3.2/bin/spark-sql --master local[*] \
>  --driver-java-options "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=10003" \
>  --conf spark.plugins=io.glutenproject.GlutenPlugin \
>  --conf spark.shuffle.manager=org.apache.spark.shuffle.sort.ColumnarShuffleManager \
>  --conf spark.gluten.loadLibFromJar=true \
>  --conf spark.memory.offHeap.enabled=true \
>  --conf spark.memory.offHeap.size=5g \
>  --conf spark.executor.extraClassPath=./* \
>  --conf spark.driver.extraClassPath=./* \
>  --conf spark.gluten.sql.columnar.backend.lib=velox \
>  --jars /data/soft/gluten/gluten-velox-bundle-spark3.2_2.12-centos_7-1.0.0.jar,/data/soft/gluten/gluten-thirdparty-lib-centos-7.jar
```

spark-sql starts successfully.

# actual behavio 

I suspect that protobuf is causing the conflict, and I have removed the Protobuf-related jars in spark jars

when linking libprotobuf.so.32  
The jvm crashed.
<img width="1145" alt="image" src="https://github.com/oap-project/gluten/assets/16716138/c78908fd-f161-4135-b212-bf382e52014f">

<img width="956" alt="image" src="https://github.com/oap-project/gluten/assets/16716138/f53dc406-20a5-4091-903f-75af9afce324">

<img width="1773" alt="image" src="https://github.com/oap-project/gluten/assets/16716138/1833e237-37c0-429c-8041-e578ba7270e4">

throw stack.
```
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007fa35c65caf6, pid=21009, tid=0x00007fa487a8d700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_144-b01) (build 1.8.0_144-b01)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.144-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libprotobuf.so.32+0x572af6]  google::protobuf::DoubleValue::DoubleValue(google::protobuf::internal::ConstantInitialized)+0x2e
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /root/hs_err_pid21009.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

# Hadoop version
```
Hadoop 3.2.1
Source code repository https://gitbox.apache.org/repos/asf/hadoop.git -r b3cbbb467e22ea829b3808f4b7b01d07e0bf3842
Compiled by rohithsharmaks on 2019-09-10T15:56Z
Compiled with protoc 2.5.0
From source with checksum 776eaf9eee9c0ffc370bcbc1888737
This command was run using /opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/hadoop-common-3.2.1.jar
```

### Spark version

None

### Spark configurations
```
/data/soft/spark-3.2.4-bin-hadoop3.2/bin/spark-sql --master local[*] \
 --driver-java-options "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=10003" \
 --conf spark.plugins=io.glutenproject.GlutenPlugin \
 --conf spark.shuffle.manager=org.apache.spark.shuffle.sort.ColumnarShuffleManager \
 --conf spark.gluten.loadLibFromJar=true \
 --conf spark.memory.offHeap.enabled=true \
 --conf spark.memory.offHeap.size=5g \
 --conf spark.executor.extraClassPath=./* \
 --conf spark.driver.extraClassPath=./* \
 --conf spark.gluten.sql.columnar.backend.lib=velox \
 --jars /data/soft/gluten/gluten-velox-bundle-spark3.2_2.12-centos_7-1.0.0.jar,/data/soft/gluten/gluten-thirdparty-lib-centos-7.jar
```

### System information

dev/info.sh Name has been changed.

gluten-build-info.sh      ?  

CentOS Linux release 7.9.2009 (Core)

### Relevant logs

```bash
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007fc62f61baf6, pid=26366, tid=0x00007fc79dccb700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_144-b01) (build 1.8.0_144-b01)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.144-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libprotobuf.so.32+0x572af6]  google::protobuf::DoubleValue::DoubleValue(google::protobuf::internal::ConstantInitialized)+0x2e
#
# Core dump written. Default location: /root/core or core.26366
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x00007fc794013000):  JavaThread "main" [_thread_in_native, id=26413, stack(0x00007fc79dbcc000,0x00007fc79dccc000)]

siginfo: si_signo: 4 (SIGILL), si_code: 2 (ILL_ILLOPN), si_addr: 0x00007fc62f61baf6

Registers:
RAX=0x00007fc62f757fc0, RBX=0x000000000000001f, RCX=0x0000000000000100, RDX=0x00007fc62f738710
RSP=0x00007fc79dcc7940, RBP=0x00007fc79dcc7950, RSI=0x0000000000000065, RDI=0x00007fc62f757fc8
R8 =0x00007fc794b49eb0, R9 =0x0000000000000000, R10=0x00007fc79dcc7520, R11=0x00007fc62f61bac8
R12=0x00007fc7940a2210, R13=0x00007fc62f731b38, R14=0x0000000000000000, R15=0x00007fc62f731858
RIP=0x00007fc62f61baf6, EFLAGS=0x0000000000010202, CSGSFS=0x0000000000000033, ERR=0x0000000000000000
  TRAPNO=0x0000000000000006

Top of Stack: (sp=0x00007fc79dcc7940)
0x00007fc79dcc7940:   000000000000001f 00007fc62f757fc0
0x00007fc79dcc7950:   00007fc79dcc7970 00007fc62f62001a
0x00007fc79dcc7960:   000000000000001f 00007fc62f757fc0
0x00007fc79dcc7970:   00007fc79dcc7990 00007fc62f61f97f
0x00007fc79dcc7980:   00007fc62f32e018 0000000100000065
0x00007fc79dcc7990:   00007fc79dcc79a0 00007fc62f61fb49
0x00007fc79dcc79a0:   00007ffc5c6d8208 00007fc79dacb9c3
0x00007fc79dcc79b0:   00007fc794b48c50 0000000000000008
0x00007fc79dcc79c0:   8000000000000000 000000000000000a
0x00007fc79dcc79d0:   00007fc79dcc7ab0 0000000000000008
0x00007fc79dcc79e0:   0000000000000001 0000000000000008
0x00007fc79dcc79f0:   00007fc794b48c50 00007fc79dad059e
0x00007fc79dcc7a00:   00007fc794b48c50 00007fc794b49170
0x00007fc79dcc7a10:   00007fc79dcc7ab0 00007fc79dad0359
0x00007fc79dcc7a20:   00000007c0000988 00007fc79dcc79d8
0x00007fc79dcc7a30:   00007fc700000001 0000000000000050
0x00007fc79dcc7a40:   00007fc79dcc7a00 00007fc79dcc7a20
0x00007fc79dcc7a50:   0000000000000001 0000000000000008
0x00007fc79dcc7a60:   00007fc79dcdf120 000000000000000b
0x00007fc79dcc7a70:   8000000100000001 00007fc79dcc7c18
0x00007fc79dcc7a80:   00007fc7980f0470 00007fc79dccb6f8
0x00007fc79dcc7a90:   0000000080000001 00007fc794b48b30
0x00007fc79dcc7aa0:   00007ffc5c6d8208 000000000000001f
0x00007fc79dcc7ab0:   00007fc79dcc7c90 00007fc79dacb7d4
0x00007fc79dcc7ac0:   00007fc79dccb6f8 00007fc79dcc7c08
0x00007fc79dcc7ad0:   00007fc79dcc7c10 00007fc79dcc7c00
0x00007fc79dcc7ae0:   00007fc79dad0160 00007fc79dcc7c18
0x00007fc79dcc7af0:   00007fc79dcc7cb0 00007fc79dcc7d10
0x00007fc79dcc7b00:   00007fc794013000 0000000000000000
0x00007fc79dcc7b10:   00007fc798260b28 fffffffffffffffe
0x00007fc79dcc7b20:   9c829a0f516625a0 0000000080000001
0x00007fc79dcc7b30:   00007fc794b48b30 00007ffc5c6d8208 

Instructions: (pc=0x00007fc62f61baf6)
0x00007fc62f61bad6:   45 f8 48 89 c7 e8 a0 2d db ff 48 8b 05 b9 dc 11
0x00007fc62f61bae6:   00 48 8d 50 10 48 8b 45 f8 48 89 10 48 8b 45 f8
0x00007fc62f61baf6:   c5 f9 57 c0 c5 fb 11 40 10 48 8b 45 f8 c7 40 18
0x00007fc62f61bb06:   00 00 00 00 90 c9 c3 90 55 48 89 e5 48 83 ec 10 

Register to memory mapping:

RAX=0x00007fc62f757fc0: _ZN6google8protobuf30_DoubleValue_default_instance_E+0 in /tmp/gluten-7cc9e68f-e25a-4b35-869b-57aa9d5a48d6/jni/cb61de8b-1c93-4235-81ab-6fa1afa4b314/gluten-3708686453622662243/libprotobuf.so.32 at 0x00007fc62f0a9000
RBX=0x000000000000001f is an unknown value
RCX=0x0000000000000100 is an unknown value
RDX=0x00007fc62f738710: _ZTVN6google8protobuf11DoubleValueE+0x10 in /tmp/gluten-7cc9e68f-e25a-4b35-869b-57aa9d5a48d6/jni/cb61de8b-1c93-4235-81ab-6fa1afa4b314/gluten-3708686453622662243/libprotobuf.so.32 at 0x00007fc62f0a9000
RSP=0x00007fc79dcc7940 is pointing into the stack for thread: 0x00007fc794013000
RBP=0x00007fc79dcc7950 is pointing into the stack for thread: 0x00007fc794013000
RSI=0x0000000000000065 is an unknown value
RDI=0x00007fc62f757fc8: _ZN6google8protobuf30_DoubleValue_default_instance_E+0x8 in /tmp/gluten-7cc9e68f-e25a-4b35-869b-57aa9d5a48d6/jni/cb61de8b-1c93-4235-81ab-6fa1afa4b314/gluten-3708686453622662243/libprotobuf.so.32 at 0x00007fc62f0a9000
R8 =0x00007fc794b49eb0 is an unknown value
R9 =0x0000000000000000 is an unknown value
R10=0x00007fc79dcc7520 is pointing into the stack for thread: 0x00007fc794013000
R11=0x00007fc62f61bac8: _ZN6google8protobuf11DoubleValueC2ENS0_8internal19ConstantInitializedE+0 in /tmp/gluten-7cc9e68f-e25a-4b35-869b-57aa9d5a48d6/jni/cb61de8b-1c93-4235-81ab-6fa1afa4b314/gluten-3708686453622662243/libprotobuf.so.32 at 0x00007fc62f0a9000
R12=0x00007fc7940a2210 is an unknown value
R13=0x00007fc62f731b38: <offset 0x688b38> in /tmp/gluten-7cc9e68f-e25a-4b35-869b-57aa9d5a48d6/jni/cb61de8b-1c93-4235-81ab-6fa1afa4b314/gluten-3708686453622662243/libprotobuf.so.32 at 0x00007fc62f0a9000
R14=0x0000000000000000 is an unknown value
R15=0x00007fc62f731858: <offset 0x688858> in /tmp/gluten-7cc9e68f-e25a-4b35-869b-57aa9d5a48d6/jni/cb61de8b-1c93-4235-81ab-6fa1afa4b314/gluten-3708686453622662243/libprotobuf.so.32 at 0x00007fc62f0a9000


Stack: [0x00007fc79dbcc000,0x00007fc79dccc000],  sp=0x00007fc79dcc7940,  free space=1006k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libprotobuf.so.32+0x572af6]  google::protobuf::DoubleValue::DoubleValue(google::protobuf::internal::ConstantInitialized)+0x2e
C  [libprotobuf.so.32+0x57701a]  google::protobuf::DoubleValueDefaultTypeInternal::DoubleValueDefaultTypeInternal()+0x18
C  [libprotobuf.so.32+0x57697f]  __static_initialization_and_destruction_0(int, int)+0x63
C  [libprotobuf.so.32+0x576b49]  _GLOBAL__sub_I.00101_wrappers.pb.cc+0x13
C  [ld-linux-x86-64.so.2+0xf9c3]  _dl_init_internal+0x113

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  java.lang.ClassLoader$NativeLibrary.load(Ljava/lang/String;Z)V+0
j  java.lang.ClassLoader.loadLibrary0(Ljava/lang/Class;Ljava/io/File;)Z+328
j  java.lang.ClassLoader.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)V+48
j  java.lang.Runtime.load0(Ljava/lang/Class;Ljava/lang/String;)V+57
j  java.lang.System.load(Ljava/lang/String;)V+7
j  io.glutenproject.vectorized.JniLibLoader.loadFromPath0(Ljava/lang/String;Z)V+27
j  io.glutenproject.vectorized.JniLibLoader.access$300(Ljava/lang/String;Z)V+2
j  io.glutenproject.vectorized.JniLibLoader$JniLoadTransaction.loadWithLink(Ljava/lang/String;Lio/glutenproject/vectorized/JniLibLoader$LoadAction;)V+13
j  io.glutenproject.vectorized.JniLibLoader$JniLoadTransaction.lambda$commit$1(Lio/glutenproject/vectorized/JniLibLoader$LoadAction;)V+23
j  io.glutenproject.vectorized.JniLibLoader$JniLoadTransaction$$Lambda$761.accept(Ljava/lang/Object;)V+8
j  java.util.ArrayList.forEach(Ljava/util/function/Consumer;)V+47
j  io.glutenproject.vectorized.JniLibLoader$JniLoadTransaction.commit()V+46
j  io.glutenproject.utils.SharedLibraryLoaderCentos7.loadLib(Lio/glutenproject/vectorized/JniLibLoader;)V+132
j  io.glutenproject.backendsapi.velox.ContextInitializer.loadLibFromJar(Lio/glutenproject/vectorized/JniLibLoader;)V+219
j  io.glutenproject.backendsapi.velox.ContextInitializer.initialize(Lorg/apache/spark/SparkConf;)V+30
j  io.glutenproject.GlutenDriverPlugin.init(Lorg/apache/spark/SparkContext;Lorg/apache/spark/api/plugin/PluginContext;)Ljava/util/Map;+54
j  org.apache.spark.internal.plugin.DriverPluginContainer.$anonfun$driverPlugins$1(Lorg/apache/spark/internal/plugin/DriverPluginContainer;Lorg/apache/spark/api/plugin/SparkPlugin;)Lscala/collection/Iterable;+77
j  org.apache.spark.internal.plugin.DriverPluginContainer$$Lambda$705.apply(Ljava/lang/Object;)Ljava/lang/Object;+8
j  scala.collection.TraversableLike.$anonfun$flatMap$1(Lscala/collection/mutable/Builder;Lscala/Function1;Ljava/lang/Object;)Lscala/collection/mutable/Builder;+3
j  scala.collection.TraversableLike$$Lambda$160.apply(Ljava/lang/Object;)Ljava/lang/Object;+9
j  scala.collection.mutable.ResizableArray.foreach(Lscala/Function1;)V+23
j  scala.collection.mutable.ResizableArray.foreach$(Lscala/collection/mutable/ResizableArray;Lscala/Function1;)V+2
j  scala.collection.mutable.ArrayBuffer.foreach(Lscala/Function1;)V+2
j  scala.collection.TraversableLike.flatMap(Lscala/Function1;Lscala/collection/generic/CanBuildFrom;)Ljava/lang/Object;+14
j  scala.collection.TraversableLike.flatMap$(Lscala/collection/TraversableLike;Lscala/Function1;Lscala/collection/generic/CanBuildFrom;)Ljava/lang/Object;+3
j  scala.collection.AbstractTraversable.flatMap(Lscala/Function1;Lscala/collection/generic/CanBuildFrom;)Ljava/lang/Object;+3
j  org.apache.spark.internal.plugin.DriverPluginContainer.<init>(Lorg/apache/spark/SparkContext;Ljava/util/Map;Lscala/collection/Seq;)V+32
j  org.apache.spark.internal.plugin.PluginContainer$.apply(Lscala/util/Either;Ljava/util/Map;)Lscala/Option;+104
j  org.apache.spark.internal.plugin.PluginContainer$.apply(Lorg/apache/spark/SparkContext;Ljava/util/Map;)Lscala/Option;+10
j  org.apache.spark.SparkContext.<init>(Lorg/apache/spark/SparkConf;)V+1802
j  org.apache.spark.SparkContext$.getOrCreate(Lorg/apache/spark/SparkConf;)Lorg/apache/spark/SparkContext;+23
j  org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(Lorg/apache/spark/SparkConf;)Lorg/apache/spark/SparkContext;+30
j  org.apache.spark.sql.SparkSession$Builder$$Lambda$363.apply()Ljava/lang/Object;+4
J 2166 C1 scala.Option.getOrElse(Lscala/Function0;)Ljava/lang/Object; (19 bytes) @ 0x00007fc77f370c9c [0x00007fc77f370aa0+0x1fc]
j  org.apache.spark.sql.SparkSession$Builder.getOrCreate()Lorg/apache/spark/sql/SparkSession;+134
j  org.apache.spark.sql.hive.thriftserver.SparkSQLEnv$.init()V+100
j  org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.<init>()V+94
j  org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main([Ljava/lang/String;)V+413
j  org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main([Ljava/lang/String;)V+4
v  ~StubRoutines::call_stub
j  sun.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+0
j  sun.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+100
j  sun.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+6
j  java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+56
j  org.apache.spark.deploy.JavaMainApplication.start([Ljava/lang/String;Lorg/apache/spark/SparkConf;)V+97
j  org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(Lorg/apache/spark/deploy/SparkSubmitArguments;Z)V+449
j  org.apache.spark.deploy.SparkSubmit.doRunMain$1(Lorg/apache/spark/deploy/SparkSubmitArguments;Z)V+196
j  org.apache.spark.deploy.SparkSubmit.submit(Lorg/apache/spark/deploy/SparkSubmitArguments;Z)V+65
j  org.apache.spark.deploy.SparkSubmit.doSubmit([Ljava/lang/String;)V+78
j  org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit([Ljava/lang/String;)V+2
j  org.apache.spark.deploy.SparkSubmit$.main([Ljava/lang/String;)V+10
j  org.apache.spark.deploy.SparkSubmit.main([Ljava/lang/String;)V+4
v  ~StubRoutines::call_stub
```

**Comment by chestnutqiang** [comment]
```
hadoop 2 mv mv /data/soft/spark-3.3.1-bin-hadoop2/jars/protobuf-*     ~/bak

```

```
23/09/20 18:23:13 INFO SharedState: spark.sql.warehouse.dir is not set, but hive.metastore.warehouse.dir is set. Setting spark.sql.warehouse.dir to the value of hive.metastore.warehouse.dir.
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/protobuf/ServiceException
	at org.apache.hadoop.ipc.ProtobufRpcEngine.<clinit>(ProtobufRpcEngine.java:72)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2134)
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2099)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2195)
	at org.apache.hadoop.ipc.RPC.getProtocolEngine(RPC.java:205)
	at org.apache.hadoop.ipc.RPC.getProtocolProxy(RPC.java:579)
	at org.apache.hadoop.hdfs.NameNodeProxies.createNNProxyWithClientProtocol(NameNodeProxies.java:428)
	at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:324)
	at org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider.getProxy(ConfiguredFailoverProxyProvider.java:124)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.<init>(RetryInvocationHandler.java:73)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.<init>(RetryInvocationHandler.java:64)
	at org.apache.hadoop.io.retry.RetryProxy.create(RetryProxy.java:59)
	at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:181)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:678)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:619)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:149)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:172)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:357)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at org.apache.spark.sql.internal.SharedState$.qualifyWarehousePath(SharedState.scala:282)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:137)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:958)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.ServiceException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more
23/09/20 18:23:13 INFO ShutdownHookManager: Shutdown hook called
23/09/20 18:23:13 INFO ShutdownHookManager: Deleting directory /tmp/spark-f7e94900-48fe-4c4e-82c5-26129bf177b7
```

**Comment by PHILO-HE** [comment]
Did you do the test with our published jars?
If so, for standard test without QAT, you should use only one jar (do not need third-party jar). And you need also turn off the below config.
`spark.gluten.loadLibFromJar=false`

**Comment by chestnutqiang** [comment]
I did the testing using the released package.
<img width="1033" alt="image" src="https://github.com/oap-project/gluten/assets/16716138/7c2c0e84-ac9f-4814-8fa3-4e7c903689c9">


If  I  set spark.gluten.loadLibFromJar=false  .
```
======================================
Gluten build info:
Gluten version: 1.0.0
GCC version: gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
Java version: 1.8.0_372
Scala version: 2.12.15
Spark version: 3.3.1
Hadoop version: 3.3.5
Build branch: branch-1.0
Build revision: bfe394b6f1d8ba7dbc5d369ccdd9cbe66dae9465
Build revision time: 2023-07-14 10:50:26 +0800
Build date: 2023-07-18T09:37:19Z
Repo url: https://github.com/oap-project/gluten.git
Velox branch: HEAD
Velox revision: 639daf95581f71c5ccd68d84f12e6d223f80077e
Velox revision time: 2023-06-26 10:45:18 +0000
======================================

23/09/21 11:47:54 INFO SparkDirectoryUtil: Created local directory at /tmp/gluten-391eff79-d09d-43a4-93dd-7c5bf3ebcdcf
23/09/21 11:47:54 INFO JniWorkspace: Creating JNI workspace in root directory /tmp/gluten-391eff79-d09d-43a4-93dd-7c5bf3ebcdcf/jni/1878d289-674d-4679-87ba-8555e177a5ee
23/09/21 11:47:54 INFO JniWorkspace: JNI workspace /tmp/gluten-391eff79-d09d-43a4-93dd-7c5bf3ebcdcf/jni/1878d289-674d-4679-87ba-8555e177a5ee/gluten-6514099027620343318 created in root directory /tmp/gluten-391eff79-d09d-43a4-93dd-7c5bf3ebcdcf/jni/1878d289-674d-4679-87ba-8555e177a5ee
23/09/21 11:47:55 INFO JniLibLoader: Trying to load library libarrow.so.1200.0.0
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007f3be7643777, pid=31784, tid=0x00007f3d44db2700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_144-b01) (build 1.8.0_144-b01)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.144-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libarrow.so.1200.0.0+0x12f2777]  orc::proto::IntegerStatistics::IntegerStatistics(google::protobuf::internal::ConstantInitialized)+0x7
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /root/hs_err_pid31784.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
```
Stack: [0x00007f3d44cb3000,0x00007f3d44db3000],  sp=0x00007f3d44daea28,  free space=1006k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libarrow.so.1200.0.0+0x12f2777]  orc::proto::IntegerStatistics::IntegerStatistics(google::protobuf::internal::ConstantInitialized)+0x7

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  java.lang.ClassLoader$NativeLibrary.load(Ljava/lang/String;Z)V+0
j  java.lang.ClassLoader.loadLibrary0(Ljava/lang/Class;Ljava/io/File;)Z+328
j  java.lang.ClassLoader.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)V+48
j  java.lang.Runtime.load0(Ljava/lang/Class;Ljava/lang/String;)V+57
j  java.lang.System.load(Ljava/lang/String;)V+7
j  io.glutenproject.vectorized.JniLibLoader.loadFromPath0(Ljava/lang/String;Z)V+27
```


I can successed in hadoop2  for gluten  0.5-snapshot  and 1.0.0 .

but in hadoop3  I can't succeed.

**Comment by PHILO-HE** [comment]
I note you are using this release jar: `gluten-velox-bundle-spark3.2_2.12-centos_7-1.0.0.jar`.

Two things need your confirmation.
1) For standard test, please do NOT configure third-party jar (e.g., gluten-thirdparty-lib-centos-7.jar). You only need to configure the above gluten jar.
2) I note you are using spark-3.3 according to your posted log, but  `gluten-velox-bundle-spark3.2_2.12-centos_7-1.0.0.jar` is for spark-3.2. You may need to download and config [gluten-velox-bundle-spark3.3_2.12-centos_7-1.0.0.jar](https://github.com/oap-project/gluten/releases/download/v1.0.0/gluten-velox-bundle-spark3.3_2.12-centos_7-1.0.0.jar) instead.

**Comment by chestnutqiang** [comment]
I I tested several versions, but they all failed. For different reasons

```
 /data/soft/spark-3.3.1-bin-hadoop2/bin/spark-sql --master local[*] \
 --driver-java-options "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=10003" \
 --conf spark.plugins=io.glutenproject.GlutenPlugin \
 --conf spark.shuffle.manager=org.apache.spark.shuffle.sort.ColumnarShuffleManager \
 --conf spark.gluten.loadLibFromJar=false \
 --conf spark.memory.offHeap.enabled=true \
 --conf spark.memory.offHeap.size=5g \
 --conf spark.executor.extraClassPath=./* \
 --conf spark.driver.extraClassPath=./* \
 --conf spark.gluten.sql.columnar.backend.lib=velox \
 --jars /data/soft/gluten/gluten-velox-bundle-spark3.3_2.12-centos_7-1.0.0.jar
```
