### ISSUE TITLE
[VL] Shuffle writer stop throws Error writing bytes to file

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#3235]
### Backend

VL (Velox)

### Bug description

I'm not sure which commit bring this issue, but it works before #2982

### Spark version

None

### Relevant logs

```bash
23/09/21 14:57:13 ERROR [Executor task launch worker for task 1.0 in stage 128.0 (TID 201)] TaskResources: Task 201 failed by error: 
java.lang.RuntimeException: Native split: shuffle writer stop failed - Error writing bytes to file
	at io.glutenproject.vectorized.ShuffleWriterJniWrapper.stop(Native Method) ~[gluten-velox-bundle-spark3.3_2.12-alinux_3-1.1.0-SNAPSHOT.jar:?]
	at org.apache.spark.shuffle.ColumnarShuffleWriter.internalWrite(ColumnarShuffleWriter.scala:186) ~[gluten-velox-bundle-spark3.3_2.12-alinux_3-1.1.0-SNAPSHOT.jar:3.3.1]
	at org.apache.spark.shuffle.ColumnarShuffleWriter.write(ColumnarShuffleWriter.scala:227) ~[gluten-velox-bundle-spark3.3_2.12-alinux_3-1.1.0-SNAPSHOT.jar:3.3.1]
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.scheduler.Task.run(Task.scala:136) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1516) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_372]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_372]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_372]
```

**Comment by Yohahaha** [comment]
@marin-ma

**Comment by marin-ma** [comment]
Which commit do you use?

**Comment by Yohahaha** [comment]
> Which commit do you use?

6a1a70b6

**Comment by Yohahaha** [comment]
Sry, my test machine's disk was full...

**Comment by marin-ma** [comment]
> Sry, my test machine's disk was full...

Got it. Besides, I saw similar exception in CI log. When the job fails (because of OOM, or other reasons), it looks like the BlockManager may quit before other tasks get killed.

```
2023-09-21T04:35:25.9923451Z java.lang.RuntimeException: Native split: shuffle writer stop failed - Failed to open local file '/tmp/blockmgr-9c62dacf-a8cb-4e59-a9b5-955372db8dc3/11/shuffle_0_45_0.data.4ba7e16f-22ce-408f-8073-1feb2d989e44'
2023-09-21T04:35:25.9924954Z 	at io.glutenproject.vectorized.ShuffleWriterJniWrapper.stop(Native Method)
2023-09-21T04:35:25.9926247Z 	at org.apache.spark.shuffle.ColumnarShuffleWriter.internalWrite(ColumnarShuffleWriter.scala:186)
2023-09-21T04:35:25.9927808Z 	at org.apache.spark.shuffle.ColumnarShuffleWriter.write(ColumnarShuffleWriter.scala:227)
2023-09-21T04:35:25.9929113Z 	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
2023-09-21T04:35:25.9930313Z 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
2023-09-21T04:35:25.9931423Z 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
2023-09-21T04:35:25.9932079Z 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
2023-09-21T04:35:25.9932707Z 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
2023-09-21T04:35:25.9933336Z 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1491)
2023-09-21T04:35:25.9933959Z 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
2023-09-21T04:35:25.9934684Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2023-09-21T04:35:25.9935439Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2023-09-21T04:35:25.9936029Z 	at java.lang.Thread.run(Thread.java:750)
```

cc: @zhztheplayer

**Comment by zhouyuan** [comment]
CC: @zuochunwei

**Comment by marin-ma** [comment]
And another log from CI. Seems like it fallback to Spark shuffle and throws simillar exception.

```
2023-09-21T04:35:23.8453909Z 23/09/21 04:35:23 ERROR DiskBlockObjectWriter: Uncaught exception while reverting partial writes to file /tmp/blockmgr-a0ab84c4-bb00-4aee-9ebe-defe60286673/12/temp_shuffle_b6806128-e3aa-4cb1-865a-b865c626fc12
2023-09-21T04:35:23.8456600Z java.io.FileNotFoundException: /tmp/blockmgr-a0ab84c4-bb00-4aee-9ebe-defe60286673/12/temp_shuffle_b6806128-e3aa-4cb1-865a-b865c626fc12 (No such file or directory)
2023-09-21T04:35:23.8458347Z   at java.io.FileOutputStream.open0(Native Method)
2023-09-21T04:35:23.8459490Z   at java.io.FileOutputStream.open(FileOutputStream.java:270)
2023-09-21T04:35:23.8460648Z   at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
2023-09-21T04:35:23.8462234Z   at org.apache.spark.storage.DiskBlockObjectWriter.$anonfun$revertPartialWritesAndClose$2(DiskBlockObjectWriter.scala:253)
2023-09-21T04:35:23.8463784Z   at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1500)
2023-09-21T04:35:23.8465520Z   at org.apache.spark.storage.DiskBlockObjectWriter.revertPartialWritesAndClose(DiskBlockObjectWriter.scala:250)
2023-09-21T04:35:23.8467677Z   at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.stop(BypassMergeSortShuffleWriter.java:292)
2023-09-21T04:35:23.8469505Z   at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:81)
2023-09-21T04:35:23.8471115Z   at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
2023-09-21T04:35:23.8472626Z   at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
2023-09-21T04:35:23.8473951Z   at org.apache.spark.scheduler.Task.run(Task.scala:131)
2023-09-21T04:35:23.8475185Z   at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
2023-09-21T04:35:23.8476466Z   at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1491)
2023-09-21T04:35:23.8477696Z   at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
2023-09-21T04:35:23.8479093Z   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2023-09-21T04:35:23.8480616Z   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2023-09-21T04:35:23.8481789Z   at java.lang.Thread.run(Thread.java:750)
```
