### ISSUE TITLE
[CH] Empty block make celeborn shuffle write failed

### ISSUE THREAD

**Issue by KevinyhZou** [oap-project/gluten#3366]
### Backend

CH (ClickHouse)

### Bug description

d_5212_0

When shuffle write to celeborn block by block, if one block is empty, which will make the shuffle write failed, and we get the exception as below
```
io.glutenproject.exception.GlutenException: Block is empty
0. Poco::Exception::Exception(String const&, int) @ 0x0000000013640739 in /data7/hadoop/yarn/local/usercache/zouyunhe/filecache/42900/libch.so
1. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000b8d6cb9 in /data7/hadoop/yarn/local/usercache/zouyunhe/filecache/42900/libch.so
2. DB::Exception::Exception<String>(int, FormatStringHelperImpl<std::type_identity<String>::type>, String&&) @ 0x0000000006b3ecc3 in /data7/hadoop/yarn/local/usercache/zouyunhe/filecache/42900/libch.so
3. DB::Block::safeGetByPosition(unsigned long) const @ 0x000000000f5cbbfd in /data7/hadoop/yarn/local/usercache/zouyunhe/filecache/42900/libch.so
4. DB::NativeWriter::write(DB::Block const&) @ 0x000000001115feaf in /data7/hadoop/yarn/local/usercache/zouyunhe/filecache/42900/libch.so
5. local_engine::CelebornPartitionWriter::evictPartitions(bool)::$_0::operator()() const @ 0x000000000bc2957b in /data7/hadoop/yarn/local/usercache/zouyunhe/filecache/42900/libch.so
6. local_engine::CelebornPartitionWriter::evictPartitions(bool) @ 0x000000000bc290c9 in /data7/hadoop/yarn/local/usercache/zouyunhe/filecache/42900/libch.so
7. local_engine::CelebornPartitionWriter::stop() @ 0x000000000bc29c50 in /data7/hadoop/yarn/local/usercache/zouyunhe/filecache/42900/libch.so
8. local_engine::CachedShuffleWriter::stop() @ 0x000000000bc1b3d7 in /data7/hadoop/yarn/local/usercache/zouyunhe/filecache/42900/libch.so
9. Java_io_glutenproject_vectorized_CHShuffleSplitterJniWrapper_stop @ 0x0000000006b1bdc0 in /data7/hadoop/yarn/local/usercache/zouyunhe/filecache/42900/libch.so

	at io.glutenproject.vectorized.CHShuffleSplitterJniWrapper.stop(Native Method)
	at org.apache.spark.shuffle.CelebornHashBasedCHColumnarShuffleWriter.internalWrite(CelebornHashBasedCHColumnarShuffleWriter.scala:108)
	at org.apache.spark.shuffle.CelebornHashBasedColumnarShuffleWriter.write(CelebornHashBasedColumnarShuffleWriter.scala:82)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:60)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### Spark version

Spark-3.3.x

**Comment by KevinyhZou** [comment]
在celeborn shuffle write 时，gluten 的offheap 内存使用已经到了极限，触发了spill操作。 shuffle write 和spill 都会调用 CelebornPartitonWriter中的evictPartitions 操作，从而造成了多线程安全的问题： A 线程执行完push到 celeborn之后，随即调用了partition.clear 方法，清除了parition中的block数据，而此时B 线程可能正在执行write， 突然遇到block 被清空，从而抛出了以上异常。

**Comment by lgbo-ustc** [comment]
FYI, this case has been reported in  https://github.com/oap-project/gluten/issues/3041
