### ISSUE TITLE
[VL] TPCDS 100T Core in __memmove_evex_unaligned_erms 

### ISSUE THREAD

**Issue by liujiayi771** [oap-project/gluten#3429]
### Backend

VL (Velox)

### Bug description

If executing TPC-DS queries consecutively within a session, around q38-q40, this exception is likely to occur. Restarting the session and executing the corresponding query separately will not have any issues.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fe13c82150d, pid=3616388, tid=0x00007fe097013640
#
# JRE version: OpenJDK Runtime Environment (8.0_362-b09) (build 1.8.0_362-b09)
# Java VM: OpenJDK 64-Bit Server VM (25.362-b09 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x15150d]  __memmove_evex_unaligned_erms+0xd
#
# Core dump written. Default location: /mnt/disk4/yarn/nm-local-dir/usercache/root/appcache/application_1697528125638_0001/container_1697528125638_0001_01_000017/core or core.3616388
#
# An error report file with more information is saved as:
# /mnt/disk4/yarn/nm-local-dir/usercache/root/appcache/application_1697528125638_0001/container_1697528125638_0001_01_000017/hs_err_pid3616388.log
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%208&component=java-1.8.0-openjdk
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
```
Core was generated by `/usr/lib/jvm/java-1.8.0/bin/java -server -Xmx2048m -XX:+IgnoreUnrecognizedVMOpt'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f3d338059d5 in raise () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f3c8969f640 (LWP 3893799))]
```
### Spark version

Spark-3.3.x

**Comment by rui-mo** [comment]
cc @zhouyuan

**Comment by FelixYBW** [comment]
can you get the call stack?

**Comment by liujiayi771** [comment]
> can you get the call stack?

I didn't see any useful stack information using gdb. I'll try running it in debug mode lib and see if it provides more insights.
```
#0  0x00007f89c3d3f9d5 in raise () from /lib64/libc.so.6
#1  0x00007f89c3d28894 in abort () from /lib64/libc.so.6
#2  0x00007f89c30334d7 in ?? ()
#3  0x00007f88e17dbed0 in ?? ()
#4  0x0000000000000376 in ?? ()
#5  0x00007f8986147150 in ?? ()
#6  0x00007f89c39f8d2a in ?? ()
#7  0x00007f883c29f2d0 in ?? ()
#8  0x1470b08a9f6fff00 in ?? ()
#9  0x0000000000000004 in ?? ()
#10 0x00007f8986147600 in ?? ()
#11 0x00007f89c3c127d8 in ?? ()
#12 0x0000005000000000 in ?? ()
#13 0x0000000000000000 in ?? ()
```

**Comment by liujiayi771** [comment]
```
#0  0x00007f34857359d5 in raise () from /lib64/libc.so.6
#1  0x00007f348571e894 in abort () from /lib64/libc.so.6
#2  0x00007f3484a294d7 in os::abort(bool) [clone .cold] () from /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.362.b09-2.al8.x86_64/jre/lib/amd64/server/libjvm.so
#3  0x00007f34853eed2a in VMError::report_and_die() () from /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.362.b09-2.al8.x86_64/jre/lib/amd64/server/libjvm.so
#4  0x00007f34851db21a in JVM_handle_linux_signal () from /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.362.b09-2.al8.x86_64/jre/lib/amd64/server/libjvm.so
#5  0x00007f34851ce0cc in signalHandler(int, siginfo_t*, void*) () from /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.362.b09-2.al8.x86_64/jre/lib/amd64/server/libjvm.so
#6  <signal handler called>
#7  0x00007f348584950d in __memmove_evex_unaligned_erms () from /lib64/libc.so.6
#8  0x00007f3438b2376b in facebook::velox::(anonymous namespace)::OssReadFile::getName() const ()
   from /mnt/disk2/yarn/nm-local-dir/usercache/root/appcache/application_1697528125638_0011/gluten-a00ff1b5-96d1-4b33-b2c7-85035fb27561/jni/fdd56962-e78b-4b7a-8371-fe16af0be7a8/gluten-7860803678158080970/libvelox.so
#9  0x00007f343a1e91a8 in facebook::velox::dwio::common::ReadFileInputStream::ReadFileInputStream(std::shared_ptr<facebook::velox::ReadFile>, std::shared_ptr<facebook::velox::dwio::common::MetricsLog const> const&, facebook::velox::dwio::common::IoStatistics*) ()
   from /mnt/disk2/yarn/nm-local-dir/usercache/root/appcache/application_1697528125638_0011/gluten-a00ff1b5-96d1-4b33-b2c7-85035fb27561/jni/fdd56962-e78b-4b7a-8371-fe16af0be7a8/gluten-7860803678158080970/libvelox.so
#10 0x00007f3438aeb5ae in facebook::velox::connector::hive::HiveDataSource::createBufferedInput(facebook::velox::FileHandle const&, facebook::velox::dwio::common::ReaderOptions const&) ()
   from /mnt/disk2/yarn/nm-local-dir/usercache/root/appcache/application_1697528125638_0011/gluten-a00ff1b5-96d1-4b33-b2c7-85035fb27561/jni/fdd56962-e78b-4b7a-8371-fe16af0be7a8/gluten-7860803678158080970/libvelox.so
#11 0x00007f3438aed292 in facebook::velox::connector::hive::HiveDataSource::addSplit(std::shared_ptr<facebook::velox::connector::ConnectorSplit>) ()
   from /mnt/disk2/yarn/nm-local-dir/usercache/root/appcache/application_1697528125638_0011/gluten-a00ff1b5-96d1-4b33-b2c7-85035fb27561/jni/fdd56962-e78b-4b7a-8371-fe16af0be7a8/gluten-7860803678158080970/libvelox.so
#12 0x00007f3437e50ff6 in facebook::velox::exec::TableScan::getOutput() ()
   from /mnt/disk2/yarn/nm-local-dir/usercache/root/appcache/application_1697528125638_0011/gluten-a00ff1b5-96d1-4b33-b2c7-85035fb27561/jni/fdd56962-e78b-4b7a-8371-fe16af0be7a8/gluten-7860803678158080970/libvelox.so
#13 0x00007f3437e2c49c in facebook::velox::exec::Driver::runInternal(std::shared_ptr<facebook::velox::exec::Driver>&, std::shared_ptr<facebook::velox::exec::BlockingState>&, std::shared_ptr<facebook::velox::RowVector>&) ()
   from /mnt/disk2/yarn/nm-local-dir/usercache/root/appcache/application_1697528125638_0011/gluten-a00ff1b5-96d1-4b33-b2c7-85035fb27561/jni/fdd56962-e78b-4b7a-8371-fe16af0be7a8/gluten-7860803678158080970/libvelox.so
#14 0x00007f3437e2d5b7 in facebook::velox::exec::Driver::next(std::shared_ptr<facebook::velox::exec::BlockingState>&) ()
   from /mnt/disk2/yarn/nm-local-dir/usercache/root/appcache/application_1697528125638_0011/gluten-a00ff1b5-96d1-4b33-b2c7-85035fb27561/jni/fdd56962-e78b-4b7a-8371-fe16af0be7a8/gluten-7860803678158080970/libvelox.so
#15 0x00007f3437e62c35 in facebook::velox::exec::Task::next(folly::SemiFuture<folly::Unit>*) ()
   from /mnt/disk2/yarn/nm-local-dir/usercache/root/appcache/application_1697528125638_0011/gluten-a00ff1b5-96d1-4b33-b2c7-85035fb27561/jni/fdd56962-e78b-4b7a-8371-fe16af0be7a8/gluten-7860803678158080970/libvelox.so
#16 0x00007f3436f6f1be in gluten::WholeStageResultIterator::next() ()
   from /mnt/disk2/yarn/nm-local-dir/usercache/root/appcache/application_1697528125638_0011/gluten-a00ff1b5-96d1-4b33-b2c7-85035fb27561/jni/fdd56962-e78b-4b7a-8371-fe16af0be7a8/gluten-7860803678158080970/libvelox.so
#17 0x00007f343b943eeb in Java_io_glutenproject_vectorized_ColumnarBatchOutIterator_nativeHasNext ()
   from /mnt/disk2/yarn/nm-local-dir/usercache/root/appcache/application_1697528125638_0011/gluten-a00ff1b5-96d1-4b33-b2c7-85035fb27561/jni/fdd56962-e78b-4b7a-8371-fe16af0be7a8/gluten-7860803678158080970/libgluten.so
#18 0x00007f347217876a in ?? ()
#19 0x00000000eb4906f8 in ?? ()
#20 0x00007f33e7849a20 in ?? ()
#21 0x0000000000000000 in ?? ()
```

**Comment by liujiayi771** [comment]
@FelixYBW Sorry, we have identified that this error originates from our internal code for accessing object storage. I will close this issue.
