### ISSUE TITLE
[CH] Query failed as division by zero

### ISSUE THREAD

**Issue by KevinyhZou** [oap-project/gluten#3452]
### Backend

CH (ClickHouse)

### Bug description

d_13485_0_0

```
io.glutenproject.exception.GlutenException: Division by zero: while executing 'FUNCTION divide(CAST(checkDecimalOverflowSparkOrNull(multiply(CAST(CAST(_w0#597,Nullable(D_0),Nullable(Decimal(38, 4))_2),1_1),26_5,4_6),Nullable(Decimal(38, 31))_8) :: 11, CAST(_we0_599,Nullable(D_7) :: 6) -> divide(CAST(checkDecimalOverflowSparkOrNull(multiply(CAST(CAST(_w0#597,Nullable(D_0),Nullable(Decimal(38, 4))_2),1_1),26_5,4_6),Nullable(Decimal(38, 31))_8),CAST(_we0_599,Nullable(D_7)) Nullable(Decimal(38, 31)) : 13'
0. Poco::Exception::Exception(String const&, int) @ 0x000000001490f179 in 
1. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000b910c79 in 
2. DB::Exception::Exception<char const (&) [17]>(int, char const (&) [17]) @ 0x0000000006c7e658 in 
3. auto DB::checkedDivision<wide::integer<128ul, int>, wide::integer<128ul, int>>(wide::integer<128ul, int>, wide::integer<128ul, int>) @ 0x0000000007f7ccbb in 
4. void DB::impl_::DecimalBinaryOperation<DB::DivideFloatingImpl, DB::Decimal<wide::integer<128ul, int>>, true>::processWithRightNullmapImpl<(DB::impl_::OpCase)0, void DB::impl_::DecimalBinaryOperation<DB::DivideFloatingImpl, DB::Decimal<wide::integer<128ul, int>>, true>::process<(DB::impl_::OpCase)0, true, true, DB::PODArray<DB::Decimal<wide::integer<128ul, int>>, 4096ul, Allocator<false, false>, 63ul, 64ul>, DB::PODArray<DB::Decimal<wide::integer<128ul, int>>, 4096ul, Allocator<false, false>, 63ul, 64ul>>(DB::PODArray<DB::Decimal<wide::integer<128ul, int>>, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, DB::PODArray<DB::Decimal<wide::integer<128ul, int>>, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, DB::PODArray<DB::Decimal<wide::integer<128ul, int>>, 4096ul, Allocator<false, false>, 63ul, 64ul>&, wide::integer<128ul, int>, wide::integer<128ul, int>, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> const*)::'lambda'(auto const&, auto const&), DB::PODArray<DB::Decimal<wide::integer<128ul, int>>, 4096ul, Allocator<false, false>, 63ul, 64ul>, DB::PODArray<DB::Decimal<wide::integer<128ul, int>>, 4096ul, Allocator<false, false>, 63ul, 64ul>>(DB::PODArray<DB::Decimal<wide::integer<128ul, int>>, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, DB::PODArray<DB::Decimal<wide::integer<128ul, int>>, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, DB::PODArray<DB::Decimal<wide::integer<128ul, int>>, 4096ul, Allocator<false, false>, 63ul, 64ul>&, unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> const*, auto) @ 0x000000000805e8aa in 
5. void DB::impl_::DecimalBinaryOperation<DB::DivideFloatingImpl, DB::Decimal<wide::integer<128ul, int>>, true>::process<(DB::impl_::OpCase)0, true, true, DB::PODArray<DB::Decimal<wide::integer<128ul, int>>, 4096ul, Allocator<false, false>, 63ul, 64ul>, DB::PODArray<DB::Decimal<wide::integer<128ul, int>>, 4096ul, Allocator<false, false>, 63ul, 64ul>>(DB::PODArray<DB::Decimal<wide::integer<128ul, int>>, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, DB::PODArray<DB::Decimal<wide::integer<128ul, int>>, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, DB::PODArray<DB::Decimal<wide::integer<128ul, int>>, 4096ul, Allocator<false, false>, 63ul, 64ul>&, wide::integer<128ul, int>, wide::integer<128ul, int>, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> const*) @ 0x000000000805e749 in 
6. COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::FunctionBinaryArithmetic<DB::DivideFloatingImpl, DB::NameDivide, true, true, true>::executeNumericWithDecimal<DB::DataTypeDecimal<DB::Decimal<wide::integer<128ul, int>>>, DB::DataTypeDecimal<DB::Decimal<wide::integer<128ul, int>>>, DB::DataTypeDecimal<DB::Decimal<wide::integer<128ul, int>>>, DB::DataTypeDecimal<DB::Decimal<wide::integer<128ul, int>>>, DB::DataTypeDecimal<DB::Decimal<wide::integer<128ul, int>>>, DB::ColumnDecimal<DB::Decimal<wide::integer<128ul, int>>>, DB::ColumnDecimal<DB::Decimal<wide::integer<128ul, int>>>>(DB::DataTypeDecimal<DB::Decimal<wide::integer<128ul, int>>> const&, DB::DataTypeDecimal<DB::Decimal<wide::integer<128ul, int>>> const&, DB::ColumnConst const*, DB::ColumnConst const*, DB::ColumnDecimal<DB::Decimal<wide::integer<128ul, int>>> const*, DB::ColumnDecimal<DB::Decimal<wide::integer<128ul, int>>> const*, unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> const*) const @ 0x000000000805e246 in 
7. COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::FunctionBinaryArithmetic<DB::DivideFloatingImpl, DB::NameDivide, true, true, true>::executeNumeric<DB::DataTypeDecimal<DB::Decimal<wide::integer<128ul, int>>>, DB::DataTypeDecimal<DB::Decimal<wide::integer<128ul, int>>>>(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, DB::DataTypeDecimal<DB::Decimal<wide::integer<128ul, int>>> const&, DB::DataTypeDecimal<DB::Decimal<wide::integer<128ul, int>>> const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> const*) const @ 0x000000000805dfa6 in 
8. auto auto bool DB::FunctionBinaryArithmetic<DB::DivideFloatingImpl, DB::NameDivide, true, true, true>::castBothTypes<DB::FunctionBinaryArithmetic<DB::DivideFloatingImpl, DB::NameDivide, true, true, true>::executeImpl2(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> const*) const::'lambda'(auto const&, auto const&)>(DB::IDataType const*, DB::IDataType const*, auto&&)::'lambda'(auto const&)::operator()<DB::DataTypeDecimal<DB::Decimal<wide::integer<128ul, int>>>>(auto const&) const::'lambda'(auto const&)::operator()<DB::DataTypeDecimal<DB::Decimal<wide::integer<128ul, int>>>>(auto const&) const @ 0x00000000080511e7 in 
9. bool DB::castTypeToEither<DB::DataTypeNumber<char8_t>, DB::DataTypeNumber<unsigned short>, DB::DataTypeNumber<unsigned int>, DB::DataTypeNumber<unsigned long>, DB::DataTypeNumber<wide::integer<128ul, unsigned int>>, DB::DataTypeNumber<wide::integer<256ul, unsigned int>>, DB::DataTypeNumber<signed char>, DB::DataTypeNumber<short>, DB::DataTypeNumber<int>, DB::DataTypeNumber<long>, DB::DataTypeNumber<wide::integer<128ul, int>>, DB::DataTypeNumber<wide::integer<256ul, int>>, DB::DataTypeDecimal<DB::Decimal<int>>, DB::DataTypeDecimal<DB::Decimal<long>>, DB::DataTypeDecimal<DB::Decimal<wide::integer<128ul, int>>>, DB::DataTypeDecimal<DB::Decimal<wide::integer<256ul, int>>>, DB::DataTypeDate, DB::DataTypeDateTime, DB::DataTypeFixedString, DB::DataTypeString, DB::DataTypeInterval, DB::DataTypeNumber<float>, DB::DataTypeNumber<double>, DB::IDataType, auto bool DB::FunctionBinaryArithmetic<DB::DivideFloatingImpl, DB::NameDivide, true, true, true>::castBothTypes<DB::FunctionBinaryArithmetic<DB::DivideFloatingImpl, DB::NameDivide, true, true, true>::executeImpl2(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> const*) const::'lambda'(auto const&, auto const&)>(DB::IDataType const*, DB::IDataType const*, auto&&)::'lambda'(auto const&)::operator()<DB::DataTypeDecimal<DB::Decimal<wide::integer<128ul, int>>>>(auto const&) const::'lambda'(auto const&)>(TypeList<DB::DataTypeNumber<char8_t>, DB::DataTypeNumber<unsigned short>, DB::DataTypeNumber<unsigned int>, DB::DataTypeNumber<unsigned long>, DB::DataTypeNumber<wide::integer<128ul, unsigned int>>, DB::DataTypeNumber<wide::integer<256ul, unsigned int>>, DB::DataTypeNumber<signed char>, DB::DataTypeNumber<short>, DB::DataTypeNumber<int>, DB::DataTypeNumber<long>, DB::DataTypeNumber<wide::integer<128ul, int>>, DB::DataTypeNumber<wide::integer<256ul, int>>, DB::DataTypeDecimal<DB::Decimal<int>>, DB::DataTypeDecimal<DB::Decimal<long>>, DB::DataTypeDecimal<DB::Decimal<wide::integer<128ul, int>>>, DB::DataTypeDecimal<DB::Decimal<wide::integer<256ul, int>>>, DB::DataTypeDate, DB::DataTypeDateTime, DB::DataTypeFixedString, DB::DataTypeString, DB::DataTypeInterval, DB::DataTypeNumber<float>, DB::DataTypeNumber<double>>, auto const*, auto bool DB::FunctionBinaryArithmetic<DB::DivideFloatingImpl, DB::NameDivide, true, true, true>::castBothTypes<DB::FunctionBinaryArithmetic<DB::DivideFloatingImpl, DB::NameDivide, true, true, true>::executeImpl2(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> const*) const::'lambda'(auto const&, auto const&)>(DB::IDataType const*, DB::IDataType const*, auto&&)::'lambda'(auto const&)::operator()<DB::DataTypeDecimal<DB::Decimal<wide::integer<128ul, int>>>>(auto const&) const::'lambda'(auto const&)&&) @ 0x0000000008050db6 in 
10. bool DB::castTypeToEither<DB::DataTypeNumber<char8_t>, DB::DataTypeNumber<unsigned short>, DB::DataTypeNumber<unsigned int>, DB::DataTypeNumber<unsigned long>, DB::DataTypeNumber<wide::integer<128ul, unsigned int>>, DB::DataTypeNumber<wide::integer<256ul, unsigned int>>, DB::DataTypeNumber<signed char>, DB::DataTypeNumber<short>, DB::DataTypeNumber<int>, DB::DataTypeNumber<long>, DB::DataTypeNumber<wide::integer<128ul, int>>, DB::DataTypeNumber<wide::integer<256ul, int>>, DB::DataTypeDecimal<DB::Decimal<int>>, DB::DataTypeDecimal<DB::Decimal<long>>, DB::DataTypeDecimal<DB::Decimal<wide::integer<128ul, int>>>, DB::DataTypeDecimal<DB::Decimal<wide::integer<256ul, int>>>, DB::DataTypeDate, DB::DataTypeDateTime, DB::DataTypeFixedString, DB::DataTypeString, DB::DataTypeInterval, DB::DataTypeNumber<float>, DB::DataTypeNumber<double>, DB::IDataType, bool DB::FunctionBinaryArithmetic<DB::DivideFloatingImpl, DB::NameDivide, true, true, true>::castBothTypes<DB::FunctionBinaryArithmetic<DB::DivideFloatingImpl, DB::NameDivide, true, true, true>::executeImpl2(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> const*) const::'lambda'(auto const&, auto const&)>(DB::IDataType const*, DB::IDataType const*, auto&&)::'lambda'(auto const&)>(TypeList<DB::DataTypeNumber<char8_t>, DB::DataTypeNumber<unsigned short>, DB::DataTypeNumber<unsigned int>, DB::DataTypeNumber<unsigned long>, DB::DataTypeNumber<wide::integer<128ul, unsigned int>>, DB::DataTypeNumber<wide::integer<256ul, unsigned int>>, DB::DataTypeNumber<signed char>, DB::DataTypeNumber<short>, DB::DataTypeNumber<int>, DB::DataTypeNumber<long>, DB::DataTypeNumber<wide::integer<128ul, int>>, DB::DataTypeNumber<wide::integer<256ul, int>>, DB::DataTypeDecimal<DB::Decimal<int>>, DB::DataTypeDecimal<DB::Decimal<long>>, DB::DataTypeDecimal<DB::Decimal<wide::integer<128ul, int>>>, DB::DataTypeDecimal<DB::Decimal<wide::integer<256ul, int>>>, DB::DataTypeDate, DB::DataTypeDateTime, DB::DataTypeFixedString, DB::DataTypeString, DB::DataTypeInterval, DB::DataTypeNumber<float>, DB::DataTypeNumber<double>>, auto const*, bool DB::FunctionBinaryArithmetic<DB::DivideFloatingImpl, DB::NameDivide, true, true, true>::castBothTypes<DB::FunctionBinaryArithmetic<DB::DivideFloatingImpl, DB::NameDivide, true, true, true>::executeImpl2(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> const*) const::'lambda'(auto const&, auto const&)>(DB::IDataType const*, DB::IDataType const*, auto&&)::'lambda'(auto const&)&&) @ 0x0000000007f717e9 in 
11. DB::FunctionBinaryArithmetic<DB::DivideFloatingImpl, DB::NameDivide, true, true, true>::executeImpl2(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> const*) const @ 0x0000000007f6de76 in 
12. DB::FunctionBinaryArithmetic<DB::DivideFloatingImpl, DB::NameDivide, true, true, true>::executeImpl2(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> const*) const @ 0x0000000007f6dceb in 
13. DB::FunctionBinaryArithmetic<DB::DivideFloatingImpl, DB::NameDivide, true, true, true>::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x0000000007f6cd0f in 
14. DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x0000000006c5540e in 
15. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f53d365 in 
16. DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f53dcd8 in 
17. DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f53ed59 in 
18. DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const @ 0x00000000100cc8e4 in 
19. DB::ExpressionTransform::transform(DB::Chunk&) @ 0x0000000011390b93 in 
20. DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x0000000011230953 in 
21. DB::ISimpleTransform::work() @ 0x000000001129562f in 
22. DB::ExecutionThreadContext::executeTask() @ 0x00000000112adb13 in 
23. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x00000000112a5730 in 
24. DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x00000000112a5069 in 
25. DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x00000000112b2270 in 
26. DB::PullingPipelineExecutor::pull(DB::Block&) @ 0x00000000112b2450 in 
27. local_engine::LocalExecutor::hasNext() @ 0x000000000bb6ddd0 in 
28. Java_io_glutenproject_vectorized_BatchIterator_nativeHasNext @ 0x0000000006b4d2b7 in 

	at io.glutenproject.vectorized.BatchIterator.nativeHasNext(Native Method)
	at io.glutenproject.vectorized.BatchIterator.hasNextInternal(BatchIterator.java:53)
	at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:32)
	at io.glutenproject.backendsapi.clickhouse.CHIteratorApi$$anon$2.hasNext(CHIteratorApi.scala:195)
	at io.glutenproject.vectorized.CloseableCHColumnBatchIterator.$anonfun$hasNext$1(CloseableCHColumnBatchIterator.scala:42)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at io.glutenproject.metrics.GlutenTimeMetric$.withNanoTime(GlutenTimeMetric.scala:41)
	at io.glutenproject.vectorized.CloseableCHColumnBatchIterator.hasNext(CloseableCHColumnBatchIterator.scala:42)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.shuffle.CHCelebornHashBasedColumnarShuffleWriter.internalWrite(CHCelebornHashBasedColumnarShuffleWriter.scala:58)
	at org.apache.spark.shuffle.CelebornHashBasedColumnarShuffleWriter.write(CelebornHashBasedColumnarShuffleWriter.scala:82)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:60)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

### Spark version

Spark-3.3.x

**Comment by taiyang-li** [comment]
问题出在这里， ch中有两种division, 一种是浮点数divide, 另一种是整数intDiv.  后者遇到零会抛异常。

如果两个decimal128相除，首先会获取底层的native type即int128, 然后对两个int128执行intDiv。如果分母为零就报错了


这是另一个diff,  两个decimal相除，ch输出类型也是decimal，会丢失精度。


```
0: jdbc:hive2://localhost:10000/> select cast(1.2 as decimal(10,2)) / cast(1.3 as decimal(10,2)); 
+----------------------------------------------------+
| (CAST(1.2 AS DECIMAL(10,2)) / CAST(1.3 AS DECIMAL(10,2))) |
+----------------------------------------------------+
| 0.9230769230769                                    |
+----------------------------------------------------+


SELECT
    intDiv(CAST(1.2, 'decimal(10, 2)'), CAST(1.3, 'decimal(10, 2)')) AS x,
    toTypeName(x)

Query id: a43d50e9-5108-4f19-94f5-a9471464e4c4

┌────x─┬─toTypeName(intDiv(CAST(1.2, 'decimal(10, 2)'), CAST(1.3, 'decimal(10, 2)')))─┐
│ 0.92 │ Decimal(18, 2)                                                               │
└──────┴──────────────────────────────────────────────────────────────────────────────┘
```

**Comment by taiyang-li** [comment]
I'll fix it.
