### ISSUE TITLE
`joinOptimizeEnabled` causes build failures with `ClassCastException`

### ISSUE THREAD

**Issue by ted-jenks** [oap-project/gluten#3632]
### Backend

VL (Velox)

### Bug description

I have tried setting `joinOptimizeEnabled` so that Gluten falls back to vanilla Spark for stages with many joins as per the recommendation on [this issue about TPC-DS q72 performance](https://github.com/oap-project/gluten/issues/1775#issuecomment-1563886600). However this caused build to fail with:
```
class org.apache.spark.sql.execution.ColumnarBuildSideRelation cannot be cast to class org.apache.spark.sql.execution.joins.HashedRelation
```
The goal is to improve the general performance of Gluten over queries of many different types.

Full stacktrace:
```
Caused by: org.apache.spark.SparkException: Job aborted.
	at org.apache.spark.sql.errors.QueryExecutionErrors$.jobAbortedError(QueryExecutionErrors.scala:496)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:251)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:186)
	at org.apache.spark.sql.execution.datasources.DataSource.writeAndRead(DataSource.scala:540)
	at org.apache.spark.sql.execution.command.CreateDataSourceTableAsSelectCommand.saveDataIntoTable(createDataSourceTables.scala:228)
	at org.apache.spark.sql.execution.command.CreateDataSourceTableAsSelectCommand.run(createDataSourceTables.scala:182)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:113)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:111)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.executeCollect(commands.scala:125)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:110)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:110)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:106)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:483)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:483)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:459)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:106)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:93)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:91)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:128)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:848)
	at org.apache.spark.sql.DataFrameWriter.createTable(DataFrameWriter.scala:689)
	at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:667)
	at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:565)
	... 41 more
Caused by: java.lang.ClassCastException: class org.apache.spark.sql.execution.ColumnarBuildSideRelation cannot be cast to class org.apache.spark.sql.execution.joins.HashedRelation (org.apache.spark.sql.execution.ColumnarBuildSideRelation and org.apache.spark.sql.execution.joins.HashedRelation are in unnamed module of loader 'app')
	at org.apache.spark.sql.execution.joins.BroadcastHashJoinExec.prepareRelation(BroadcastHashJoinExec.scala:219)
	at org.apache.spark.sql.execution.joins.HashJoin.codegenInner(HashJoin.scala:390)
	at org.apache.spark.sql.execution.joins.HashJoin.codegenInner$(HashJoin.scala:389)
	at org.apache.spark.sql.execution.joins.BroadcastHashJoinExec.codegenInner(BroadcastHashJoinExec.scala:40)
	at org.apache.spark.sql.execution.joins.HashJoin.doConsume(HashJoin.scala:356)
	at org.apache.spark.sql.execution.joins.HashJoin.doConsume$(HashJoin.scala:354)
```

### Spark version

Spark-3.2.x

### Spark configurations

```
spark.sql.join.preferSortMergeJoin: false
spark.gluten.sql.native.bloomFilter: true
spark.gluten.sql.columnar.joinOptimizationLevel: 18
spark.gluten.sql.columnar.physicalJoinOptimizeEnable: true
spark.gluten.sql.columnar.physicalJoinOptimizationLevel: 18
spark.gluten.sql.columnar.logicalJoinOptimizeEnable: true
spark.gluten.sql.columnar.logicalJoinOptimizationLevel: 18    
spark.gluten.sql.columnar.shuffle.writeEOS: false
spark.gluten.loadLibFromJar: true
spark.plugins: io.glutenproject.GlutenPlugin
spark.shuffle.manager: org.apache.spark.shuffle.sort.ColumnarShuffleManager
spark.gluten.sql.columnar.backend.lib: velox
spark.memory.offHeap.enabled: true
spark.memory.offHeap.size: 15g
spark.executor.memory: 13g
spark.executor.memoryOverhead: 2g
spark.executor.cores: 2
spark.driver.cores: 1
spark.dynamicAllocation.maxExecutors: 16
spark.executor.instances: 16
```

### System information

K8s. Our hosts are r6id.8xlarge (multiple instances). From AWS that gives us:

```
vCpu: 32
CPU: 16
Memory: 256 GiB
Memory per vCPU: 8.0 GiB
Storage: 1900GB NVMe SSD
Network Bandwidth: 12.5 Gbps
EBS Bandwidth: 10Gbps // this is our read/write
EBS Throughput: 1250 MB/s
Max IO operations per second: 40000
```

From kubectyl describe node $NODE_NAME

```
System Info:
  Machine ID:                                   ...
  System UUID:                                  ...
  Boot ID:                                      ...
  Kernel Version:                               5.4.0-1109-aws
  OS Image:                                     Ubuntu 20.04.6 LTS
  Operating System:                             linux
  Architecture:                                 amd64
  Container Runtime Version:                    containerd://1.6.12
  Kubelet Version:                              v1.25.1301
  Kube-Proxy Version:                           v1.25.1301
```

**Comment by ted-jenks** [comment]
I think based on the error, it looks like the fallback happens at the wrong time. There is already a gluten'y looking relation class and then spark is expecting a HashedJoinRelation instead.

**Comment by PHILO-HE** [comment]
As you suspected, this issue comes from wrongly using gluten's ColumnarBroadcastExchange for vanilla spark's BroadcastHashJoinExec. We have a few patches for such issue, but may not cover all cases. Also see https://github.com/oap-project/gluten/issues/2699.

**Comment by PHILO-HE** [comment]
We'll try to reproduce this issue internally. Thanks for your feedback!

**Comment by ted-jenks** [comment]
I haven't tried on 1.1 yet but will tomorrow morning, will let you know!

**Comment by ted-jenks** [comment]
Confirmed working on 1.1 so closing out, thanks for the help!

**Comment by fuuuyuuu** [comment]
> Hi @ted-jenks, sorry for this late reply. Which gluten version are you using? Maybe, you can try again with the latest release: Gluten 1.1.0. If this issue still exists, could you share your workload with us to reproduce? I'm assuming this issue is not found in TPC-DS test.

Hi @PHILO-HE,  I found that running the query blow still came into the same question, although based on Gluten 1.1.1.
The query is a variant of tpc-ds q61, could you please give some suggestions?
```
select promotions,total,cast(promotions as decimal(15,4))/cast(total as decimal(15,4))*100
from
    (
        select 
            (
            select sum(ss_ext_sales_price) promotions
            from  store_sales
                    ,store
                    ,promotion
                    ,date_dim
                    ,customer
                    ,customer_address 
                    ,item
            where ss_sold_date_sk = d_date_sk
            and   ss_store_sk = s_store_sk
            and   ss_promo_sk = p_promo_sk
            and   ss_customer_sk= c_customer_sk
            and   ca_address_sk = c_current_addr_sk
            and   ss_item_sk = i_item_sk 
            and   ca_gmt_offset = -5
            and   i_category = 'Jewelry'
            and   (p_channel_dmail = 'Y' or p_channel_email = 'Y' or p_channel_tv = 'Y')
            and   s_gmt_offset = -5
            and   d_year = 1998
            and   d_moy  = 11
            ) promotions,
            (
                select sum(ss_ext_sales_price) total
                from  store_sales
                        ,store
                        ,date_dim
                        ,customer
                        ,customer_address
                        ,item
                where ss_sold_date_sk = d_date_sk
                and   ss_store_sk = s_store_sk
                and   ss_customer_sk= c_customer_sk
                and   ca_address_sk = c_current_addr_sk
                and   ss_item_sk = i_item_sk
                and   ca_gmt_offset = -5
                and   i_category = 'Jewelry'
                and   s_gmt_offset = -5
                and   d_year = 1998
                and   d_moy  = 11
            ) total
    ) MergedScalarSubqueries
order by promotions, total
limit 100;
```
