### ISSUE TITLE
[CH] EmptyRDD: EmptyRDD created

### ISSUE THREAD

**Issue by zhanglistar** [oap-project/gluten#4330]
SQL: d_679_0
Fallback node:
<img width="1272" alt="image" src="https://github.com/oap-project/gluten/assets/985418/ba5b9c7d-c53a-4bf9-a299-d5542c5c3591">

LOG:
```
24/01/09 11:34:53,720 DEBUG [main] ColumnarOverrideRules: finalColumnarTransitions afterOverriden plan:
RowToCHNativeColumnar
+- LocalTableScan <empty>, [op_area#30, country#31, get_diamonds#32L, consume_diamonds#33L, get_uv#34L, consume_uv#35L, day#36]

24/01/09 11:34:53,721 DEBUG [main] ColumnarOverrideRules: finalTransform SparkPlan took: 2 ms.
24/01/09 11:34:53,730 INFO [main] EmptyRDD: EmptyRDD created
java.lang.Exception: EmptyRDD
        at org.apache.spark.rdd.EmptyRDD.<init>(EmptyRDD.scala:30) ~[spark-core_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.SparkContext.emptyRDD(SparkContext.scala:1449) ~[spark-core_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.LocalTableScanExec.rdd$lzycompute(LocalTableScanExec.scala:50) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.LocalTableScanExec.rdd(LocalTableScanExec.scala:48) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.LocalTableScanExec.doExecute(LocalTableScanExec.scala:60) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:194) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151) ~[spark-core_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:190) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.RowToCHNativeColumnarExec.doExecuteColumnarInternal(RowToCHNativeColumnarExec.scala:50) ~[gluten-1.2.0-SNAPSH
OT-spark-3.3-jar-with-dependencies.jar:3.3.2]
        at io.glutenproject.execution.RowToColumnarExecBase.doExecuteColumnar(RowToColumnarExecBase.scala:61) ~[gluten-1.2.0-SNAPSHOT-spark-3.3-jar-wit
h-dependencies.jar:?]
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:221) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151) ~[spark-core_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:217) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$doExecuteColumnar$1(AdaptiveSparkPlanExec.scala:364) ~[spark-sql_2.12
-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.withFinalPlanUpdate(AdaptiveSparkPlanExec.scala:376) ~[spark-sql_2.12-3.3.2.ja
r:3.3.2]
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.doExecuteColumnar(AdaptiveSparkPlanExec.scala:364) ~[spark-sql_2.12-3.3.2.jar:
3.3.2]
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:221) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151) ~[spark-core_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:217) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.datasources.FakeRowAdaptor.doExecuteColumnar(GlutenWriterColumnarRules.scala:69) ~[gluten-1.2.0-SNAPSHOT-spar
k-3.3-jar-with-dependencies.jar:?]
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:221) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151) ~[spark-core_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:217) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.InputAdapter.doExecuteColumnar(WholeStageCodegenExec.scala:521) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:221) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151) ~[spark-core_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:217) ~[spark-sql_2.12-3.3.2.jar:3.3.2]
        at io.glutenproject.execution.TransformSupport.getColumnarInputRDDs(WholeStageTransformer.scala:81) ~[gluten-1.2.0-SNAPSHOT-spark-3.3-jar-with-
dependencies.jar:?]
        at io.glutenproject.execution.TransformSupport.getColumnarInputRDDs$(WholeStageTransformer.scala:76) ~[gluten-1.2.0-SNAPSHOT-spark-3.3-jar-with
-dependencies.jar:?]
        at org.apache.spark.sql.execution.InputIteratorTransformer.getColumnarInputRDDs(ColumnarCollapseTransformStages.scala:41) ~[gluten-1.2.0-SNAPSH
OT-spark-3.3-jar-with-dependencies.jar:3.3.2]
        at io.glutenproject.execution.UnaryTransformSupport.columnarInputRDDs(WholeStageTransformer.scala:92) ~[gluten-1.2.0-SNAPSHOT-spark-3.3-jar-wit
h-dependencies.jar:?]
        at io.glutenproject.execution.UnaryTransformSupport.columnarInputRDDs$(WholeStageTransformer.scala:91) ~[gluten-1.2.0-SNAPSHOT-spark-3.3-jar-wi
th-dependencies.jar:?]
        at org.apache.spark.sql.execution.InputIteratorTransformer.columnarInputRDDs(ColumnarCollapseTransformStages.scala:41) ~[gluten-1.2.0-SNAPSHOT-
spark-3.3-jar-with-dependencies.jar:3.3.2]
        at io.glutenproject.execution.TransformSupport.getColumnarInputRDDs(WholeStageTransformer.scala:79) ~[gluten-1.2.0-SNAPSHOT-spark-3.3-jar-with-
dependencies.jar:?]
        at io.glutenproject.execution.TransformSupport.getColumnarInputRDDs$(WholeStageTransformer.scala:76) ~[gluten-1.2.0-SNAPSHOT-spark-3.3-jar-with
-dependencies.jar:?]
```

**Comment by zhanglistar** [comment]
Due empty result, spark finishes job early.
