### ISSUE TITLE
【VL】UnsupportedOperationException occurs with celeborn

### ISSUE THREAD

**Issue by hailiang9615** [oap-project/gluten#4370]
### Backend

VL (Velox)

### Bug description

```
24/01/11 11:37:48 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0) (10.4.163.5 executor 1): java.lang.UnsupportedOperationException
	at org.apache.spark.shuffle.CelebornColumnarBatchSerializerInstance.serializeStream(VeloxCelebornColumnarBatchSerializer.scala:223)
	at org.apache.spark.shuffle.celeborn.HashBasedShuffleWriter.<init>(HashBasedShuffleWriter.java:147)
	at org.apache.spark.shuffle.celeborn.SparkShuffleManager.getWriter(SparkShuffleManager.java:217)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:57)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

24/01/11 11:37:48 ERROR TaskSetManager: Task 0 in stage 0.0 failed 4 times; aborting job
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 6) (10.4.163.5 executor 1): java.lang.UnsupportedOperationException
	at org.apache.spark.shuffle.CelebornColumnarBatchSerializerInstance.serializeStream(VeloxCelebornColumnarBatchSerializer.scala:223)
	at org.apache.spark.shuffle.celeborn.HashBasedShuffleWriter.<init>(HashBasedShuffleWriter.java:147)
	at org.apache.spark.shuffle.celeborn.SparkShuffleManager.getWriter(SparkShuffleManager.java:217)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:57)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2672)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2608)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2607)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2607)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1182)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1182)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1182)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2860)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2802)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2791)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
Caused by: java.lang.UnsupportedOperationException
	at org.apache.spark.shuffle.CelebornColumnarBatchSerializerInstance.serializeStream(VeloxCelebornColumnarBatchSerializer.scala:223)
	at org.apache.spark.shuffle.celeborn.HashBasedShuffleWriter.<init>(HashBasedShuffleWriter.java:147)
	at org.apache.spark.shuffle.celeborn.SparkShuffleManager.getWriter(SparkShuffleManager.java:217)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:57)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

### Spark version

Spark-3.3.x

### Spark configurations

 --conf spark.shuffle.manager=org.apache.spark.shuffle.celeborn.SparkShuffleManager
--conf spark.shuffle.service.enabled=false
--conf spark.serializer=org.apache.spark.serializer.KryoSerializer
--conf spark.shuffle.service.enabled=false
--conf spark.celeborn.client.spark.shuffle.writer=hash
--conf spark.celeborn.client.push.replicate.enabled=false
--conf spark.sql.adaptive.localShuffleReader.enabled=false

### System information

centos 7

**Comment by hailiang9615** [comment]
An exception occurs when using celeborn shuffle: CelebornColumnarBatchSerializer.serializeStream is found to be unimplemented, and the exception is thrown directly. It's strange why here didn't go to the celebornCelebornColumnarBatchSerializer class....
![image](https://github.com/oap-project/gluten/assets/56329371/74ebf575-9a32-4148-9181-5076d41c95f0)

**Comment by hailiang9615** [comment]
Is there an error in the configuration of Celeborn? Or is there some problem where? The following is the environment configuration for a single-node test
![image](https://github.com/oap-project/gluten/assets/56329371/f80310b4-aa5f-4e81-ae30-eb6acb932112)

**Comment by RaoZhiRou-Z** [comment]
I have the same error but I use the  org.apache.spark.shuffle.sort.ColumnarShuffleManager
how did you solved this error

**Comment by RaoZhiRou-Z** [comment]
@hailiang9615

**Comment by RaoZhiRou-Z** [comment]
@hailiang9615 
I have the same error but I use the org.apache.spark.shuffle.sort.ColumnarShuffleManager
how did you solved this error

**Comment by ArnavBalyan** [comment]
Getting the same error, what was the resolution here, cc @hailiang9615 @RaoZhiRou-Z

**Comment by RaoZhiRou-Z** [comment]
> Getting the same error, what was the resolution here, cc @hailiang9615 @RaoZhiRou-Z

the reason is  i use the config  "spark.executor.userClassPathFirst" and I modify the spark source code to deal with it
