### ISSUE TITLE
NoSuchMethodError: ArrowType$Decimal.<init>(III)V for TPC-H Q1

### ISSUE THREAD

**Issue by estoianovici** [oap-project/gluten#4698]
### Backend

VL (Velox)

### Bug description

TPC-H Q1 throws NoSuchMethodError with the following callstack:
`java.lang.NoSuchMethodError: io.glutenproject.shaded.org.apache.arrow.vector.types.pojo.ArrowType$Decimal.<init>(III)V
	at org.apache.spark.sql.utils.SparkArrowUtil$.toArrowType(SparkArrowUtil.scala:41)
	at org.apache.spark.sql.utils.SparkArrowUtil$.toArrowField(SparkArrowUtil.scala:111)
	at org.apache.spark.sql.utils.SparkArrowUtil$.$anonfun$toArrowSchema$1(SparkArrowUtil.scala:141)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at org.apache.spark.sql.types.StructType.foreach(StructType.scala:105)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at org.apache.spark.sql.types.StructType.map(StructType.scala:105)
	at org.apache.spark.sql.utils.SparkArrowUtil$.toArrowSchema(SparkArrowUtil.scala:140)
	at io.glutenproject.execution.RowToVeloxColumnarExec$.toColumnarBatchIterator(RowToVeloxColumnarExec.scala:121)
	at io.glutenproject.execution.RowToVeloxColumnarExec.$anonfun$doExecuteColumnarInternal$2(RowToVeloxColumnarExec.scala:72)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:853)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:853)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at io.glutenproject.execution.ColumnarInputRDDsWrapper.$anonfun$getIterators$1(WholeStageTransformer.scala:443)
	at scala.collection.immutable.List.flatMap(List.scala:366)
	at io.glutenproject.execution.ColumnarInputRDDsWrapper.getIterators(WholeStageTransformer.scala:434)
	at io.glutenproject.execution.WholeStageZippedPartitionsRDD.$anonfun$compute$1(WholeStageZippedPartitionsRDD.scala:48)
	at io.glutenproject.utils.Arm$.withResource(Arm.scala:25)
	at io.glutenproject.metrics.GlutenTimeMetric$.millis(GlutenTimeMetric.scala:37)
	at io.glutenproject.execution.WholeStageZippedPartitionsRDD.compute(WholeStageZippedPartitionsRDD.scala:46)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)`

Setup:
Gluten SHA: cdf1725ea56f20643cb5800b3b45fc46c856e38b - version 1.2.0-SNAPSHOT with Velox backend

### Spark version

None

### Spark configurations

Spark 3.4.2

**Comment by estoianovici** [comment]
This can be closed just like #4701. The issue is not in gluten.
