### ISSUE TITLE
TPC-DS q2 throws java.lang.NoSuchMethodError: io.glutenproject.shaded.org.apache.arrow.memory.BufferAllocator.buffer(J)Lio/glutenproject/shaded/org/apache/arrow/memory/ArrowBuf;

### ISSUE THREAD

**Issue by estoianovici** [oap-project/gluten#4701]
### Backend

VL (Velox)

### Stack trace:
```
Caused by: java.lang.NoSuchMethodError: 
io.glutenproject.shaded.org.apache.arrow.memory.BufferAllocator.buffer(J)Lio/glutenproject/shaded/org/apache/arrow/memory/ArrowBuf;
        at org.apache.arrow.c.ArrowSchema.allocateNew(ArrowSchema.java:111)
        at io.glutenproject.execution.RowToVeloxColumnarExec$.toColumnarBatchIterator(RowToVeloxColumnarExec.scala:125)
        at io.glutenproject.execution.RowToVeloxColumnarExec.$anonfun$doExecuteColumnarInternal$2(RowToVeloxColumnarExec.scala:72)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:853)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:853)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:92)
        at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
        at org.apache.spark.scheduler.Task.run(Task.scala:141)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:563)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1541)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:566)
        ... 3 more
```
### Driver stacktrace:
```
Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2974)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2910)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2909)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2909)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1263)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1263)
        at scala.Option.foreach(Option.scala:407)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1263)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3173)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3112)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3101)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1028)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2271)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2292)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2311)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2336)
        at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1019)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:405)
        at org.apache.spark.rdd.RDD.collect(RDD.scala:1018)
        at io.glutenproject.backendsapi.velox.SparkPlanExecApiImpl.createBroadcastRelation(SparkPlanExecApiImpl.scala:350)
        at org.apache.spark.sql.execution.ColumnarBroadcastExchangeExec.$anonfun$relationFuture$2(ColumnarBroadcastExchangeExec.scala:79)
        at io.glutenproject.utils.Arm$.withResource(Arm.scala:25)
        at io.glutenproject.metrics.GlutenTimeMetric$.millis(GlutenTimeMetric.scala:37)
        at org.apache.spark.sql.execution.ColumnarBroadcastExchangeExec.$anonfun$relationFuture$1(ColumnarBroadcastExchangeExec.scala:69)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withThreadLocalCaptured$1(SQLExecution.scala:293)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more
```

### Spark version

None

### Spark configurations

Spark version 3.4.1
Configuration:
```
 --conf spark.plugins=io.glutenproject.GlutenPlugin
 --conf spark.memory.offHeap.enabled=true
 --conf spark.memory.offHeap.size=2g
 --conf spark.shuffle.manager=org.apache.spark.shuffle.sort.ColumnarShuffleManager
 --conf spark.executor.memory=4g
 --conf spark.sql.adaptive.enabled=false
```

### System information

```
Velox System Info v0.0.2
Commit: bf4085d21a186b810ac045e5d2e60ca320df503a
CMake Version: 3.25.1
System: Linux-5.10.209-175.812.amzn2int.x86_64
Arch: x86_64
C++ Compiler: /opt/rh/devtoolset-11/root/usr/bin/c++
C++ Compiler Version: 11.2.1
C Compiler: /opt/rh/devtoolset-11/root/usr/bin/cc
C Compiler Version: 11.2.1
CMake Prefix Path: /usr/local;/usr;/;/usr/local;/usr/local;/usr/X11R6;/usr/pkg;/opt
```

**Comment by zhouyuan** [comment]
Hi @estoianovici
 
Thanks for reporting, it looks due to some Jar conflict issue: 
https://github.com/oap-project/gluten/blob/main/docs/velox-backend-troubleshooting.md#jar-conflict-issue

Would you please share what is the cluster mode in your test? Ideally Spark should pick the binary in Gluten package first, if configurated properly.
https://github.com/oap-project/gluten/blob/main/docs/velox-backend-troubleshooting.md#configurations-for-yarn-client-mode 

The root case maybe the same as in https://github.com/oap-project/gluten/issues/4698 

Thanks, 
-yuan

**Comment by estoianovici** [comment]
Thank you for getting back to me, @zhouyuan. I replaced the arrow jars manually on all the nodes, but I'm running into the same issue. These are the arrow jars I've copied to the cluster
```
$ ls /usr/lib/spark/jars/|grep arrow
-rw-r--r-- 1 root root  574K Feb 20 01:02 arrow-c-data-14.0.1.jar
-rw-r--r-- 1 root root  107K Feb 20 01:02 arrow-format-14.0.1.jar
-rw-r--r-- 1 root root  108K Feb 20 01:02 arrow-memory-core-14.0.1.jar
-rw-r--r-- 1 root root   38K Feb 20 01:02 arrow-memory-netty-14.0.1.jar
-rw-r--r-- 1 root root   10K Feb 20 01:02 arrow-memory-unsafe-14.0.1.jar
-rw-r--r-- 1 root root  1.9M Feb 20 01:02 arrow-vector-14.0.1.jar
-rw-r--r-- 1 root root  2.1M Feb 20 01:02 arrow-vector-14.0.1-shade-format-flatbuffers.jar
```



I've tried the 1.1.0 release too:
```
$./dev/info.sh 

Velox System Info v0.0.2
Commit: cce55960a78c7c3b654b3ac0b2a808791bc6c6ee
CMake Version: 3.25.1
System: Linux-5.10.209-175.812.amzn2int.x86_64
Arch: x86_64
C++ Compiler: /opt/rh/devtoolset-11/root/usr/bin/c++
C++ Compiler Version: 11.2.1
C Compiler: /opt/rh/devtoolset-11/root/usr/bin/cc
C Compiler Version: 11.2.1
CMake Prefix Path: /usr/local;/usr;/;/usr/local;/usr/local;/usr/X11R6;/usr/pkg;/opt
```

and I'm getting the same error

**Comment by estoianovici** [comment]
Sorry for the noise, this can be closed. The issue exists in my build, one of the dependencies in my project eventually relies on an older version of arrow-vector which gets bundled with the gluten jar and overwrites the required version.

If anyone runs into this issue, `mvn dependency:tree` will show all the dependencies built into the gluten jar. To exclude a specific version, you can add and exclusion to the dependency management. E.g., this excludes 
```
<dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-sql_${scala.binary.version}</artifactId>
        <version>${spark.version}</version>
        <scope>provided</scope>
        <exclusions>
          <exclusion>
            <groupId>org.apache.arrow</groupId>
            <artifactId>arrow-vector</artifactId>
          </exclusion>
...
        </exclusions>
```

This excludes the arrow-vector version on which spark-sql relies on and replaces it with the one specified by the gluten pom
