### ISSUE TITLE
Unhandled exception for missing velox file type causes worker to generate obscure core dump

### ISSUE THREAD

**Issue by estoianovici** [oap-project/gluten#528]
**Describe the bug**
the velox code throws a c++ exception when the file type is not recognised. This exception should be caught somewhere (maybe gluten::GlutenResultIterator::HasNext ?) and reported as an error upstream. Otherwise the worker just cores.

The coredump:

```
#3  0x00007f6f5d41a476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f6f5d4007f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007f6eb26116b2 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f6eb261c8df in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f6eb261ca07 in __gxx_personality_v0 () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007f6ea7e01fe9 in __libunwind_Unwind_Resume () from /lib/x86_64-linux-gnu/libunwind.so.8
#9  0x00007f6ea931b1d8 in __gnu_cxx::new_allocator<char>::~new_allocator (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/11/ext/new_allocator.h:89
#10 std::allocator<char>::~allocator (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/11/bits/allocator.h:174
#11 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Alloc_hider::~_Alloc_hider (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/11/bits/basic_string.h:158
#12 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/11/bits/basic_string.h:672
#13 facebook::velox::filesystems::getFileSystem (filename=..., properties=std::shared_ptr<const facebook::velox::Config> (use count 6, weak count 0) = {...}) at /home/ubuntu/gluten/tools/build/velox_ep/velox/common/file/FileSystems.cpp:60
#14 0x00007f6eaa326e19 in facebook::velox::FileHandleGenerator::operator() (this=0x7f6ed0c20a80, filename="s3a://cluster_name/warehouse/tpcds/store_returns/sr_returned_date_sk=2452332/part-00024-99d08db4-6c4d-4643-b353-d5e5392005b4.c000.snappy.parquet")
    at /home/ubuntu/gluten/tools/build/velox_ep/velox/connectors/hive/FileHandle.cpp:42
#15 0x00007f6eaa325f52 in facebook::velox::CachedFactory<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, facebook::velox::FileHandle, facebook::velox::FileHandleGenerator, facebook::velox::FileHandleSizer, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::generate (this=0x7f6ed0a8a588, 
    key="s3a://eusto-my-cluster1/warehouse/tpcds_spark_10.db/store_returns/sr_returned_date_sk=2452332/part-00024-99d08db4-6c4d-4643-b353-d5e5392005b4.c000.snappy.parquet") at /usr/include/c++/11/bits/unique_ptr.h:173
#16 0x00007f6eaa31c4f1 in facebook::velox::connector::hive::HiveDataSource::addSplit (this=0x7f6ee8004700, split=...) at /home/ubuntu/gluten/tools/build/velox_ep/velox/connectors/hive/HiveConnector.cpp:385
#17 0x00007f6ea9a454b0 in facebook::velox::exec::TableScan::getOutput (this=0x7f6edc2f5590) at /home/ubuntu/gluten/tools/build/velox_ep/velox/exec/TableScan.cpp:98
#18 0x00007f6ea99dd170 in facebook::velox::exec::Driver::runInternal (this=0x7f6eec33f510, self=std::shared_ptr<facebook::velox::exec::Driver> (use count 2, weak count 1) = {...}, blockingState=std::shared_ptr<facebook::velox::exec::BlockingState> (empty) = {...}, 
    result=std::shared_ptr<facebook::velox::RowVector> (empty) = {...}) at /home/ubuntu/gluten/tools/build/velox_ep/velox/exec/Driver.cpp:352
#19 0x00007f6ea99dda3b in facebook::velox::exec::Driver::next (this=0x7f6eec33f510, blockingState=std::shared_ptr<facebook::velox::exec::BlockingState> (empty) = {...}) at /home/ubuntu/gluten/tools/build/velox_ep/velox/exec/Driver.cpp:236
#20 0x00007f6ea99c8300 in facebook::velox::exec::Task::next (this=0x7f6eec329a30) at /usr/include/c++/11/bits/shared_ptr_base.h:1295
#21 0x00007f6ea9330d04 in velox::compute::WholeStageResIter::Next (this=0x7f6eec332c10) at /usr/include/c++/11/bits/shared_ptr_base.h:1295
#22 0x00007f6ea933b93c in gluten::GlutenResultIterator::Wrapper<velox::compute::VeloxPlanConverter::WholeStageResIterFirstStage>::Next (this=<optimized out>) at /home/ubuntu/gluten/cpp/src/compute/exec_backend.h:315
#23 arrow::Iterator<std::shared_ptr<gluten::memory::GlutenColumnarBatch> >::Next<gluten::GlutenResultIterator::Wrapper<velox::compute::VeloxPlanConverter::WholeStageResIterFirstStage> > (ptr=<optimized out>)
    at /home/ubuntu/gluten/cpp/build/releases/include/arrow/util/iterator.h:200
#24 0x00007f6ea933b506 in arrow::Iterator<std::shared_ptr<gluten::memory::GlutenColumnarBatch> >::Next (this=<optimized out>) at /home/ubuntu/gluten/cpp/build/releases/include/arrow/util/iterator.h:110
#25 gluten::GlutenResultIterator::GetNext (this=this@entry=0x7f6eec3378a0) at /home/ubuntu/gluten/cpp/src/compute/exec_backend.h:337
#26 0x00007f6ea933b83b in gluten::GlutenResultIterator::HasNext (this=0x7f6eec3378a0) at /home/ubuntu/gluten/cpp/src/compute/exec_backend.h:264
#27 0x00007f6eabbaa395 in Java_io_glutenproject_vectorized_ArrowOutIterator_nativeHasNext (env=0x7f6ed0a05260, obj=<optimized out>, id=<optimized out>) at /home/ubuntu/gluten/cpp/src/jni/jni_wrapper.cc:450
#28 0x00007f6f48418427 in ?? ()
#29 0x0000000000000000 in ?? ()
```

**To Reproduce**
Try to access an S3 parquet file through gluten+velox.

**Expected behavior**
A nicer error should be returned to the user rather than the crash. The crash cannot be investigated without rebuilding everything with debug symbols.

**Comment by estoianovici** [comment]
This is the code that throws:

```
|       51  std::shared_ptr<FileSystem> getFileSystem(                                                                                                                                                                                                                       │
│       52      std::string_view filename,                                                                                                                                                                                                                                   │
│       53      std::shared_ptr<const Config> properties) {                                                                                                                                                                                                                  │
│       54    const auto& filesystems = registeredFileSystems();                                                                                                                                                                                                             │
│       55    for (const auto& p : filesystems) {                                                                                                                                                                                                                            │
│       56      if (p.first(filename)) {                                                                                                                                                                                                                                     │
│       57        return p.second(properties);                                                                                                                                                                                                                               │
│       58      }                                                                                                                                                                                                                                                            │
│       59    }                                                                                                                                                                                                                                                              │
│  >    60    VELOX_FAIL("No registered file system matched with filename '{}'", filename);                                                                                                                                                                                  │
│       61  }    
```

**Comment by FelixYBW** [comment]
@zhouyuan  Can this be part of the data source validation?

**Comment by zhouyuan** [comment]
@estoianovici 
Hi, thanks for reporting!
I assume you are trying the WIP patch on #491 (?)
based on the info you provide in https://github.com/oap-project/gluten/issues/484, it seems gluten s3 is not able to read any data and velox timeout when reading there. indeed the "timeout" is not handled well right now.

the issue is most likely due to some wrong configurations used in S3 filesystem registration
https://github.com/oap-project/gluten/pull/491/files#diff-975304e9bcc8f4218711827300c70cf56fb33d9663650fcccbdbfdf37d812b18R103-R124
I'll look into this and try to setup real S3 to do more checks

**Comment by estoianovici** [comment]
Yes, I was using that patch. Once the S3 access is sorted, the code seems to work. It's just that I was expecting an error rather than a full blown coredump

**Comment by jinchengchenghh** [comment]
Seems like duplicate problems with https://github.com/oap-project/gluten/issues/539
