### ISSUE TITLE
An unsupportedOperationException interrupted the query execution

### ISSUE THREAD

**Issue by PHILO-HE** [oap-project/gluten#560]
**Describe the bug**

In testing the below query, we found that for
```
SELECT col_1322, col_1262, col_1218, str_162, col_1313, Sum(str_155) AS str_155, Sum(str_164)  AS str_164 FROM (SELECT col_1322, col_1262, col_1218, explode(split(col_752, '#')) AS str_162, col_1313, IF(col_1175=3, 1, 0) as str_155, IF(col_1175=2, 1, 0) AS str_164 FROM table_0 t1 WHERE (col_1114='20220307' and col_1043='23'  AND col_1175 IN (2, 3) AND (cast(col_1313 AS int)&8>0 or col_1313=0) AND (col_1009=25 OR  col_1322 IN (628, 585, 706, 640, 719, 814)))) GROUP BY col_1322, col_1262, col_1218, str_162, col_1313 UNION ALL SELECT col_1322,  col_1262, col_1218,  'all' AS str_162, col_1313, sum(IF(col_1175=3, 1, 0)) AS str_155, sum(IF(col_1175=2, 1, 0)) AS str_164 FROM table_0 t1 WHERE (col_1114='20220307' and col_1043='23' AND col_1175 IN (2, 3) AND (cast(col_1313 AS int)&8 > 0 or col_1313=0) AND ( col_1009=25 OR col_1322 IN (628, 585, 706, 640, 719, 814))) GROUP BY col_1322, col_1262, col_1218, col_1313;
```
we got the below exception interrupted the execution.
```
java.lang.UnsupportedOperationException: Not supported: BitwiseAnd.
        at io.glutenproject.expression.BitwiseAndTransformer.doTransform(ArithmeticTransformer.scala:154)
        at io.glutenproject.expression.GreaterThanTransformer.doTransform(BinaryOperatorTransformer.scala:179)
        at io.glutenproject.expression.OrTransformer.doTransform(BinaryOperatorTransformer.scala:61)
        at io.glutenproject.expression.AndTransformer.doTransform(BinaryOperatorTransformer.scala:36)
        at io.glutenproject.expression.AndTransformer.doTransform(BinaryOperatorTransformer.scala:34)
        at io.glutenproject.execution.BasicScanExecTransformer.$anonfun$doTransform$4(BasicScanExecTransformer.scala:117)
        at scala.Option.map(Option.scala:230)
        at io.glutenproject.execution.BasicScanExecTransformer.doTransform(BasicScanExecTransformer.scala:117)
        at io.glutenproject.execution.BasicScanExecTransformer.doTransform$(BasicScanExecTransformer.scala:98)
        at io.glutenproject.execution.FileSourceScanExecTransformer.doTransform(FileSourceScanExecTransformer.scala:37)
        at io.glutenproject.execution.VeloxFilterExecTransformer.doTransform(VeloxFilterExecTransformer.scala:68)

```
The expected behavior is the operator should correctly fall back for unsupported case.

**Comment by jinchengchenghh** [comment]
Can we close this issue now? @PHILO-HE

**Comment by PHILO-HE** [comment]
Yes. I am closing it. Thanks!
