### ISSUE TITLE
It won't  load the libparquet.so.1000  when we use Gluten with Velox backend and run it on the yarn.

### ISSUE THREAD

**Issue by weixiuli** [oap-project/gluten#797]
**Describe the bug**
Currently, it won't  load the libparquet.so.1000  when we use Gluten with Velox backend and run it on the yarn. 
The error log is as follows：
```
INFO ApplicationMaster: Final app status: FAILED, exitCode: 13, sparkExitCode: -6015, (reason: SparkContext not inited, check driver to determine why, possible reason:
user application exited with status 15 before SparkContext inited. am ex: User class threw exception: java.lang.UnsatisfiedLinkError: /****/tmp/spark_columnar_plugin_600222766168197802/libspark_columnar_jni.so: libparquet.so.1000: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at io.glutenproject.vectorized.JniLibLoader.loadFromPath0(JniLibLoader.java:88)
	at io.glutenproject.vectorized.JniLibLoader.access$300(JniLibLoader.java:57)
	at io.glutenproject.vectorized.JniLibLoader$JniLoadTransaction.loadWithLink(JniLibLoader.java:308)
	at io.glutenproject.vectorized.JniLibLoader$JniLoadTransaction.lambda$commit$1(JniLibLoader.java:258)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at io.glutenproject.vectorized.JniLibLoader$JniLoadTransaction.commit(JniLibLoader.java:255)
	at io.glutenproject.vectorized.JniLibLoader.mapAndLoad(JniLibLoader.java:109)
	at io.glutenproject.backendsapi.velox.VeloxInitializerApi.initialize(VeloxInitializerApi.scala:41)
	at io.glutenproject.GlutenDriverPlugin.init(GlutenPlugin.scala:52)
	at org.apache.spark.internal.plugin.DriverPluginContainer.$anonfun$driverPlugins$1(PluginContainer.scala:53)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at org.apache.spark.internal.plugin.DriverPluginContainer.<init>(PluginContainer.scala:46)
	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:210)
	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:193)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:611)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2817)
	at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:1036)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:1030)
	at com.bytedance.tpcds.SparkTaskDriver$.runPowerTest(SparkTaskDriver.scala:179)
	at com.bytedance.tpcds.SparkTaskDriver$.run(SparkTaskDriver.scala:198)
	at com.bytedance.tpcds.SparkTaskDriver$.main(SparkTaskDriver.scala:42)
	at com.bytedance.tpcds.SparkTaskDriver.main(SparkTaskDriver.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:773)

Following is the stacktrace of Driver thread the moment SparkContext initialization timed out:
	at java.lang.Thread.getStackTrace(Thread.java:1559)
	at org.apache.spark.deploy.yarn.ApplicationMaster.finish(ApplicationMaster.scala:415)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:790)
```
**To Reproduce**
Use Gluten with Velox backend and run it on the yarn.

**Comment by j-buczak** [comment]
I had the same issue, but on Spark-standalone. I think it's connected to minimal runtime setup - I created an [issue for this](https://github.com/oap-project/gluten/issues/748). I solve this particular issue by running Gluten in the same environment I build it, but it produces huuge images (~13BG)

**Comment by zhejiangxiaomai** [comment]
https://github.com/oap-project/gluten/pull/798 fix this problem.
