### ISSUE TITLE
This operator doesn't support doExecuteColumnar

### ISSUE THREAD

**Issue by j-buczak** [oap-project/gluten#799]
**Describe the bug**
Using Spark-standalone with s3 (MinIO) using data in Parquet format.

This bug shows during TPC-H data generation. 

```
ERROR FileFormatWriter: Aborting job 61ee6b0c-e13f-4d61-9a9b-d4e51ff005c1.
java.lang.UnsupportedOperationException: This operator doesn't support doExecuteColumnar().
        at io.glutenproject.execution.ProjectExecTransformer.doExecuteColumnar(BasicPhysicalOperatorTransformer.scala:461)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:221)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229)
        at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:217)
        at org.apache.spark.sql.execution.GlutenColumnarToRowExec.doExecuteInternal(GlutenColumnarToRowExec.scala:108)
        at io.glutenproject.execution.GlutenColumnarToRowExecBase.doExecute(GlutenColumnarToRowExecBase.scala:50)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:194)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:190)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:213)
        at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:186)
        at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:113)
        at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:111)
        at org.apache.spark.sql.execution.command.DataWritingCommandExec.executeCollect(commands.scala:125)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:98)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:109)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:95)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:94)
        at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:584)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:176)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:584)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:560)
        at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:94)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:81)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:79)
        at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:116)
        at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:860)
        at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:390)
        at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:363)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:239)
        at com.databricks.spark.sql.perf.Tables$Table.genData(Tables.scala:242)
        at com.databricks.spark.sql.perf.Tables.$anonfun$genData$7(Tables.scala:310)
        at com.databricks.spark.sql.perf.Tables.$anonfun$genData$7$adapted(Tables.scala:307)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at com.databricks.spark.sql.perf.Tables.genData(Tables.scala:307)
        at com.intel.cnds.tpc.TpcSparkDataGenerator$.main(tpc_data_generator.scala:104)
        at com.intel.cnds.tpc.TpcSparkDataGenerator.main(tpc_data_generator.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:958)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by j-buczak** [comment]
# Gluten / Spark configuration
* Java 8
* Velox backend
* Scala 2.12.16
* Spark 3.3.1

## spark-defaults.conf
```
spark.cnds.totalExecutorsInCluster 2
spark.driver.defaultJavaOptions
spark.driver.extraClassPath /opt/gluten-jars/gluten-spark3.3_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar
spark.driver.extraJavaOptions -Dlog4jspark.root.logger=WARN,console
spark.driver.maxResultSize 0
spark.driver.maxResultSize 4g
spark.dynamicAllocation.enabled false
spark.executor.cores 12
spark.executor.defaultJavaOptions
spark.executor.extraClassPath /opt/gluten-jars/gluten-spark3.3_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar
spark.executor.extraJavaOptions
spark.executor.memory 61440m
spark.executor.memoryOverhead 1g
spark.executorEnv.OTEL_SERVICE_NAME spark-executor
spark.gluten.sql.columnar.backend.lib velox
spark.gluten.sql.columnar.batchscan true
spark.gluten.sql.columnar.broadcastexchange true
spark.gluten.sql.columnar.broadcastJoin true
spark.gluten.sql.columnar.codegen.sort true
spark.gluten.sql.columnar.expand true
spark.gluten.sql.columnar.forceshuffledhashjoin true
spark.gluten.sql.columnar.hashagg true
spark.gluten.sql.columnar.projfilter true
spark.gluten.sql.columnar.shuffle.customizedCompression.codec lz4
spark.gluten.sql.columnar.shuffledhashjoin true
spark.gluten.sql.columnar.shuffleSplitDefaultSize 8192
spark.gluten.sql.columnar.sort true
spark.gluten.sql.columnar.sortmergejoin true
spark.gluten.sql.columnar.union true
spark.gluten.sql.columnar.wholestagetransform false
spark.gluten.sql.columnar.window true
spark.hadoop.fs.s3a.access.key minio
spark.hadoop.fs.s3a.aws.credentials.provider org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.block.size 512M
spark.hadoop.fs.s3a.committer.abort.pending.uploads true
spark.hadoop.fs.s3a.committer.magic.enabled false
spark.hadoop.fs.s3a.committer.name directory
spark.hadoop.fs.s3a.committer.staging.conflict-mode append
spark.hadoop.fs.s3a.committer.staging.tmp.path /tmp/staging
spark.hadoop.fs.s3a.committer.staging.unique-filenames true
spark.hadoop.fs.s3a.committer.threads 2048
spark.hadoop.fs.s3a.connection.establish.timeout 5000
spark.hadoop.fs.s3a.connection.maximum 8192
spark.hadoop.fs.s3a.connection.ssl.enabled false
spark.hadoop.fs.s3a.connection.timeout 200000
spark.hadoop.fs.s3a.endpoint http://minio.jbuczak-2.svc:9000
spark.hadoop.fs.s3a.fast.upload true
spark.hadoop.fs.s3a.fast.upload.active.blocks 2048
spark.hadoop.fs.s3a.fast.upload.buffer disk
spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.max.total.tasks 2048
spark.hadoop.fs.s3a.multipart.size 512M
spark.hadoop.fs.s3a.multipart.threshold 512M
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.secret.key *****
spark.hadoop.fs.s3a.socket.recv.buffer 65536
spark.hadoop.fs.s3a.socket.send.buffer 65536
spark.hadoop.fs.s3a.threads.max 2048
spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version 2
spark.hadoop.parquet.enable.summary-metadata false
spark.history.ui.port  18080
spark.master spark://spark-master-svc.jbuczak-2.svc:7077
spark.master.rest.enabled false
spark.master.rest.port  6066
spark.memory.offHeap.enabled true
spark.memory.offHeap.size 30g
spark.plugins io.glutenproject.GlutenPlugin
spark.shuffle.manager org.apache.spark.shuffle.sort.ColumnarShuffleManager
spark.sql.autoBroadcastJoinThreshold 10M
spark.sql.broadcastTimeout 4800
spark.sql.execution.arrow.maxRecordsPerBatch 10000
spark.sql.execution.arrow.maxRecordsPerBatch 10240
spark.sql.files.maxPartitionBytes 2g
spark.sql.hive.metastore.jars path
spark.sql.hive.metastore.jars.path /opt/spark/lib/*.jar
spark.sql.hive.metastore.version 3.1.3
spark.sql.hive.metastorePartitionPruning true
spark.sql.inMemoryColumnarStorage.batchSize 32768
spark.sql.join.preferSortMergeJoin false
spark.sql.parquet.columnarReaderBatchSize 32768
spark.sql.parquet.filterPushdown true
spark.sql.parquet.mergeSchema false
spark.sql.shuffle.partitions 224
spark.sql.sources.useV1SourceList avro
spark.sql.streaming.checkpointLocation s3a://state/checkpoints
spark.sql.streaming.kafka.useDeprecatedOffsetFetching false
spark.standalone.submit.waitAppCompletion false
```

**Comment by FelixYBW** [comment]
TPCH data generator doesn't use spark SQL. You should generate data without Gluten. Let's see how we should fallback this operation

You may remove below config now.
spark.plugins io.glutenproject.GlutenPlugin
spark.shuffle.manager org.apache.spark.shuffle.sort.ColumnarShuffleManager

**Comment by j-buczak** [comment]
@FelixYBW Thanks, I setup it this way - datageneration is working without Gluten, but I still have the same error when running TPC-H queries. 

I generated data according to [tpch_datagen_parquet.scala](https://github.com/oap-project/gluten/blob/main/backends-velox/workload/tpch/gen_data/parquet_dataset/tpch_datagen_parquet.scala) with `rootDir=s3a://bucket_name/database_location`. After generation the database metadata was stored in Hive-Metastore with:

```scala
tables.createExternalTables(
    rootDir,
    "parquet",
    "s3a_tpch_sf1_parquet_gluten",
    overwrite = true,
    discoverPartitions = true)
tables.analyzeTables("s3a_tpch_sf1_parquet_gluten", analyzeColumns = true)
```

Then in new Spark shell with gluten enabled:
```scala
import scala.io.Source
val f = Source.fromFile(s"/path-to/sql-gluten/tpch/1.sql").mkString
spark.sql(s"USE s3a_tpch_sf1_parquet_gluten")
val res = spark.sql(f).show
```

Then I got 

<details>
<summary>The same error: This operator doesn't support doExecuteColumnar()</summary>

```
23/01/04 14:40:44 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
java.lang.UnsupportedOperationException: This operator doesn't support doExecuteColumnar().
  at io.glutenproject.execution.ProjectExecTransformer.doExecuteColumnar(BasicPhysicalOperatorTransformer.scala:461)
  at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:221)
  at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229)
  at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:217)
  at org.apache.spark.sql.execution.ColumnarShuffleExchangeAdaptor.inputColumnarRDD$lzycompute(ColumnarShuffleExchangeExec.scala:196)
  at org.apache.spark.sql.execution.ColumnarShuffleExchangeAdaptor.inputColumnarRDD(ColumnarShuffleExchangeExec.scala:196)
  at org.apache.spark.sql.execution.ColumnarShuffleExchangeAdaptor.mapOutputStatisticsFuture$lzycompute(ColumnarShuffleExchangeExec.scala:200)
  at org.apache.spark.sql.execution.ColumnarShuffleExchangeAdaptor.mapOutputStatisticsFuture(ColumnarShuffleExchangeExec.scala:199)
  at org.apache.spark.sql.execution.exchange.ShuffleExchangeLike.$anonfun$submitShuffleJob$1(ShuffleExchangeExec.scala:68)
  at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229)
  at org.apache.spark.sql.execution.exchange.ShuffleExchangeLike.submitShuffleJob(ShuffleExchangeExec.scala:68)
  at org.apache.spark.sql.execution.exchange.ShuffleExchangeLike.submitShuffleJob$(ShuffleExchangeExec.scala:67)
  at org.apache.spark.sql.execution.ColumnarShuffleExchangeAdaptor.submitShuffleJob(ColumnarShuffleExchangeExec.scala:168)
  at org.apache.spark.sql.execution.adaptive.ShuffleQueryStageExec.shuffleFuture$lzycompute(QueryStageExec.scala:174)
  at org.apache.spark.sql.execution.adaptive.ShuffleQueryStageExec.shuffleFuture(QueryStageExec.scala:174)
  at org.apache.spark.sql.execution.adaptive.ShuffleQueryStageExec.doMaterialize(QueryStageExec.scala:176)
  at org.apache.spark.sql.execution.adaptive.QueryStageExec.materialize(QueryStageExec.scala:82)
  at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$getFinalPhysicalPlan$5(AdaptiveSparkPlanExec.scala:260)
  at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$getFinalPhysicalPlan$5$adapted(AdaptiveSparkPlanExec.scala:258)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  at scala.collection.IterableLike.foreach(IterableLike.scala:74)
  at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
  at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$getFinalPhysicalPlan$1(AdaptiveSparkPlanExec.scala:258)
  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
  at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.getFinalPhysicalPlan(AdaptiveSparkPlanExec.scala:230)
  at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.withFinalPlanUpdate(AdaptiveSparkPlanExec.scala:372)
  at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.executeCollect(AdaptiveSparkPlanExec.scala:345)
  at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:3868)
  at org.apache.spark.sql.Dataset.$anonfun$head$1(Dataset.scala:2863)
  at org.apache.spark.sql.Dataset.$anonfun$withAction$2(Dataset.scala:3858)
  at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:510)
  at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3856)
  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:109)
  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:95)
  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3856)
  at org.apache.spark.sql.Dataset.head(Dataset.scala:2863)
  at org.apache.spark.sql.Dataset.take(Dataset.scala:3084)
  at org.apache.spark.sql.Dataset.getRows(Dataset.scala:288)
  at org.apache.spark.sql.Dataset.showString(Dataset.scala:327)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:808)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:767)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:776)
  ... 47 elided
  ```
</details>

**Comment by FelixYBW** [comment]
@zhouyuan Is it related to s3?

**Comment by zhouyuan** [comment]
Hi @j-buczak,


The call stack from the error message showed gluten executed some code should not go to - highly like a bug under some special cases


I made some tests with a local Minio setup and not able to re-produce the issue, can you please also help to check:
- is S3 support included? should compiled with `--enable_s3=ON`, e.g., `./dev/buildbundle-veloxbe.sh --enable_s3=ON`
- does simple query(`select l_orderkey from lineitem limit 10`) work? 


in the configuration you showed, it seems aws-sdk and hadoop-aws jars are missing, I assume those jars are already placed in the classpath, otherwise vanilla spark can not read from your minio setup?    

`spark.driver.extraClassPath /opt/gluten-jars/gluten-spark3.3_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar`

-yuan

**Comment by j-buczak** [comment]
I just put `aws-sdk` and `hadoop-aws` in `SPARK_HOME/jars` folder:

```sh
aws-java-sdk-1.12.214.jar
aws-java-sdk-core-1.12.214.jar
aws-java-sdk-dynamodb-1.12.214.jar
aws-java-sdk-kms-1.12.214.jar
aws-java-sdk-s3-1.12.214.jar
hadoop-aws-3.3.1.jar
```

I also put `spark-hadoop-cloud_2.12-3.3.1.jar`, which is suggested in [Spark cloud integration documentation](https://spark.apache.org/docs/latest/cloud-integration.html)

**Comment by jinchengchenghh** [comment]
Can this issue be closed? @zhouyuan

**Comment by zhouyuan** [comment]
closing as the issue is fixed by using correct config
