### ISSUE TITLE
Gluten + Velox backend does not support Struct dataset with same element name.

### ISSUE THREAD

**Issue by JkSelf** [oap-project/gluten#815]
**Describe the bug**
When the Struct schema is Struct(id, id), Gluten + Velox backend will throw following exception:
`java.lang.ArrayIndexOutOfBoundsException: 1
        at org.apache.spark.sql.execution.vectorized.WritableColumnVector.getChild(WritableColumnVector.java:671)
        at io.glutenproject.execution.RowToColumnConverter$StructConverter.$anonfun$append$2(GlutenRowToArrowColumnarExec.scala:140)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
        at io.glutenproject.execution.RowToColumnConverter$StructConverter.append(GlutenRowToArrowColumnarExec.scala:139)
        at io.glutenproject.execution.RowToColumnConverter.convert(GlutenRowToArrowColumnarExec.scala:46)
        at io.glutenproject.execution.GlutenRowToArrowColumnarExec$$anon$1.next(GlutenRowToArrowColumnarExec.scala:292)
        at io.glutenproject.execution.GlutenRowToArrowColumnarExec$$anon$1.next(GlutenRowToArrowColumnarExec.scala:276)
        at org.apache.spark.sql.execution.datasources.v2.arrow.SparkMemoryUtil$UnsafeItr.next(SparkMemoryUtil.scala:41)
        at org.apache.spark.sql.execution.datasources.v2.arrow.SparkMemoryUtil$UnsafeItr.next(SparkMemoryUtil.scala:26)
        at io.glutenproject.backendsapi.glutendata.GlutenSparkPlanExecApi.$anonfun$createBroadcastRelation$1(GlutenSparkPlanExecApi.scala:232)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1491)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`
**To Reproduce**
Remove the exclude test [here  ](https://github.com/oap-project/gluten/blob/28a10fa6cafc18f4693d81c053ccc1fa2bf23c36/gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala#L166) and Run GlutenInnerJoinSuite.

**Expected behavior**

**Additional context**
It is because that the field name used as the key in Map, and the value will be replaced if the field name is same when initialize the StructVector [here](https://github.com/apache/arrow/blob/d2481a610f7653e1b965366461dd6be0c22c1fda/java/vector/src/main/java/org/apache/arrow/vector/complex/NonNullableStructVector.java#LL431C51-L431C66).

**Comment by rui-mo** [comment]
I was just debugging this issue, and found there was a config in Arrow controlling this behaviour at [AbstractStructVector](https://github.com/oap-project/arrow/blob/backend_velox_main/java/vector/src/main/java/org/apache/arrow/vector/complex/AbstractStructVector.java#L51-L64). Therefore, we can resolve this issue by setting below config to the JVM.
```
-Darrow.struct.conflict.policy=CONFLICT_APPEND
```
