### ISSUE TITLE
NullType issue

### ISSUE THREAD

**Issue by PHILO-HE** [oap-project/gluten#911]
**Describe the bug**
```
java.lang.UnsupportedOperationException: Unsupported data type: void
	at org.apache.spark.sql.utils.SparkArrowUtil$.toArrowType(SparkArrowUtil.scala:56)
	at org.apache.spark.sql.utils.SparkArrowUtil$.toArrowField(SparkArrowUtil.scala:102)
	at org.apache.spark.sql.utils.SparkArrowUtil$.$anonfun$toArrowSchema$1(SparkArrowUtil.scala:131)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at org.apache.spark.sql.types.StructType.foreach(StructType.scala:102)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at org.apache.spark.sql.types.StructType.map(StructType.scala:102)
	at org.apache.spark.sql.utils.SparkArrowUtil$.toArrowSchema(SparkArrowUtil.scala:130)
	at org.apache.spark.sql.utils.SparkArrowUtil.toArrowSchema(SparkArrowUtil.scala)
	at io.glutenproject.vectorized.ArrowWritableColumnVector.allocateColumns(ArrowWritableColumnVector.java:101)
	at io.glutenproject.execution.GlutenRowToArrowColumnarExec$$anon$1.next(GlutenRowToArrowColumnarExec.scala:287)
	at io.glutenproject.execution.GlutenRowToArrowColumnarExec$$anon$1.next(GlutenRowToArrowColumnarExec.scala:276)
	at org.apache.spark.sql.execution.datasources.v2.arrow.SparkMemoryUtil$UnsafeItr.next(SparkMemoryUtil.scala:41)
	at org.apache.spark.sql.execution.datasources.v2.arrow.SparkMemoryUtil$UnsafeItr.next(SparkMemoryUtil.scala:26)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage3.columnartorow_nextBatch_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage3.agg_doAggregateWithKeys_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage3.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:140)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1491)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by PHILO-HE** [comment]
Currently, we still let the relevant operator fall back if NullType is used. There will be a lot of code changes in velox to fully support this type.
